-- ItemScoreData.lua
--
-- GENERATED FILE -- do not edit by hand.
-- Weights:   this addon's own, worked out from the game's formulas and
--            calibrated toward Pawn's Classic Era scales (HawsJon's), in
--            Tools/data/stat_weights.json. Turtle WoW's own stats keep
--            OctoPawn's weight, rescaled.
-- Patterns:  OctoPawn's stat patterns, soft caps and labels
--            (https://github.com/iGreed1993/OctoPawn)
-- Generator: Tools/build/build_weights.py (OctoPawn's data through
--            Tools/build/import_octopawn.py)
--
-- OctoPawn's licence, which covers its data:
--
-- MIT License
--
-- Copyright (c) 2026 iGreed
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in all
-- copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-- SOFTWARE.

AegisPathfinder.ItemScoreData = {
	-- Every stat the scorer knows, in a fixed order (the options panel's).
	stats = {
		"AGILITY",
		"ALL RESISTANCES",
		"ARCANE DAMAGE",
		"ARCANE RESISTANCE",
		"ARMOR",
		"ARMOR PENETRATION",
		"ATTACK POWER",
		"ATTACK POWER UNDEAD",
		"AVOIDANCE",
		"BLOCK",
		"BLOCK VALUE",
		"CASTING REGEN",
		"CRIT",
		"DEFENSE",
		"DODGE",
		"DPS",
		"EXTRA ATTACK",
		"FERAL ATTACK POWER",
		"FIRE DAMAGE",
		"FIRE RESISTANCE",
		"FORTUNE",
		"FROST DAMAGE",
		"FROST RESISTANCE",
		"HASTE",
		"HEALING",
		"HEALTH",
		"HEALTH PER 5",
		"HIT",
		"HOLY CRIT",
		"HOLY DAMAGE",
		"INTELLECT",
		"LIFESTEAL",
		"MANA",
		"MANA PER 5",
		"MOUNT SPEED",
		"MOVEMENT SPEED",
		"NATURE DAMAGE",
		"NATURE RESISTANCE",
		"PARRY",
		"RANGED ATTACK POWER",
		"RANGED CRIT",
		"RANGED DPS",
		"RANGED HASTE",
		"RESILIENCE",
		"SHADOW DAMAGE",
		"SHADOW RESISTANCE",
		"SPELL CRIT",
		"SPELL DAMAGE",
		"SPELL DAMAGE UNDEAD",
		"SPELL HIT",
		"SPELL PENETRATION",
		"SPELL POWER",
		"SPIRIT",
		"STAMINA",
		"STRENGTH",
	},
	-- How the options panel names a stat.
	labels = {
		["AVOIDANCE"] = "AVOIDANCE %",
		["BLOCK"] = "BLOCK %",
		["CASTING REGEN"] = "CASTING REGEN %",
		["CRIT"] = "CRIT %",
		["DODGE"] = "DODGE %",
		["DPS"] = "WEAPON DPS",
		["EXTRA ATTACK"] = "EXTRA ATTACK %",
		["HASTE"] = "HASTE %",
		["HIT"] = "HIT %",
		["HOLY CRIT"] = "HOLY CRIT %",
		["LIFESTEAL"] = "LIFESTEAL %",
		["MOUNT SPEED"] = "MOUNT SPEED %",
		["MOVEMENT SPEED"] = "MOVEMENT SPEED %",
		["PARRY"] = "PARRY %",
		["RANGED CRIT"] = "RANGED CRIT %",
		["RANGED DPS"] = "RANGED WEAPON DPS",
		["RANGED HASTE"] = "RANGED HASTE %",
		["RESILIENCE"] = "RESILIENCE %",
		["SPELL CRIT"] = "SPELL CRIT %",
		["SPELL HIT"] = "SPELL HIT %",
	},
	-- class -> spec -> stat -> weight at level 60 (a stat with no weight counts 0).
	weights = {
		WARRIOR = {
			Arms = {
				["AGILITY"] = 1.44,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.013,
				["ARMOR PENETRATION"] = 1.35,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 17.5,
				["DEFENSE"] = 0.147,
				["DODGE"] = 1.27,
				["DPS"] = 12.9,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 11.6,
				["HEALTH"] = 0.023,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 20.4,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 1.27,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.072,
				["STAMINA"] = 0.229,
				["STRENGTH"] = 2.16,
			},
			Fury = {
				["AGILITY"] = 1.11,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.011,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 13.5,
				["DEFENSE"] = 0.128,
				["DODGE"] = 1.13,
				["DPS"] = 10.3,
				["EXTRA ATTACK"] = 3.6,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 8.26,
				["HEALTH"] = 0.02,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 12.2,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.19,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.063,
				["STAMINA"] = 0.2,
				["STRENGTH"] = 1.89,
			},
			Protection = {
				["AGILITY"] = 0.665,
				["ALL RESISTANCES"] = 0.562,
				["ARCANE RESISTANCE"] = 0.156,
				["ARMOR"] = 0.03,
				["ARMOR PENETRATION"] = 0.188,
				["ATTACK POWER"] = 0.075,
				["AVOIDANCE"] = 1,
				["BLOCK"] = 4.66,
				["BLOCK VALUE"] = 0.322,
				["CRIT"] = 2.52,
				["DEFENSE"] = 1.28,
				["DODGE"] = 8.11,
				["DPS"] = 3.1,
				["EXTRA ATTACK"] = 0.5,
				["FIRE RESISTANCE"] = 0.156,
				["FORTUNE"] = 0.312,
				["FROST RESISTANCE"] = 0.156,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.562,
				["HIT"] = 6.46,
				["LIFESTEAL"] = 0.625,
				["MOUNT SPEED"] = 0.05,
				["MOVEMENT SPEED"] = 0.094,
				["NATURE RESISTANCE"] = 0.156,
				["PARRY"] = 6.8,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.156,
				["SPIRIT"] = 0.04,
				["STAMINA"] = 1,
				["STRENGTH"] = 0.335,
			},
		},
		PALADIN = {
			Holy = {
				["AGILITY"] = 0.07,
				["ALL RESISTANCES"] = 0.357,
				["ARCANE RESISTANCE"] = 0.086,
				["ARMOR"] = 0.009,
				["AVOIDANCE"] = 0.25,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.108,
				["DODGE"] = 0.605,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.086,
				["FORTUNE"] = 0.357,
				["FROST RESISTANCE"] = 0.086,
				["HASTE"] = 5.59,
				["HEALING"] = 1,
				["HEALTH"] = 0.018,
				["HEALTH PER 5"] = 0.214,
				["HOLY CRIT"] = 12,
				["HOLY DAMAGE"] = 0.15,
				["INTELLECT"] = 1.59,
				["LIFESTEAL"] = 0.143,
				["MANA"] = 0.079,
				["MANA PER 5"] = 2.22,
				["MOUNT SPEED"] = 0.057,
				["MOVEMENT SPEED"] = 0.143,
				["NATURE RESISTANCE"] = 0.086,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.086,
				["SPELL CRIT"] = 7.85,
				["SPELL DAMAGE"] = 0.15,
				["SPELL HIT"] = 0.05,
				["SPELL POWER"] = 0.15,
				["SPIRIT"] = 0.38,
				["STAMINA"] = 0.176,
				["STRENGTH"] = 0.02,
			},
			Protection = {
				["AGILITY"] = 0.673,
				["ALL RESISTANCES"] = 0.562,
				["ARCANE RESISTANCE"] = 0.156,
				["ARMOR"] = 0.03,
				["ARMOR PENETRATION"] = 0.188,
				["ATTACK POWER"] = 0.075,
				["AVOIDANCE"] = 1,
				["BLOCK"] = 5.03,
				["BLOCK VALUE"] = 0.185,
				["CRIT"] = 1.58,
				["DEFENSE"] = 1.15,
				["DODGE"] = 8.11,
				["DPS"] = 2.02,
				["EXTRA ATTACK"] = 0.5,
				["FIRE RESISTANCE"] = 0.156,
				["FORTUNE"] = 0.312,
				["FROST RESISTANCE"] = 0.156,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.562,
				["HIT"] = 2.21,
				["HOLY DAMAGE"] = 0.454,
				["INTELLECT"] = 0.44,
				["LIFESTEAL"] = 0.625,
				["MANA"] = 0.029,
				["MANA PER 5"] = 0.88,
				["MOUNT SPEED"] = 0.05,
				["MOVEMENT SPEED"] = 0.094,
				["NATURE RESISTANCE"] = 0.156,
				["PARRY"] = 6.97,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.156,
				["SPELL POWER"] = 0.454,
				["SPIRIT"] = 0.04,
				["STAMINA"] = 1,
				["STRENGTH"] = 0.23,
			},
			Retribution = {
				["AGILITY"] = 1.43,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.014,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 15.2,
				["DEFENSE"] = 0.157,
				["DODGE"] = 1.34,
				["DPS"] = 13.4,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 6.69,
				["HEALTH"] = 0.025,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 19.2,
				["HOLY CRIT"] = 4.18,
				["HOLY DAMAGE"] = 0.629,
				["INTELLECT"] = 0.668,
				["LIFESTEAL"] = 1.4,
				["MANA"] = 0.045,
				["MANA PER 5"] = 1.85,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 1.34,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPELL POWER"] = 0.629,
				["SPIRIT"] = 0.098,
				["STAMINA"] = 0.245,
				["STRENGTH"] = 2.32,
			},
		},
		HUNTER = {
			BeastMastery = {
				["AGILITY"] = 2.35,
				["ALL RESISTANCES"] = 0.36,
				["ARCANE RESISTANCE"] = 0.096,
				["ARMOR"] = 0.013,
				["ARMOR PENETRATION"] = 0.88,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.32,
				["AVOIDANCE"] = 0.28,
				["CRIT"] = 17,
				["DEFENSE"] = 0.152,
				["DODGE"] = 1.29,
				["DPS"] = 1.52,
				["EXTRA ATTACK"] = 2.4,
				["FIRE RESISTANCE"] = 0.096,
				["FORTUNE"] = 0.8,
				["FROST RESISTANCE"] = 0.096,
				["HASTE"] = 10.9,
				["HEALTH"] = 0.024,
				["HEALTH PER 5"] = 0.2,
				["HIT"] = 21.1,
				["INTELLECT"] = 1.23,
				["LIFESTEAL"] = 1.12,
				["MANA"] = 0.082,
				["MANA PER 5"] = 3.43,
				["MOUNT SPEED"] = 0.064,
				["MOVEMENT SPEED"] = 0.16,
				["NATURE RESISTANCE"] = 0.096,
				["RANGED ATTACK POWER"] = 1,
				["RANGED CRIT"] = 17,
				["RANGED DPS"] = 16.1,
				["RANGED HASTE"] = 17.1,
				["SHADOW RESISTANCE"] = 0.096,
				["SPIRIT"] = 0.094,
				["STAMINA"] = 0.237,
				["STRENGTH"] = 0.112,
			},
			Marksmanship = {
				["AGILITY"] = 1.97,
				["ALL RESISTANCES"] = 0.333,
				["ARCANE RESISTANCE"] = 0.089,
				["ARMOR"] = 0.011,
				["ARMOR PENETRATION"] = 0.667,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.296,
				["AVOIDANCE"] = 0.259,
				["CRIT"] = 11.8,
				["DEFENSE"] = 0.126,
				["DODGE"] = 1.12,
				["DPS"] = 1.26,
				["EXTRA ATTACK"] = 2.22,
				["FIRE RESISTANCE"] = 0.089,
				["FORTUNE"] = 0.741,
				["FROST RESISTANCE"] = 0.089,
				["HASTE"] = 7.64,
				["HEALTH"] = 0.02,
				["HEALTH PER 5"] = 0.185,
				["HIT"] = 17.5,
				["INTELLECT"] = 1.11,
				["LIFESTEAL"] = 1.04,
				["MANA"] = 0.074,
				["MANA PER 5"] = 2.86,
				["MOUNT SPEED"] = 0.059,
				["MOVEMENT SPEED"] = 0.148,
				["NATURE RESISTANCE"] = 0.089,
				["RANGED ATTACK POWER"] = 1,
				["RANGED CRIT"] = 11.8,
				["RANGED DPS"] = 16.8,
				["RANGED HASTE"] = 17.1,
				["SHADOW RESISTANCE"] = 0.089,
				["SPIRIT"] = 0.078,
				["STAMINA"] = 0.197,
				["STRENGTH"] = 0.093,
			},
			Survival = {
				["AGILITY"] = 1.96,
				["ALL RESISTANCES"] = 0.391,
				["ARCANE RESISTANCE"] = 0.104,
				["ARMOR"] = 0.011,
				["ARMOR PENETRATION"] = 0.957,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.348,
				["AVOIDANCE"] = 0.304,
				["CRIT"] = 12.3,
				["DEFENSE"] = 0.126,
				["DODGE"] = 1.1,
				["DPS"] = 1.57,
				["EXTRA ATTACK"] = 2.61,
				["FIRE RESISTANCE"] = 0.104,
				["FORTUNE"] = 0.87,
				["FROST RESISTANCE"] = 0.104,
				["HASTE"] = 7.64,
				["HEALTH"] = 0.02,
				["HEALTH PER 5"] = 0.217,
				["HIT"] = 17.5,
				["INTELLECT"] = 1.02,
				["LIFESTEAL"] = 1.04,
				["MANA"] = 0.068,
				["MANA PER 5"] = 2.86,
				["MOUNT SPEED"] = 0.07,
				["MOVEMENT SPEED"] = 0.174,
				["NATURE RESISTANCE"] = 0.104,
				["RANGED ATTACK POWER"] = 1,
				["RANGED CRIT"] = 12.3,
				["RANGED DPS"] = 15.4,
				["RANGED HASTE"] = 17.1,
				["SHADOW RESISTANCE"] = 0.104,
				["SPIRIT"] = 0.078,
				["STAMINA"] = 0.197,
				["STRENGTH"] = 0.093,
			},
		},
		ROGUE = {
			Assassination = {
				["AGILITY"] = 2.13,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.013,
				["ARMOR PENETRATION"] = 1.25,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 17.2,
				["DEFENSE"] = 0.147,
				["DODGE"] = 1.3,
				["DPS"] = 7.82,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 16.7,
				["HEALTH"] = 0.023,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 20.9,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.51,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.072,
				["STAMINA"] = 0.229,
				["STRENGTH"] = 1.08,
			},
			Combat = {
				["AGILITY"] = 2.1,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.013,
				["ARMOR PENETRATION"] = 1.15,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 16.5,
				["DEFENSE"] = 0.147,
				["DODGE"] = 1.25,
				["DPS"] = 8.03,
				["EXTRA ATTACK"] = 3.4,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 17.1,
				["HEALTH"] = 0.023,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 21.3,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.4,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.072,
				["STAMINA"] = 0.229,
				["STRENGTH"] = 1.08,
			},
			Subtlety = {
				["AGILITY"] = 2.1,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.013,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 16.5,
				["DEFENSE"] = 0.147,
				["DODGE"] = 1.25,
				["DPS"] = 7.82,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1.15,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 16.3,
				["HEALTH"] = 0.023,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 20.4,
				["LIFESTEAL"] = 1.6,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.4,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.072,
				["STAMINA"] = 0.229,
				["STRENGTH"] = 1.08,
			},
		},
		PRIEST = {
			Discipline = {
				["AGILITY"] = 0.056,
				["ALL RESISTANCES"] = 0.4,
				["ARCANE RESISTANCE"] = 0.096,
				["ARMOR"] = 0.008,
				["AVOIDANCE"] = 0.28,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.087,
				["DODGE"] = 0.487,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.096,
				["FORTUNE"] = 0.4,
				["FROST RESISTANCE"] = 0.096,
				["HASTE"] = 5.99,
				["HEALING"] = 1,
				["HEALTH"] = 0.014,
				["HEALTH PER 5"] = 0.24,
				["HOLY CRIT"] = 6,
				["HOLY DAMAGE"] = 0.15,
				["INTELLECT"] = 1.21,
				["LIFESTEAL"] = 0.16,
				["MANA"] = 0.06,
				["MANA PER 5"] = 1.83,
				["MOUNT SPEED"] = 0.064,
				["MOVEMENT SPEED"] = 0.16,
				["NATURE RESISTANCE"] = 0.096,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.096,
				["SPELL CRIT"] = 4.05,
				["SPELL DAMAGE"] = 0.15,
				["SPELL HIT"] = 0.05,
				["SPELL POWER"] = 0.15,
				["SPIRIT"] = 0.649,
				["STAMINA"] = 0.142,
				["STRENGTH"] = 0.02,
			},
			Holy = {
				["AGILITY"] = 0.052,
				["ALL RESISTANCES"] = 0.345,
				["ARCANE RESISTANCE"] = 0.083,
				["ARMOR"] = 0.007,
				["AVOIDANCE"] = 0.241,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.079,
				["DODGE"] = 0.446,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.083,
				["FORTUNE"] = 0.345,
				["FROST RESISTANCE"] = 0.083,
				["HASTE"] = 5.7,
				["HEALING"] = 1,
				["HEALTH"] = 0.013,
				["HEALTH PER 5"] = 0.207,
				["HOLY CRIT"] = 6,
				["HOLY DAMAGE"] = 0.1,
				["INTELLECT"] = 1.07,
				["LIFESTEAL"] = 0.138,
				["MANA"] = 0.054,
				["MANA PER 5"] = 1.84,
				["MOUNT SPEED"] = 0.055,
				["MOVEMENT SPEED"] = 0.138,
				["NATURE RESISTANCE"] = 0.083,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.083,
				["SPELL CRIT"] = 2.99,
				["SPELL DAMAGE"] = 0.1,
				["SPELL HIT"] = 0.05,
				["SPELL POWER"] = 0.1,
				["SPIRIT"] = 0.846,
				["STAMINA"] = 0.13,
				["STRENGTH"] = 0.02,
			},
			Shadow = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 5.98,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.011,
				["HEALTH PER 5"] = 0.19,
				["HOLY DAMAGE"] = 0.2,
				["INTELLECT"] = 0.202,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.011,
				["MANA PER 5"] = 1.19,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW DAMAGE"] = 1,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 4.87,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.524,
				["SPELL HIT"] = 9.21,
				["SPELL PENETRATION"] = 0.132,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.174,
				["STAMINA"] = 0.111,
				["STRENGTH"] = 0.02,
			},
		},
		SHAMAN = {
			Elemental = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.5,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.4,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 7.63,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.011,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.334,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.013,
				["MANA PER 5"] = 1.31,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE DAMAGE"] = 1,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 8.77,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 7.82,
				["SPELL PENETRATION"] = 0.426,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.092,
				["STAMINA"] = 0.111,
				["STRENGTH"] = 0.02,
			},
			Enhancement = {
				["AGILITY"] = 1.61,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.012,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 18.4,
				["DEFENSE"] = 0.136,
				["DODGE"] = 1.2,
				["DPS"] = 7.59,
				["EXTRA ATTACK"] = 3,
				["FIRE DAMAGE"] = 0.125,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST DAMAGE"] = 0.15,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 12,
				["HEALTH"] = 0.021,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 14.3,
				["INTELLECT"] = 0.576,
				["LIFESTEAL"] = 1.4,
				["MANA"] = 0.038,
				["MANA PER 5"] = 1.59,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE DAMAGE"] = 0.456,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 1.2,
				["RANGED DPS"] = 0.2,
				["SHADOW RESISTANCE"] = 0.12,
				["SPELL POWER"] = 0.482,
				["SPIRIT"] = 0.084,
				["STAMINA"] = 0.211,
				["STRENGTH"] = 2,
			},
			EnhancementTank = {
				["AGILITY"] = 0.95,
				["ALL RESISTANCES"] = 0.581,
				["ARCANE RESISTANCE"] = 0.161,
				["ARMOR"] = 0.1,
				["ARMOR PENETRATION"] = 0.194,
				["ATTACK POWER"] = 0.15,
				["AVOIDANCE"] = 0.903,
				["BLOCK"] = 7,
				["BLOCK VALUE"] = 0.25,
				["CRIT"] = 3,
				["DEFENSE"] = 1.5,
				["DODGE"] = 15,
				["DPS"] = 3,
				["EXTRA ATTACK"] = 0.516,
				["FIRE RESISTANCE"] = 0.161,
				["FORTUNE"] = 0.323,
				["FROST RESISTANCE"] = 0.161,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.581,
				["HIT"] = 7,
				["INTELLECT"] = 0.3,
				["LIFESTEAL"] = 0.645,
				["MANA"] = 0.02,
				["MANA PER 5"] = 0.6,
				["MOUNT SPEED"] = 0.052,
				["MOVEMENT SPEED"] = 0.097,
				["NATURE DAMAGE"] = 0.3,
				["NATURE RESISTANCE"] = 0.161,
				["PARRY"] = 13,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.161,
				["SPELL POWER"] = 0.3,
				["SPIRIT"] = 0.02,
				["STAMINA"] = 1,
				["STRENGTH"] = 0.35,
			},
			Restoration = {
				["AGILITY"] = 0.048,
				["ALL RESISTANCES"] = 0.357,
				["ARCANE RESISTANCE"] = 0.086,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.25,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.073,
				["DODGE"] = 0.412,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.086,
				["FORTUNE"] = 0.357,
				["FROST RESISTANCE"] = 0.086,
				["HASTE"] = 6.16,
				["HEALING"] = 1,
				["HEALTH"] = 0.012,
				["HEALTH PER 5"] = 0.214,
				["INTELLECT"] = 0.952,
				["LIFESTEAL"] = 0.143,
				["MANA"] = 0.048,
				["MANA PER 5"] = 1.69,
				["MOUNT SPEED"] = 0.057,
				["MOVEMENT SPEED"] = 0.143,
				["NATURE RESISTANCE"] = 0.086,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.086,
				["SPELL CRIT"] = 4.65,
				["SPELL DAMAGE"] = 0.1,
				["SPELL HIT"] = 0.05,
				["SPELL POWER"] = 0.1,
				["SPIRIT"] = 0.553,
				["STAMINA"] = 0.12,
				["STRENGTH"] = 0.02,
			},
		},
		MAGE = {
			Arcane = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.909,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.094,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.539,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 5.56,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.01,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.453,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.024,
				["MANA PER 5"] = 1.3,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 4.85,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 7.62,
				["SPELL PENETRATION"] = 0.145,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.419,
				["STAMINA"] = 0.105,
				["STRENGTH"] = 0.02,
			},
			Fire = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.194,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.955,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.315,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 7.12,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.01,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.43,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.018,
				["MANA PER 5"] = 1.1,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 6.77,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 8.01,
				["SPELL PENETRATION"] = 0.145,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.062,
				["STAMINA"] = 0.105,
				["STRENGTH"] = 0.02,
			},
			Frost = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.145,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.075,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.962,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 5.84,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.01,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.381,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.015,
				["MANA PER 5"] = 1.01,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 5.62,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 9.82,
				["SPELL PENETRATION"] = 0.12,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.057,
				["STAMINA"] = 0.105,
				["STRENGTH"] = 0.02,
			},
		},
		WARLOCK = {
			Affliction = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.409,
				["ARCANE RESISTANCE"] = 0.109,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.273,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.322,
				["FIRE RESISTANCE"] = 0.109,
				["FORTUNE"] = 0.773,
				["FROST RESISTANCE"] = 0.109,
				["HASTE"] = 6.86,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.013,
				["HEALTH PER 5"] = 0.182,
				["INTELLECT"] = 0.308,
				["LIFESTEAL"] = 0.227,
				["MANA"] = 0.015,
				["MANA PER 5"] = 1.05,
				["MOUNT SPEED"] = 0.073,
				["MOVEMENT SPEED"] = 0.182,
				["NATURE RESISTANCE"] = 0.109,
				["RANGED DPS"] = 0.5,
				["SHADOW DAMAGE"] = 0.932,
				["SHADOW RESISTANCE"] = 0.109,
				["SPELL CRIT"] = 2.95,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.545,
				["SPELL HIT"] = 9.7,
				["SPELL PENETRATION"] = 0.132,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.095,
				["STAMINA"] = 0.132,
				["STRENGTH"] = 0.02,
			},
			Demonology = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.673,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 6.32,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.013,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.349,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.015,
				["MANA PER 5"] = 1.05,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW DAMAGE"] = 0.846,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 5.21,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 9.7,
				["SPELL PENETRATION"] = 0.132,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.281,
				["STAMINA"] = 0.132,
				["STRENGTH"] = 0.02,
			},
			Destruction = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.409,
				["ARCANE RESISTANCE"] = 0.109,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.273,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.319,
				["FIRE RESISTANCE"] = 0.109,
				["FORTUNE"] = 0.773,
				["FROST RESISTANCE"] = 0.109,
				["HASTE"] = 9.18,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.012,
				["HEALTH PER 5"] = 0.182,
				["INTELLECT"] = 0.334,
				["LIFESTEAL"] = 0.227,
				["MANA"] = 0.011,
				["MANA PER 5"] = 0.758,
				["MOUNT SPEED"] = 0.073,
				["MOVEMENT SPEED"] = 0.182,
				["NATURE RESISTANCE"] = 0.109,
				["RANGED DPS"] = 0.5,
				["SHADOW DAMAGE"] = 0.962,
				["SHADOW RESISTANCE"] = 0.109,
				["SPELL CRIT"] = 7.62,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.364,
				["SPELL HIT"] = 12,
				["SPELL PENETRATION"] = 0.132,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.167,
				["STAMINA"] = 0.119,
				["STRENGTH"] = 0.02,
			},
		},
		DRUID = {
			Balance = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.697,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.006,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 1.5,
				["DEFENSE"] = 0.068,
				["DODGE"] = 0.381,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 6.99,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.011,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.379,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.017,
				["MANA PER 5"] = 0.79,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE DAMAGE"] = 0.531,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 5.5,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 9.76,
				["SPELL PENETRATION"] = 0.273,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.25,
				["STAMINA"] = 0.111,
				["STRENGTH"] = 0.02,
			},
			FeralBear = {
				["AGILITY"] = 0.605,
				["ALL RESISTANCES"] = 0.545,
				["ARCANE RESISTANCE"] = 0.152,
				["ARMOR"] = 0.107,
				["ARMOR PENETRATION"] = 0.182,
				["ATTACK POWER"] = 0.298,
				["AVOIDANCE"] = 0.97,
				["CRIT"] = 1.58,
				["DEFENSE"] = 0.546,
				["DODGE"] = 5.13,
				["EXTRA ATTACK"] = 0.485,
				["FERAL ATTACK POWER"] = 0.298,
				["FIRE RESISTANCE"] = 0.152,
				["FORTUNE"] = 0.303,
				["FROST RESISTANCE"] = 0.152,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.545,
				["HIT"] = 2.21,
				["INTELLECT"] = 0.1,
				["LIFESTEAL"] = 0.606,
				["MOUNT SPEED"] = 0.048,
				["MOVEMENT SPEED"] = 0.091,
				["NATURE RESISTANCE"] = 0.152,
				["SHADOW RESISTANCE"] = 0.152,
				["SPIRIT"] = 0.04,
				["STAMINA"] = 1,
				["STRENGTH"] = 0.245,
			},
			FeralCat = {
				["AGILITY"] = 1.78,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.381,
				["AVOIDANCE"] = 0.333,
				["CRIT"] = 10.6,
				["DEFENSE"] = 0.12,
				["DODGE"] = 1.02,
				["EXTRA ATTACK"] = 2.86,
				["FERAL ATTACK POWER"] = 1,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.952,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 7.65,
				["HEALTH"] = 0.019,
				["HEALTH PER 5"] = 0.238,
				["HIT"] = 11.5,
				["INTELLECT"] = 0.164,
				["LIFESTEAL"] = 1.33,
				["MANA"] = 0.011,
				["MANA PER 5"] = 0.446,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["SHADOW RESISTANCE"] = 0.114,
				["SPIRIT"] = 0.059,
				["STAMINA"] = 0.187,
				["STRENGTH"] = 2.37,
			},
			Restoration = {
				["AGILITY"] = 0.038,
				["ALL RESISTANCES"] = 0.345,
				["ARCANE RESISTANCE"] = 0.083,
				["ARMOR"] = 0.005,
				["AVOIDANCE"] = 0.241,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.059,
				["DODGE"] = 0.33,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.083,
				["FORTUNE"] = 0.345,
				["FROST RESISTANCE"] = 0.083,
				["HASTE"] = 3.62,
				["HEALING"] = 1,
				["HEALTH"] = 0.01,
				["HEALTH PER 5"] = 0.207,
				["INTELLECT"] = 0.763,
				["LIFESTEAL"] = 0.138,
				["MANA"] = 0.038,
				["MANA PER 5"] = 1.62,
				["MOUNT SPEED"] = 0.055,
				["MOVEMENT SPEED"] = 0.138,
				["NATURE RESISTANCE"] = 0.083,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.083,
				["SPELL CRIT"] = 2.81,
				["SPELL DAMAGE"] = 0.1,
				["SPELL HIT"] = 0.05,
				["SPELL POWER"] = 0.1,
				["SPIRIT"] = 0.687,
				["STAMINA"] = 0.096,
				["STRENGTH"] = 0.02,
			},
		},
	},
	-- The same below level 60. A spec not here -- the tanks -- uses its 60 set.
	leveling = {
		WARRIOR = {
			Arms = {
				["AGILITY"] = 0.925,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.35,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["BLOCK"] = 1.32,
				["BLOCK VALUE"] = 0.15,
				["CRIT"] = 5.07,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.84,
				["DPS"] = 12.9,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 3.35,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 5.9,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 1.47,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 1,
				["STRENGTH"] = 2.16,
			},
			Fury = {
				["AGILITY"] = 0.707,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["BLOCK"] = 1.43,
				["BLOCK VALUE"] = 0.15,
				["CRIT"] = 3.9,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.64,
				["DPS"] = 10.3,
				["EXTRA ATTACK"] = 3.6,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 2.39,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 3.53,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.53,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 1,
				["STRENGTH"] = 1.89,
			},
		},
		PALADIN = {
			Holy = {
				["AGILITY"] = 0.07,
				["ALL RESISTANCES"] = 0.357,
				["ARCANE RESISTANCE"] = 0.086,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.25,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.2,
				["DODGE"] = 3.02,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.086,
				["FORTUNE"] = 0.357,
				["FROST RESISTANCE"] = 0.086,
				["HASTE"] = 3.35,
				["HEALING"] = 1,
				["HEALTH"] = 0.05,
				["HEALTH PER 5"] = 0.214,
				["HOLY CRIT"] = 5,
				["HOLY DAMAGE"] = 0.4,
				["INTELLECT"] = 1.59,
				["LIFESTEAL"] = 0.143,
				["MANA"] = 0.079,
				["MANA PER 5"] = 2.22,
				["MOUNT SPEED"] = 0.057,
				["MOVEMENT SPEED"] = 0.143,
				["NATURE RESISTANCE"] = 0.086,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.086,
				["SPELL CRIT"] = 3.27,
				["SPELL DAMAGE"] = 0.4,
				["SPELL HIT"] = 0.3,
				["SPELL POWER"] = 0.4,
				["SPIRIT"] = 0.38,
				["STAMINA"] = 0.5,
				["STRENGTH"] = 0.15,
			},
			Retribution = {
				["AGILITY"] = 0.926,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["BLOCK"] = 1.21,
				["BLOCK VALUE"] = 0.15,
				["CRIT"] = 4.4,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.93,
				["DPS"] = 13.4,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 1.94,
				["HEALING"] = 0.15,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 5.55,
				["HOLY CRIT"] = 1.21,
				["HOLY DAMAGE"] = 0.839,
				["INTELLECT"] = 0.668,
				["LIFESTEAL"] = 1.4,
				["MANA"] = 0.045,
				["MANA PER 5"] = 1.85,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 1.55,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPELL POWER"] = 0.839,
				["SPIRIT"] = 0.2,
				["STAMINA"] = 1,
				["STRENGTH"] = 2.32,
			},
		},
		HUNTER = {
			BeastMastery = {
				["AGILITY"] = 2.25,
				["ALL RESISTANCES"] = 0.36,
				["ARCANE RESISTANCE"] = 0.096,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 0.88,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.32,
				["AVOIDANCE"] = 0.28,
				["CRIT"] = 4.91,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.87,
				["DPS"] = 4.55,
				["EXTRA ATTACK"] = 2.4,
				["FIRE RESISTANCE"] = 0.096,
				["FORTUNE"] = 0.8,
				["FROST RESISTANCE"] = 0.096,
				["HASTE"] = 3.14,
				["HEALTH"] = 0.08,
				["HEALTH PER 5"] = 0.2,
				["HIT"] = 6.1,
				["INTELLECT"] = 1.23,
				["LIFESTEAL"] = 1.12,
				["MANA"] = 0.082,
				["MANA PER 5"] = 3.43,
				["MOUNT SPEED"] = 0.064,
				["MOVEMENT SPEED"] = 0.16,
				["NATURE RESISTANCE"] = 0.096,
				["RANGED ATTACK POWER"] = 1,
				["RANGED CRIT"] = 4.91,
				["RANGED DPS"] = 16.1,
				["RANGED HASTE"] = 4.95,
				["SHADOW RESISTANCE"] = 0.096,
				["SPIRIT"] = 0.2,
				["STAMINA"] = 0.8,
				["STRENGTH"] = 0.112,
			},
			Marksmanship = {
				["AGILITY"] = 1.86,
				["ALL RESISTANCES"] = 0.333,
				["ARCANE RESISTANCE"] = 0.089,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 0.667,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.296,
				["AVOIDANCE"] = 0.259,
				["CRIT"] = 3.43,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.62,
				["DPS"] = 3.79,
				["EXTRA ATTACK"] = 2.22,
				["FIRE RESISTANCE"] = 0.089,
				["FORTUNE"] = 0.741,
				["FROST RESISTANCE"] = 0.089,
				["HASTE"] = 2.21,
				["HEALTH"] = 0.08,
				["HEALTH PER 5"] = 0.185,
				["HIT"] = 5.07,
				["INTELLECT"] = 1.11,
				["LIFESTEAL"] = 1.04,
				["MANA"] = 0.074,
				["MANA PER 5"] = 2.86,
				["MOUNT SPEED"] = 0.059,
				["MOVEMENT SPEED"] = 0.148,
				["NATURE RESISTANCE"] = 0.089,
				["RANGED ATTACK POWER"] = 1,
				["RANGED CRIT"] = 3.43,
				["RANGED DPS"] = 16.8,
				["RANGED HASTE"] = 4.95,
				["SHADOW RESISTANCE"] = 0.089,
				["SPIRIT"] = 0.2,
				["STAMINA"] = 0.8,
				["STRENGTH"] = 0.093,
			},
			Survival = {
				["AGILITY"] = 1.87,
				["ALL RESISTANCES"] = 0.391,
				["ARCANE RESISTANCE"] = 0.104,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 0.957,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.348,
				["AVOIDANCE"] = 0.304,
				["CRIT"] = 3.57,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.59,
				["DPS"] = 4.7,
				["EXTRA ATTACK"] = 2.61,
				["FIRE RESISTANCE"] = 0.104,
				["FORTUNE"] = 0.87,
				["FROST RESISTANCE"] = 0.104,
				["HASTE"] = 2.21,
				["HEALTH"] = 0.08,
				["HEALTH PER 5"] = 0.217,
				["HIT"] = 5.07,
				["INTELLECT"] = 1.02,
				["LIFESTEAL"] = 1.04,
				["MANA"] = 0.068,
				["MANA PER 5"] = 2.86,
				["MOUNT SPEED"] = 0.07,
				["MOVEMENT SPEED"] = 0.174,
				["NATURE RESISTANCE"] = 0.104,
				["RANGED ATTACK POWER"] = 1,
				["RANGED CRIT"] = 3.57,
				["RANGED DPS"] = 15.4,
				["RANGED HASTE"] = 4.95,
				["SHADOW RESISTANCE"] = 0.104,
				["SPIRIT"] = 0.2,
				["STAMINA"] = 0.8,
				["STRENGTH"] = 0.093,
			},
		},
		ROGUE = {
			Assassination = {
				["AGILITY"] = 1.8,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.25,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 4.99,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.88,
				["DPS"] = 7.82,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 4.84,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 6.04,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.9,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 1,
				["STRENGTH"] = 1.08,
			},
			Combat = {
				["AGILITY"] = 1.81,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.15,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 4.79,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.8,
				["DPS"] = 8.03,
				["EXTRA ATTACK"] = 3.4,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 4.94,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 6.17,
				["LIFESTEAL"] = 1.4,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.78,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 1,
				["STRENGTH"] = 1.08,
			},
			Subtlety = {
				["AGILITY"] = 1.81,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["CRIT"] = 4.79,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.8,
				["DPS"] = 7.82,
				["EXTRA ATTACK"] = 3,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1.15,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 4.72,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 5.9,
				["LIFESTEAL"] = 1.6,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 2.78,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 1,
				["STRENGTH"] = 1.08,
			},
		},
		PRIEST = {
			Discipline = {
				["AGILITY"] = 0.056,
				["ALL RESISTANCES"] = 0.4,
				["ARCANE RESISTANCE"] = 0.096,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.28,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.2,
				["DODGE"] = 2.44,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.096,
				["FORTUNE"] = 0.4,
				["FROST RESISTANCE"] = 0.096,
				["HASTE"] = 3.59,
				["HEALING"] = 1,
				["HEALTH"] = 0.05,
				["HEALTH PER 5"] = 0.24,
				["HOLY CRIT"] = 3,
				["HOLY DAMAGE"] = 0.5,
				["INTELLECT"] = 1.21,
				["LIFESTEAL"] = 0.16,
				["MANA"] = 0.06,
				["MANA PER 5"] = 1.83,
				["MOUNT SPEED"] = 0.064,
				["MOVEMENT SPEED"] = 0.16,
				["NATURE RESISTANCE"] = 0.096,
				["RANGED DPS"] = 2,
				["SHADOW RESISTANCE"] = 0.096,
				["SPELL CRIT"] = 2.03,
				["SPELL DAMAGE"] = 0.5,
				["SPELL HIT"] = 0.3,
				["SPELL POWER"] = 0.5,
				["SPIRIT"] = 0.649,
				["STAMINA"] = 0.5,
				["STRENGTH"] = 0.02,
			},
			Holy = {
				["AGILITY"] = 0.052,
				["ALL RESISTANCES"] = 0.345,
				["ARCANE RESISTANCE"] = 0.083,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.241,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.2,
				["DODGE"] = 2.23,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.083,
				["FORTUNE"] = 0.345,
				["FROST RESISTANCE"] = 0.083,
				["HASTE"] = 3.42,
				["HEALING"] = 1,
				["HEALTH"] = 0.05,
				["HEALTH PER 5"] = 0.207,
				["HOLY CRIT"] = 3,
				["HOLY DAMAGE"] = 0.4,
				["INTELLECT"] = 1.07,
				["LIFESTEAL"] = 0.138,
				["MANA"] = 0.054,
				["MANA PER 5"] = 1.84,
				["MOUNT SPEED"] = 0.055,
				["MOVEMENT SPEED"] = 0.138,
				["NATURE RESISTANCE"] = 0.083,
				["RANGED DPS"] = 2,
				["SHADOW RESISTANCE"] = 0.083,
				["SPELL CRIT"] = 1.49,
				["SPELL DAMAGE"] = 0.4,
				["SPELL HIT"] = 0.3,
				["SPELL POWER"] = 0.4,
				["SPIRIT"] = 0.846,
				["STAMINA"] = 0.5,
				["STRENGTH"] = 0.02,
			},
			Shadow = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.5,
				["HEALING"] = 0.25,
				["HEALTH"] = 0.05,
				["HEALTH PER 5"] = 0.19,
				["HOLY DAMAGE"] = 0.2,
				["INTELLECT"] = 0.371,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.023,
				["MANA PER 5"] = 1.5,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW DAMAGE"] = 1,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 1.22,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.524,
				["SPELL HIT"] = 2.3,
				["SPELL PENETRATION"] = 0.066,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.6,
				["STAMINA"] = 0.5,
				["STRENGTH"] = 0.02,
			},
		},
		SHAMAN = {
			Elemental = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.5,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.4,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.91,
				["HEALING"] = 0.25,
				["HEALTH"] = 0.045,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.434,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.023,
				["MANA PER 5"] = 1.5,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE DAMAGE"] = 1,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 2.19,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 1.95,
				["SPELL PENETRATION"] = 0.213,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 0.45,
				["STRENGTH"] = 0.02,
			},
			Enhancement = {
				["AGILITY"] = 1.03,
				["ALL RESISTANCES"] = 0.45,
				["ARCANE RESISTANCE"] = 0.12,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.4,
				["AVOIDANCE"] = 0.35,
				["BLOCK"] = 1.43,
				["BLOCK VALUE"] = 0.15,
				["CRIT"] = 5.32,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.74,
				["DPS"] = 7.59,
				["EXTRA ATTACK"] = 3,
				["FIRE DAMAGE"] = 0.2,
				["FIRE RESISTANCE"] = 0.12,
				["FORTUNE"] = 1,
				["FROST DAMAGE"] = 0.24,
				["FROST RESISTANCE"] = 0.12,
				["HASTE"] = 3.46,
				["HEALING"] = 0.15,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.25,
				["HIT"] = 4.13,
				["INTELLECT"] = 0.6,
				["LIFESTEAL"] = 1.4,
				["MANA"] = 0.04,
				["MANA PER 5"] = 1.59,
				["MOUNT SPEED"] = 0.08,
				["MOVEMENT SPEED"] = 0.2,
				["NATURE DAMAGE"] = 0.729,
				["NATURE RESISTANCE"] = 0.12,
				["PARRY"] = 1.39,
				["RANGED DPS"] = 0.5,
				["SHADOW RESISTANCE"] = 0.12,
				["SPELL POWER"] = 0.771,
				["SPIRIT"] = 0.2,
				["STAMINA"] = 1,
				["STRENGTH"] = 2,
			},
			Restoration = {
				["AGILITY"] = 0.048,
				["ALL RESISTANCES"] = 0.357,
				["ARCANE RESISTANCE"] = 0.086,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.25,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.2,
				["DODGE"] = 2.06,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.086,
				["FORTUNE"] = 0.357,
				["FROST RESISTANCE"] = 0.086,
				["HASTE"] = 3.7,
				["HEALING"] = 1,
				["HEALTH"] = 0.05,
				["HEALTH PER 5"] = 0.214,
				["INTELLECT"] = 0.952,
				["LIFESTEAL"] = 0.143,
				["MANA"] = 0.048,
				["MANA PER 5"] = 1.69,
				["MOUNT SPEED"] = 0.057,
				["MOVEMENT SPEED"] = 0.143,
				["NATURE RESISTANCE"] = 0.086,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.086,
				["SPELL CRIT"] = 2.32,
				["SPELL DAMAGE"] = 0.4,
				["SPELL HIT"] = 0.3,
				["SPELL POWER"] = 0.4,
				["SPIRIT"] = 0.553,
				["STAMINA"] = 0.5,
				["STRENGTH"] = 0.15,
			},
		},
		MAGE = {
			Arcane = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.909,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.094,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.539,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.39,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.04,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.453,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.027,
				["MANA PER 5"] = 1.5,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 1.21,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 1.91,
				["SPELL PENETRATION"] = 0.072,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.419,
				["STAMINA"] = 0.4,
				["STRENGTH"] = 0.02,
			},
			Fire = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.194,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.955,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.315,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.78,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.04,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.43,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.023,
				["MANA PER 5"] = 1.5,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 1.69,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 2,
				["SPELL PENETRATION"] = 0.072,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.35,
				["STAMINA"] = 0.4,
				["STRENGTH"] = 0.02,
			},
			Frost = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.145,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.075,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST DAMAGE"] = 0.962,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.46,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.04,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.434,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.023,
				["MANA PER 5"] = 1.5,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 1.41,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 2.45,
				["SPELL PENETRATION"] = 0.06,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.35,
				["STAMINA"] = 0.4,
				["STRENGTH"] = 0.02,
			},
		},
		WARLOCK = {
			Affliction = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.409,
				["ARCANE RESISTANCE"] = 0.109,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.273,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.322,
				["FIRE RESISTANCE"] = 0.109,
				["FORTUNE"] = 0.773,
				["FROST RESISTANCE"] = 0.109,
				["HASTE"] = 1.71,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.085,
				["HEALTH PER 5"] = 0.182,
				["INTELLECT"] = 0.308,
				["LIFESTEAL"] = 0.227,
				["MANA"] = 0.015,
				["MANA PER 5"] = 1.05,
				["MOUNT SPEED"] = 0.073,
				["MOVEMENT SPEED"] = 0.182,
				["NATURE RESISTANCE"] = 0.109,
				["RANGED DPS"] = 3,
				["SHADOW DAMAGE"] = 0.932,
				["SHADOW RESISTANCE"] = 0.109,
				["SPELL CRIT"] = 0.738,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.545,
				["SPELL HIT"] = 2.42,
				["SPELL PENETRATION"] = 0.066,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.5,
				["STAMINA"] = 0.85,
				["STRENGTH"] = 0.02,
			},
			Demonology = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.673,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.58,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.07,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.349,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.015,
				["MANA PER 5"] = 1.05,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW DAMAGE"] = 0.846,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 1.3,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 2.42,
				["SPELL PENETRATION"] = 0.066,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.35,
				["STAMINA"] = 0.7,
				["STRENGTH"] = 0.02,
			},
			Destruction = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.409,
				["ARCANE RESISTANCE"] = 0.109,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.273,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE DAMAGE"] = 0.319,
				["FIRE RESISTANCE"] = 0.109,
				["FORTUNE"] = 0.773,
				["FROST RESISTANCE"] = 0.109,
				["HASTE"] = 2.29,
				["HEALING"] = 0.05,
				["HEALTH"] = 0.06,
				["HEALTH PER 5"] = 0.182,
				["INTELLECT"] = 0.334,
				["LIFESTEAL"] = 0.227,
				["MANA"] = 0.013,
				["MANA PER 5"] = 0.9,
				["MOUNT SPEED"] = 0.073,
				["MOVEMENT SPEED"] = 0.182,
				["NATURE RESISTANCE"] = 0.109,
				["RANGED DPS"] = 3,
				["SHADOW DAMAGE"] = 0.962,
				["SHADOW RESISTANCE"] = 0.109,
				["SPELL CRIT"] = 1.91,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.364,
				["SPELL HIT"] = 3.01,
				["SPELL PENETRATION"] = 0.066,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.3,
				["STAMINA"] = 0.6,
				["STRENGTH"] = 0.02,
			},
		},
		DRUID = {
			Balance = {
				["AGILITY"] = 0.044,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE DAMAGE"] = 0.697,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.286,
				["CASTING REGEN"] = 2,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.9,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.81,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 1.75,
				["HEALING"] = 0.25,
				["HEALTH"] = 0.045,
				["HEALTH PER 5"] = 0.19,
				["INTELLECT"] = 0.412,
				["LIFESTEAL"] = 0.238,
				["MANA"] = 0.023,
				["MANA PER 5"] = 1.5,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE DAMAGE"] = 0.531,
				["NATURE RESISTANCE"] = 0.114,
				["RANGED DPS"] = 3,
				["SHADOW RESISTANCE"] = 0.114,
				["SPELL CRIT"] = 1.38,
				["SPELL DAMAGE"] = 1,
				["SPELL DAMAGE UNDEAD"] = 0.381,
				["SPELL HIT"] = 2.44,
				["SPELL PENETRATION"] = 0.137,
				["SPELL POWER"] = 1,
				["SPIRIT"] = 0.35,
				["STAMINA"] = 0.45,
				["STRENGTH"] = 0.02,
			},
			FeralCat = {
				["AGILITY"] = 1.46,
				["ALL RESISTANCES"] = 0.429,
				["ARCANE RESISTANCE"] = 0.114,
				["ARMOR"] = 0.05,
				["ARMOR PENETRATION"] = 1.1,
				["ATTACK POWER"] = 1,
				["ATTACK POWER UNDEAD"] = 0.381,
				["AVOIDANCE"] = 0.333,
				["CRIT"] = 3.08,
				["DEFENSE"] = 0.4,
				["DODGE"] = 1.47,
				["EXTRA ATTACK"] = 2.86,
				["FERAL ATTACK POWER"] = 1,
				["FIRE RESISTANCE"] = 0.114,
				["FORTUNE"] = 0.952,
				["FROST RESISTANCE"] = 0.114,
				["HASTE"] = 2.21,
				["HEALING"] = 0.15,
				["HEALTH"] = 0.1,
				["HEALTH PER 5"] = 0.238,
				["HIT"] = 3.32,
				["INTELLECT"] = 0.25,
				["LIFESTEAL"] = 1.33,
				["MANA"] = 0.017,
				["MANA PER 5"] = 0.6,
				["MOUNT SPEED"] = 0.076,
				["MOVEMENT SPEED"] = 0.19,
				["NATURE RESISTANCE"] = 0.114,
				["SHADOW RESISTANCE"] = 0.114,
				["SPIRIT"] = 0.15,
				["STAMINA"] = 1,
				["STRENGTH"] = 2.37,
			},
			Restoration = {
				["AGILITY"] = 0.038,
				["ALL RESISTANCES"] = 0.345,
				["ARCANE RESISTANCE"] = 0.083,
				["ARMOR"] = 0.03,
				["AVOIDANCE"] = 0.241,
				["CASTING REGEN"] = 2.6,
				["DEFENSE"] = 0.2,
				["DODGE"] = 1.65,
				["DPS"] = 0.05,
				["FIRE RESISTANCE"] = 0.083,
				["FORTUNE"] = 0.345,
				["FROST RESISTANCE"] = 0.083,
				["HASTE"] = 2.17,
				["HEALING"] = 1,
				["HEALTH"] = 0.05,
				["HEALTH PER 5"] = 0.207,
				["INTELLECT"] = 0.763,
				["LIFESTEAL"] = 0.138,
				["MANA"] = 0.038,
				["MANA PER 5"] = 1.62,
				["MOUNT SPEED"] = 0.055,
				["MOVEMENT SPEED"] = 0.138,
				["NATURE RESISTANCE"] = 0.083,
				["RANGED DPS"] = 0.3,
				["SHADOW RESISTANCE"] = 0.083,
				["SPELL CRIT"] = 1.4,
				["SPELL DAMAGE"] = 0.4,
				["SPELL HIT"] = 0.3,
				["SPELL POWER"] = 0.4,
				["SPIRIT"] = 0.687,
				["STAMINA"] = 0.5,
				["STRENGTH"] = 0.02,
			},
		},
	},
	-- { upper-case text on a tooltip line, the stat it adds to }. In order:
	-- a line's first match for a stat wins, so the specific come first.
	patterns = {
		{ "DAMAGE AND HEALING DONE BY MAGICAL SPELLS", "SPELL POWER" },
		{ "DAMAGE AND HEALING DONE BY SPELLS", "SPELL POWER" },
		{ "DAMAGE DONE BY SHADOW SPELLS", "SHADOW DAMAGE" },
		{ "DAMAGE DONE BY FIRE SPELLS", "FIRE DAMAGE" },
		{ "DAMAGE DONE BY FROST SPELLS", "FROST DAMAGE" },
		{ "DAMAGE DONE BY NATURE SPELLS", "NATURE DAMAGE" },
		{ "DAMAGE DONE BY ARCANE SPELLS", "ARCANE DAMAGE" },
		{ "DAMAGE DONE BY HOLY SPELLS", "HOLY DAMAGE" },
		{ "NATURE SPELL DAMAGE", "NATURE DAMAGE" },
		{ "FIRE SPELL DAMAGE", "FIRE DAMAGE" },
		{ "FROST SPELL DAMAGE", "FROST DAMAGE" },
		{ "SHADOW SPELL DAMAGE", "SHADOW DAMAGE" },
		{ "ARCANE SPELL DAMAGE", "ARCANE DAMAGE" },
		{ "HOLY SPELL DAMAGE", "HOLY DAMAGE" },
		{ "NATURE DAMAGE", "NATURE DAMAGE" },
		{ "FIRE DAMAGE", "FIRE DAMAGE" },
		{ "FROST DAMAGE", "FROST DAMAGE" },
		{ "SHADOW DAMAGE", "SHADOW DAMAGE" },
		{ "ARCANE DAMAGE", "ARCANE DAMAGE" },
		{ "HOLY DAMAGE", "HOLY DAMAGE" },
		{ "INCREASES HEALING DONE", "HEALING" },
		{ "HEALING DONE BY SPELLS", "HEALING" },
		{ "DAMAGE DEALT IS RETURNED AS HEALING", "LIFESTEAL" },
		{ "RETURNED AS HEALING", "LIFESTEAL" },
		{ "VAMPIRISM", "LIFESTEAL" },
		{ "VAMPIRIC", "LIFESTEAL" },
		{ "DECREASES THE MAGICAL RESISTANCES OF YOUR SPELL TARGETS", "SPELL PENETRATION" },
		{ "DECREASES THE MAGICAL RESISTANCES", "SPELL PENETRATION" },
		{ "SPELL PENETRATION", "SPELL PENETRATION" },
		{ "YOUR ATTACKS IGNORE", "ARMOR PENETRATION" },
		{ "IGNORE .* OF THE TARGET'S ARMOR", "ARMOR PENETRATION" },
		{ "ARMOR PENETRATION", "ARMOR PENETRATION" },
		{ "INCREASES YOUR ATTACK AND CASTING SPEED", "HASTE" },
		{ "ATTACK AND CASTING SPEED", "HASTE" },
		{ "INCREASES YOUR ATTACK SPEED", "HASTE" },
		{ "INCREASES YOUR CASTING SPEED", "HASTE" },
		{ "CHANCE TO GRANT .* EXTRA ATTACK", "EXTRA ATTACK" },
		{ "CHANCE TO GET .* EXTRA ATTACK", "EXTRA ATTACK" },
		{ "CHANCE ON HIT TO GRANT .* EXTRA ATTACK", "EXTRA ATTACK" },
		{ "CHANCE OF GETTING AN EXTRA ATTACK", "EXTRA ATTACK" },
		{ "% CHANCE .* EXTRA ATTACK", "EXTRA ATTACK" },
		{ "GRANT .* EXTRA ATTACK", "EXTRA ATTACK" },
		{ "EXTRA ATTACK", "EXTRA ATTACK" },
		{ "CHANCE TO TRIGGER CHANCE BASED ITEM EFFECTS", "FORTUNE" },
		{ "TRIGGER EFFECTS FROM EQUIPPED ITEMS", "FORTUNE" },
		{ "TRIGGER CHANCE BASED ITEM EFFECTS", "FORTUNE" },
		{ "INCREASES YOUR CHANCE TO TRIGGER", "FORTUNE" },
		{ "DAMAGE YOU TAKE FROM AREA OF EFFECT", "AVOIDANCE" },
		{ "DAMAGE FROM AREA OF EFFECT", "AVOIDANCE" },
		{ "AREA OF EFFECT ATTACKS BY", "AVOIDANCE" },
		{ "AVOIDANCE", "AVOIDANCE" },
		{ "DAMAGE TAKEN FROM CRITICAL HITS AND DAMAGE OVER TIME", "RESILIENCE" },
		{ "DAMAGE TAKEN FROM CRITICAL HITS", "RESILIENCE" },
		{ "CRITICAL HITS AND DAMAGE OVER TIME", "RESILIENCE" },
		{ "DAMAGE FROM CRITICAL HITS", "RESILIENCE" },
		{ "RESILIENCE", "RESILIENCE" },
		{ "ATTACK POWER IN CAT, BEAR, DIRE BEAR, AND MOONKIN", "FERAL ATTACK POWER" },
		{ "ATTACK POWER IN CAT, BEAR", "FERAL ATTACK POWER" },
		{ "ATTACK POWER IN CAT", "FERAL ATTACK POWER" },
		{ "ATTACK POWER IN BEAR", "FERAL ATTACK POWER" },
		{ "FERAL ATTACK POWER", "FERAL ATTACK POWER" },
		{ "ATTACK POWER VERSUS UNDEAD", "ATTACK POWER UNDEAD" },
		{ "ATTACK POWER AGAINST UNDEAD", "ATTACK POWER UNDEAD" },
		{ "SPELL DAMAGE VERSUS UNDEAD", "SPELL DAMAGE UNDEAD" },
		{ "SPELL DAMAGE AGAINST UNDEAD", "SPELL DAMAGE UNDEAD" },
		{ "DAMAGE TO UNDEAD", "SPELL DAMAGE UNDEAD" },
		{ "CHANCE TO HIT WITH SPELLS", "SPELL HIT" },
		{ "HIT WITH SPELLS", "SPELL HIT" },
		{ "SPELL HIT", "SPELL HIT" },
		{ "IMPROVES YOUR CHANCE TO HIT", "HIT" },
		{ "INCREASES YOUR CHANCE TO HIT", "HIT" },
		{ "INCREASE TO HIT", "HIT" },
		{ "TO HIT BY", "HIT" },
		{ "CRITICAL STRIKE WITH SPELLS", "SPELL CRIT" },
		{ "CRITICAL STRIKE WITH HOLY", "HOLY CRIT" },
		{ "CRITICAL STRIKE WITH RANGED", "RANGED CRIT" },
		{ "RANGED CRITICAL", "RANGED CRIT" },
		{ "STRENGTH", "STRENGTH" },
		{ "AGILITY", "AGILITY" },
		{ "STAMINA", "STAMINA" },
		{ "INTELLECT", "INTELLECT" },
		{ "SPIRIT", "SPIRIT" },
		{ "RANGED ATTACK POWER", "RANGED ATTACK POWER" },
		{ "ATTACK POWER", "ATTACK POWER" },
		{ "SPELL DAMAGE", "SPELL DAMAGE" },
		{ "SPELL POWER", "SPELL POWER" },
		{ "SPELL CRIT", "SPELL CRIT" },
		{ "HEALTH PER 5", "HEALTH PER 5" },
		{ "MANA PER 5", "MANA PER 5" },
		{ "MANA REGENERATION TO CONTINUE WHILE CASTING", "CASTING REGEN" },
		{ "REGENERATION TO CONTINUE WHILE CASTING", "CASTING REGEN" },
		{ "CONTINUE WHILE CASTING", "CASTING REGEN" },
		{ "WHILE CASTING", "CASTING REGEN" },
		{ "INCREASES HEALTH", "HEALTH" },
		{ "HEALTH", "HEALTH" },
		{ "INCREASES MANA", "MANA" },
		{ "MANA", "MANA" },
		{ "DAMAGE PER SECOND", "DPS" },
		{ "DPS", "DPS" },
		{ "CRIT", "CRIT" },
		{ "DEFENSE", "DEFENSE" },
		{ "DODGE", "DODGE" },
		{ "PARRY", "PARRY" },
		{ "BLOCK VALUE", "BLOCK VALUE" },
		{ "BLOCK", "BLOCK" },
		{ "REINFORCED ARMOR", "ARMOR" },
		{ "ARMOR", "ARMOR" },
		{ "TO ALL RESISTANCES", "ALL RESISTANCES" },
		{ "ALL RESISTANCES", "ALL RESISTANCES" },
		{ "ALL RESISTANCE", "ALL RESISTANCES" },
		{ "FIRE RESISTANCE", "FIRE RESISTANCE" },
		{ "FROST RESISTANCE", "FROST RESISTANCE" },
		{ "SHADOW RESISTANCE", "SHADOW RESISTANCE" },
		{ "NATURE RESISTANCE", "NATURE RESISTANCE" },
		{ "ARCANE RESISTANCE", "ARCANE RESISTANCE" },
		{ "RANGED ATTACK SPEED", "RANGED HASTE" },
		{ "MOUNT SPEED", "MOUNT SPEED" },
		{ "RUN SPEED", "MOVEMENT SPEED" },
		{ "MOVEMENT SPEED", "MOVEMENT SPEED" },
	},
	-- Soft caps: past `cap`, each further point counts `after` of one.
	softcaps = {
		["ARMOR PENETRATION"] = { cap = 30, after = 0.45 },
		["BLOCK"] = { cap = 25, after = 0.4 },
		["CRIT"] = { cap = 25, after = 0.4 },
		["DEFENSE"] = { cap = 25, after = 0.35 },
		["DODGE"] = { cap = 25, after = 0.4 },
		["HASTE"] = { cap = 20, after = 0.45 },
		["HIT"] = { cap = 6, after = 0.35 },
		["HOLY CRIT"] = { cap = 25, after = 0.4 },
		["PARRY"] = { cap = 20, after = 0.4 },
		["RANGED CRIT"] = { cap = 25, after = 0.4 },
		["RANGED HASTE"] = { cap = 20, after = 0.45 },
		["SPELL CRIT"] = { cap = 25, after = 0.4 },
		["SPELL HIT"] = { cap = 10, after = 0.3 },
		["SPELL PENETRATION"] = { cap = 20, after = 0.4 },
	},
}
