-- Alchemy (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Alchemy route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Alchemy.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Alchemy (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Alchemy (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 370 crafts in total). For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Alchemy needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Alchemy (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Telina Shadehand (Alah'Thalas), Milla Fairancora (Darnassus), Ghak Healtouch (Loch Modan), Alchemist Mallory (Elwynn Forest).",
			faction = "Alliance",
			rank = { profession = "Alchemy", cap = 75 },
			npcs = { "Telina Shadehand", "Milla Fairancora", "Ghak Healtouch", "Alchemist Mallory" },
		},
		{
			type = "TRAIN",
			title = "Learn Alchemy (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Yox Rackgadg (Blackstone Island), Tammix Razzfire (Durotar), Whuut (Orgrimmar), Carolai Anise (Tirisfal Glades).",
			faction = "Horde",
			rank = { profession = "Alchemy", cap = 75 },
			npcs = { "Yox Rackgadg", "Tammix Razzfire", "Whuut", "Carolai Anise" },
		},
		{
			type = "USE",
			title = "Craft 5x Minor Healing Potion",
			note = "Takes you from 1 to 6.",
			skill = { profession = "Alchemy", from = 1, to = 6 },
			craft = { item = "Minor Healing Potion", count = 5 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Peacebloom", qty = 1 }, { item = "Silverleaf", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Elixir of Minor Defense",
			note = "Takes you from 6 to 7.",
			skill = { profession = "Alchemy", from = 6, to = 7 },
			craft = { item = "Elixir of Minor Defense", count = 1 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Silverleaf", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 33x Minor Healing Potion",
			note = "Takes you from 7 to 40.",
			skill = { profession = "Alchemy", from = 7, to = 40 },
			craft = { item = "Minor Healing Potion", count = 33 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Peacebloom", qty = 1 }, { item = "Silverleaf", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Minor Rejuvenation Potion",
			note = "Takes you from 40 to 50.",
			skill = { profession = "Alchemy", from = 40, to = 50 },
			craft = { item = "Minor Rejuvenation Potion", count = 14 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Peacebloom", qty = 1 }, { item = "Mageroyal", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Alchemy needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Alchemy (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Telina Shadehand (Alah'Thalas), Milla Fairancora (Darnassus), Ghak Healtouch (Loch Modan), Alchemist Mallory (Elwynn Forest).",
			faction = "Alliance",
			rank = { profession = "Alchemy", cap = 150 },
			npcs = { "Telina Shadehand", "Milla Fairancora", "Ghak Healtouch", "Alchemist Mallory" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Alchemy (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Yox Rackgadg (Blackstone Island), Tammix Razzfire (Durotar), Whuut (Orgrimmar), Carolai Anise (Tirisfal Glades).",
			faction = "Horde",
			rank = { profession = "Alchemy", cap = 150 },
			npcs = { "Yox Rackgadg", "Tammix Razzfire", "Whuut", "Carolai Anise" },
		},
		{
			type = "USE",
			title = "Craft 70x Minor Rejuvenation Potion",
			note = "Takes you from 50 to 100.",
			skill = { profession = "Alchemy", from = 50, to = 100 },
			craft = { item = "Minor Rejuvenation Potion", count = 70 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Peacebloom", qty = 1 }, { item = "Mageroyal", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 26x Holy Protection Potion",
			note = "Takes you from 100 to 125.",
			skill = { profession = "Alchemy", from = 100, to = 125 },
			craft = { item = "Holy Protection Potion", count = 26 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Bruiseweed", qty = 1 }, { item = "Swiftthistle", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Alchemy needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Alchemy (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Kylanna Windwhisper (Feralas), Ainethil (Darnassus), Sylvanna Forestmoon (Darnassus).",
			faction = "Alliance",
			rank = { profession = "Alchemy", cap = 225 },
			npcs = { "Kylanna Windwhisper", "Ainethil", "Sylvanna Forestmoon" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Alchemy (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Rogvar (Swamp of Sorrows), Doctor Herbert Halsey (Undercity), Yelmak (Orgrimmar).",
			faction = "Horde",
			rank = { profession = "Alchemy", cap = 225 },
			npcs = { "Rogvar", "Doctor Herbert Halsey", "Yelmak" },
		},
		{
			type = "USE",
			title = "Craft 8x Holy Protection Potion",
			note = "Takes you from 125 to 133.",
			skill = { profession = "Alchemy", from = 125, to = 133 },
			craft = { item = "Holy Protection Potion", count = 8 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Bruiseweed", qty = 1 }, { item = "Swiftthistle", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 22x Fire Oil",
			note = "Takes you from 133 to 154.",
			skill = { profession = "Alchemy", from = 133, to = 154 },
			craft = { item = "Fire Oil", count = 22 },
			reagents = { { item = "Empty Vial", qty = 1 }, { item = "Firefin Snapper", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 2x Elixir of Ogre's Strength",
			note = "Takes you from 154 to 156.",
			skill = { profession = "Alchemy", from = 154, to = 156 },
			craft = { item = "Elixir of Ogre's Strength", count = 2 },
			reagents = { { item = "Kingsblood", qty = 1 }, { item = "Leaded Vial", qty = 1 }, { item = "Earthroot", qty = 1 } },
			source = "Recipe: Elixir of Ogre's Strength",
		},
		{
			type = "USE",
			title = "Craft 25x Greater Healing Potion",
			note = "Takes you from 156 to 180.",
			skill = { profession = "Alchemy", from = 156, to = 180 },
			craft = { item = "Greater Healing Potion", count = 25 },
			reagents = { { item = "Liferoot", qty = 1 }, { item = "Kingsblood", qty = 1 }, { item = "Leaded Vial", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 22x Mighty Troll's Blood Potion",
			note = "Takes you from 180 to 200.",
			skill = { profession = "Alchemy", from = 180, to = 200 },
			craft = { item = "Mighty Troll's Blood Potion", count = 22 },
			reagents = { { item = "Liferoot", qty = 1 }, { item = "Leaded Vial", qty = 1 }, { item = "Bruiseweed", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Alchemy needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Alchemy (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Kylanna Windwhisper (Feralas).",
			faction = "Alliance",
			rank = { profession = "Alchemy", cap = 300 },
			npcs = { "Kylanna Windwhisper" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Alchemy (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Rogvar (Swamp of Sorrows).",
			faction = "Horde",
			rank = { profession = "Alchemy", cap = 300 },
			npcs = { "Rogvar" },
		},
		{
			type = "USE",
			title = "Craft 14x Mighty Troll's Blood Potion",
			note = "Takes you from 200 to 213.",
			skill = { profession = "Alchemy", from = 200, to = 213 },
			craft = { item = "Mighty Troll's Blood Potion", count = 14 },
			reagents = { { item = "Liferoot", qty = 1 }, { item = "Leaded Vial", qty = 1 }, { item = "Bruiseweed", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 34x Elixir of Detect Lesser Invisibility",
			note = "Takes you from 213 to 237.",
			skill = { profession = "Alchemy", from = 213, to = 237 },
			craft = { item = "Elixir of Detect Lesser Invisibility", count = 34 },
			reagents = { { item = "Leaded Vial", qty = 1 }, { item = "Khadgar's Whisker", qty = 1 }, { item = "Fadeleaf", qty = 1 } },
			source = "Recipe: Elixir of Detect Lesser Invisibility",
		},
		{
			type = "USE",
			title = "Craft 71x Elixir of Detect Undead",
			note = "Takes you from 237 to 277.",
			skill = { profession = "Alchemy", from = 237, to = 277 },
			craft = { item = "Elixir of Detect Undead", count = 71 },
			reagents = { { item = "Arthas' Tears", qty = 1 }, { item = "Crystal Vial", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Mageblood Potion",
			note = "Takes you from 277 to 291.",
			skill = { profession = "Alchemy", from = 277, to = 291 },
			craft = { item = "Mageblood Potion", count = 14 },
			reagents = { { item = "Dreamfoil", qty = 1 }, { item = "Plaguebloom", qty = 2 }, { item = "Crystal Vial", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Purification Potion",
			note = "Takes you from 291 to 300.",
			skill = { profession = "Alchemy", from = 291, to = 300 },
			craft = { item = "Purification Potion", count = 9 },
			reagents = { { item = "Icecap", qty = 2 }, { item = "Plaguebloom", qty = 2 }, { item = "Crystal Vial", qty = 1 } },
			source = "Recipe: Purification Potion",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Alchemy is maxed at 300.",
		},
	},
})
