-- Blacksmithing (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Blacksmithing route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Blacksmithing.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Blacksmithing (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Blacksmithing (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 579 crafts in total). For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Blacksmithing needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Blacksmithing (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Smith Argus (Elwynn Forest), Delfrum Flintbeard (Darkshore), Groum Stonebeard (Ironforge), Dane Lindgren (Stormwind City).",
			faction = "Alliance",
			rank = { profession = "Blacksmithing", cap = 75 },
			npcs = { "Smith Argus", "Delfrum Flintbeard", "Groum Stonebeard", "Dane Lindgren" },
		},
		{
			type = "TRAIN",
			title = "Learn Blacksmithing (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Thrag Stonehoof (Thunder Bluff), Ug'thok (Orgrimmar), Basil Frye (Undercity), Dwukk (Durotar).",
			faction = "Horde",
			rank = { profession = "Blacksmithing", cap = 75 },
			npcs = { "Thrag Stonehoof", "Ug'thok", "Basil Frye", "Dwukk" },
		},
		{
			type = "USE",
			title = "Craft 50x Rough Sharpening Stone",
			note = "Takes you from 1 to 39.",
			skill = { profession = "Blacksmithing", from = 1, to = 39 },
			craft = { item = "Rough Sharpening Stone", count = 50 },
			reagents = { { item = "Rough Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 34x Rough Grinding Stone",
			note = "Takes you from 39 to 50. Keep them for Silver Skeleton Key.",
			skill = { profession = "Blacksmithing", from = 39, to = 50 },
			craft = { item = "Rough Grinding Stone", count = 34 },
			reagents = { { item = "Rough Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Blacksmithing needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Blacksmithing (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Clarise Gnarltree (Duskwood), Rotgath Stonebeard (Ironforge), Therum Deepforge (Stormwind City), Smith Martin (Northwind).",
			faction = "Alliance",
			rank = { profession = "Blacksmithing", cap = 150 },
			npcs = { "Clarise Gnarltree", "Rotgath Stonebeard", "Therum Deepforge", "Smith Martin" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Blacksmithing (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Snarl (Orgrimmar), Traugh (The Barrens), Karn Stonehoof (Thunder Bluff), Thrag Stonehoof (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Blacksmithing", cap = 150 },
			npcs = { "Snarl", "Traugh", "Karn Stonehoof", "Thrag Stonehoof" },
		},
		{
			type = "USE",
			title = "Craft 104x Rough Grinding Stone",
			note = "Takes you from 50 to 84. Keep them for Silver Skeleton Key.",
			skill = { profession = "Blacksmithing", from = 50, to = 84 },
			craft = { item = "Rough Grinding Stone", count = 104 },
			reagents = { { item = "Rough Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Copper Chain Belt",
			note = "Takes you from 84 to 93.",
			skill = { profession = "Blacksmithing", from = 84, to = 93 },
			craft = { item = "Copper Chain Belt", count = 14 },
			reagents = { { item = "Copper Bar", qty = 6 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Gemmed Copper Gauntlets",
			note = "Takes you from 93 to 100.",
			skill = { profession = "Blacksmithing", from = 93, to = 100 },
			craft = { item = "Gemmed Copper Gauntlets", count = 7 },
			reagents = { { item = "Copper Bar", qty = 8 }, { item = "Tigerseye", qty = 1 }, { item = "Malachite", qty = 1 } },
			source = "Plans: Gemmed Copper Gauntlets",
		},
		{
			type = "USE",
			title = "Craft 52x Silver Skeleton Key",
			note = "Takes you from 100 to 119.",
			skill = { profession = "Blacksmithing", from = 100, to = 119 },
			craft = { item = "Silver Skeleton Key", count = 52 },
			reagents = { { item = "Silver Bar", qty = 1 }, { item = "Rough Grinding Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Rough Bronze Bracers",
			note = "Takes you from 119 to 125.",
			skill = { profession = "Blacksmithing", from = 119, to = 125 },
			craft = { item = "Rough Bronze Bracers", count = 6 },
			reagents = { { item = "Bronze Bar", qty = 4 } },
			source = "Plans: Rough Bronze Bracers",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Blacksmithing needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Blacksmithing (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Bengus Deepforge (Ironforge).",
			faction = "Alliance",
			rank = { profession = "Blacksmithing", cap = 225 },
			npcs = { "Bengus Deepforge" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Blacksmithing (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Brikk Keencraft (Stranglethorn Vale), Ulf Stonetotem (Moonwhisper Coast), Saru Steelfury (Orgrimmar), James Van Brunt (Undercity).",
			faction = "Horde",
			rank = { profession = "Blacksmithing", cap = 225 },
			npcs = { "Brikk Keencraft", "Ulf Stonetotem", "Saru Steelfury", "James Van Brunt" },
		},
		{
			type = "USE",
			title = "Craft 14x Heavy Sharpening Stone",
			note = "Takes you from 125 to 134.",
			skill = { profession = "Blacksmithing", from = 125, to = 134 },
			craft = { item = "Heavy Sharpening Stone", count = 14 },
			reagents = { { item = "Heavy Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 17x Rough Bronze Bracers",
			note = "Takes you from 134 to 150.",
			skill = { profession = "Blacksmithing", from = 134, to = 150 },
			craft = { item = "Rough Bronze Bracers", count = 17 },
			reagents = { { item = "Bronze Bar", qty = 4 } },
			source = "Plans: Rough Bronze Bracers",
		},
		{
			type = "USE",
			title = "Craft 8x Iron Buckle",
			note = "Takes you from 150 to 154.",
			skill = { profession = "Blacksmithing", from = 150, to = 154 },
			craft = { item = "Iron Buckle", count = 8 },
			reagents = { { item = "Iron Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Golden Skeleton Key",
			note = "Takes you from 154 to 158.",
			skill = { profession = "Blacksmithing", from = 154, to = 158 },
			craft = { item = "Golden Skeleton Key", count = 6 },
			reagents = { { item = "Gold Bar", qty = 1 }, { item = "Heavy Grinding Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 16x Rough Bronze Bracers",
			note = "Takes you from 158 to 165.",
			skill = { profession = "Blacksmithing", from = 158, to = 165 },
			craft = { item = "Rough Bronze Bracers", count = 16 },
			reagents = { { item = "Bronze Bar", qty = 4 } },
			source = "Plans: Rough Bronze Bracers",
		},
		{
			type = "USE",
			title = "Craft 38x Green Iron Bracers",
			note = "Takes you from 165 to 200.",
			skill = { profession = "Blacksmithing", from = 165, to = 200 },
			craft = { item = "Green Iron Bracers", count = 38 },
			reagents = { { item = "Iron Bar", qty = 6 }, { item = "Green Dye", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Blacksmithing needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Blacksmithing (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Grumnus Steelshaper (Ironforge), Ironus Coldsteel (Ironforge), Borgus Steelhand (Stormwind City), Brikk Keencraft (Stranglethorn Vale).",
			faction = "Alliance",
			rank = { profession = "Blacksmithing", cap = 300 },
			npcs = { "Grumnus Steelshaper", "Ironus Coldsteel", "Borgus Steelhand", "Brikk Keencraft" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Blacksmithing (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Okothos Ironrager (Orgrimmar), Shayis Steelfury (Orgrimmar), Borgosh Corebender (Orgrimmar), Kelgruk Bloodaxe (Orgrimmar).",
			faction = "Horde",
			rank = { profession = "Blacksmithing", cap = 300 },
			npcs = { "Okothos Ironrager", "Shayis Steelfury", "Borgosh Corebender", "Kelgruk Bloodaxe" },
		},
		{
			type = "USE",
			title = "Craft 97x Solid Grinding Stone",
			note = "Takes you from 200 to 210. Keep them for Truesilver Skeleton Key and Mithril Spurs.",
			skill = { profession = "Blacksmithing", from = 200, to = 210 },
			craft = { item = "Solid Grinding Stone", count = 97 },
			reagents = { { item = "Solid Stone", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Truesilver Skeleton Key",
			note = "Takes you from 210 to 214.",
			skill = { profession = "Blacksmithing", from = 210, to = 214 },
			craft = { item = "Truesilver Skeleton Key", count = 10 },
			reagents = { { item = "Truesilver Bar", qty = 1 }, { item = "Solid Grinding Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 23x Heavy Mithril Gauntlet",
			note = "Takes you from 214 to 234.",
			skill = { profession = "Blacksmithing", from = 214, to = 234 },
			craft = { item = "Heavy Mithril Gauntlet", count = 23 },
			reagents = { { item = "Mithril Bar", qty = 6 }, { item = "Mageweave Cloth", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Mithril Scale Gloves",
			note = "Takes you from 234 to 235.",
			skill = { profession = "Blacksmithing", from = 234, to = 235 },
			craft = { item = "Mithril Scale Gloves", count = 1 },
			reagents = { { item = "Mithril Bar", qty = 8 }, { item = "Heavy Leather", qty = 6 }, { item = "Mageweave Cloth", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 15x Mithril Spurs",
			note = "Takes you from 235 to 250.",
			skill = { profession = "Blacksmithing", from = 235, to = 250 },
			craft = { item = "Mithril Spurs", count = 15 },
			reagents = { { item = "Mithril Bar", qty = 4 }, { item = "Solid Grinding Stone", qty = 3 } },
			source = "Plans: Mithril Spurs",
		},
		{
			type = "USE",
			title = "Craft 13x Dense Sharpening Stone",
			note = "Takes you from 250 to 259.",
			skill = { profession = "Blacksmithing", from = 250, to = 259 },
			craft = { item = "Dense Sharpening Stone", count = 13 },
			reagents = { { item = "Dense Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Mithril Spurs",
			note = "Takes you from 259 to 267.",
			skill = { profession = "Blacksmithing", from = 259, to = 267 },
			craft = { item = "Mithril Spurs", count = 14 },
			reagents = { { item = "Mithril Bar", qty = 4 }, { item = "Solid Grinding Stone", qty = 3 } },
			source = "Plans: Mithril Spurs",
		},
		{
			type = "USE",
			title = "Craft 14x Ornate Mithril Helm",
			note = "Takes you from 267 to 276.",
			skill = { profession = "Blacksmithing", from = 267, to = 276 },
			craft = { item = "Ornate Mithril Helm", count = 14 },
			reagents = { { item = "Mithril Bar", qty = 16 } },
		},
		{
			type = "USE",
			title = "Craft 2x Thorium Bracers",
			note = "Takes you from 276 to 277.",
			skill = { profession = "Blacksmithing", from = 276, to = 277 },
			craft = { item = "Thorium Bracers", count = 2 },
			reagents = { { item = "Thorium Bar", qty = 12 }, { item = "Blue Power Crystal", qty = 4 } },
			source = "Plans: Thorium Bracers",
		},
		{
			type = "USE",
			title = "Craft 19x Imperial Plate Bracers",
			note = "Takes you from 277 to 295.",
			skill = { profession = "Blacksmithing", from = 277, to = 295 },
			craft = { item = "Imperial Plate Bracers", count = 19 },
			reagents = { { item = "Thorium Bar", qty = 20 }, { item = "Star Ruby", qty = 1 } },
			source = "Quest reward",
		},
		{
			type = "USE",
			title = "Craft 1x Thorium Boots",
			note = "Takes you from 295 to 296.",
			skill = { profession = "Blacksmithing", from = 295, to = 296 },
			craft = { item = "Thorium Boots", count = 1 },
			reagents = { { item = "Thorium Bar", qty = 20 }, { item = "Rugged Leather", qty = 8 }, { item = "Green Power Crystal", qty = 4 } },
			source = "Plans: Thorium Boots",
		},
		{
			type = "USE",
			title = "Craft 4x Thorium Helm",
			note = "Takes you from 296 to 300.",
			skill = { profession = "Blacksmithing", from = 296, to = 300 },
			craft = { item = "Thorium Helm", count = 4 },
			reagents = { { item = "Thorium Bar", qty = 24 }, { item = "Star Ruby", qty = 1 }, { item = "Yellow Power Crystal", qty = 4 } },
			source = "Plans: Thorium Helm",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Blacksmithing is maxed at 300.",
		},
	},
})
