-- Cooking (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Cooking (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Cooking (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 185 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Learn Cooking (Apprentice)",
			note = "Costs 5 copper. Trainers: Cook Ghilm (Dun Morogh), Gremlock Pilsnor (Dun Morogh), Tomas (Elwynn Forest), Verrus Trueshine (Alah'Thalas).",
			faction = "Alliance",
			rank = { profession = "Cooking", cap = 75 },
			npcs = { "Cook Ghilm", "Gremlock Pilsnor", "Tomas", "Verrus Trueshine" },
		},
		{
			type = "TRAIN",
			title = "Learn Cooking (Apprentice)",
			note = "Costs 5 copper. Trainers: Cook Torka (Durotar), Pyall Silentstride (Mulgore), Duhng (The Barrens), Shazzlan (Blackstone Island).",
			faction = "Horde",
			rank = { profession = "Cooking", cap = 75 },
			npcs = { "Cook Torka", "Pyall Silentstride", "Duhng", "Shazzlan" },
		},
		{
			type = "USE",
			title = "Craft 40x Brilliant Smallfish",
			note = "Takes you from 1 to 58.",
			skill = { profession = "Cooking", from = 1, to = 58 },
			craft = { item = "Brilliant Smallfish", count = 40 },
			reagents = { { item = "Raw Brilliant Smallfish", qty = 1 } },
			source = "Recipe: Brilliant Smallfish",
			alternatives = { "Slitherskin Mackerel", "Roasted Boar Meat", "Charred Wolf Meat", "Herb Baked Egg", "Crispy Bat Wing", "Gingerbread Cookie" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Cooking (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Verrus Trueshine (Alah'Thalas), Cook Ghilm (Dun Morogh), Gremlock Pilsnor (Dun Morogh), Tomas (Elwynn Forest).",
			faction = "Alliance",
			rank = { profession = "Cooking", cap = 150 },
			npcs = { "Verrus Trueshine", "Cook Ghilm", "Gremlock Pilsnor", "Tomas" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Cooking (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Cook Torka (Durotar), Pyall Silentstride (Mulgore), Duhng (The Barrens), Shazzlan (Blackstone Island).",
			faction = "Horde",
			rank = { profession = "Cooking", cap = 150 },
			npcs = { "Cook Torka", "Pyall Silentstride", "Duhng", "Shazzlan" },
		},
		{
			type = "USE",
			title = "Craft 32x Longjaw Mud Snapper",
			note = "Takes you from 58 to 105.",
			skill = { profession = "Cooking", from = 58, to = 105 },
			craft = { item = "Longjaw Mud Snapper", count = 32 },
			reagents = { { item = "Raw Longjaw Mud Snapper", qty = 1 } },
			source = "Recipe: Longjaw Mud Snapper",
			alternatives = { "Brilliant Smallfish", "Slitherskin Mackerel", "Rainbow Fin Albacore", "Loch Frenzy Delight", "Kaldorei Spider Kabob", "Roasted Boar Meat" },
		},
		{
			type = "USE",
			title = "Craft 25x Dig Rat Stew",
			note = "Takes you from 105 to 145.",
			skill = { profession = "Cooking", from = 105, to = 145 },
			craft = { item = "Dig Rat Stew", count = 25 },
			reagents = { { item = "Dig Rat", qty = 1 } },
			source = "Recipe: Dig Rat Stew",
			alternatives = { "Longjaw Mud Snapper", "Bristle Whisker Catfish", "Rainbow Fin Albacore", "Loch Frenzy Delight", "Savory Deviate Delight", "Coyote Steak" },
		},
		{
			type = "BUY",
			title = "Buy Expert Cookbook",
			note = "Shandrina (Ashenvale, Silverwind Refuge) sells it for 1 gold. Read it to raise your Cooking cap to 225; it needs skill 125.",
			faction = "Alliance",
			rank = { profession = "Cooking", cap = 225 },
			npcs = { "Shandrina" },
		},
		{
			type = "BUY",
			title = "Buy Expert Cookbook",
			note = "Wulan (Desolace, Shadowprey Village) sells it for 1 gold. Read it to raise your Cooking cap to 225; it needs skill 125.",
			faction = "Horde",
			rank = { profession = "Cooking", cap = 225 },
			npcs = { "Wulan" },
		},
		{
			type = "USE",
			title = "Craft 13x Bristle Whisker Catfish",
			note = "Takes you from 145 to 155.",
			skill = { profession = "Cooking", from = 145, to = 155 },
			craft = { item = "Bristle Whisker Catfish", count = 13 },
			reagents = { { item = "Raw Bristle Whisker Catfish", qty = 1 } },
			source = "Recipe: Bristle Whisker Catfish",
			alternatives = { "Dig Rat Stew", "Savory Deviate Delight", "Cooked Crab Claw", "Dry Pork Ribs", "Crocolisk Steak", "Clam Chowder" },
		},
		{
			type = "USE",
			title = "Craft 10x Lean Wolf Steak",
			note = "Takes you from 155 to 175.",
			skill = { profession = "Cooking", from = 155, to = 175 },
			craft = { item = "Lean Wolf Steak", count = 10 },
			reagents = { { item = "Lean Wolf Flank", qty = 1 }, { item = "Mild Spices", qty = 1 } },
			source = "Recipe: Lean Wolf Steak",
			alternatives = { "Dig Rat Stew", "Bristle Whisker Catfish", "Clam Chowder", "Goblin Deviled Clams", "Gooey Spider Cake", "Lean Venison" },
		},
		{
			type = "USE",
			title = "Craft 15x Rockscale Cod",
			note = "Takes you from 175 to 210.",
			skill = { profession = "Cooking", from = 175, to = 210 },
			craft = { item = "Rockscale Cod", count = 15 },
			reagents = { { item = "Raw Rockscale Cod", qty = 1 } },
			source = "Recipe: Rockscale Cod",
			alternatives = { "Mithril Head Trout", "Lean Wolf Steak", "Goblin Deviled Clams", "Gooey Spider Cake", "Lean Venison", "Crocolisk Gumbo" },
		},
		{
			type = "USE",
			title = "Craft 4x Mithril Head Trout",
			note = "Takes you from 210 to 225.",
			skill = { profession = "Cooking", from = 210, to = 225 },
			craft = { item = "Mithril Head Trout", count = 4 },
			reagents = { { item = "Raw Mithril Head Trout", qty = 1 } },
			source = "Recipe: Mithril Head Trout",
			alternatives = { "Rockscale Cod", "Giant Clam Scorcho", "Jungle Stew", "Roast Raptor", "Hot Wolf Ribs", "Carrion Surprise" },
		},
		{
			type = "GRIND",
			title = "Reach level 40",
			note = "The Artisan Cooking quest needs character level 40. This step clears itself when you get there.",
			level = 40,
		},
		{
			type = "NOTE",
			title = "Start the Artisan Cooking quest",
			note = "Daryl Riknussun in Ironforge, near the gryphon platform at the forge, starts it. Needs level 40 and skill 225. You can skip this and go straight to Dirge Quikcleave.",
			faction = "Alliance",
			optional = true,
			npcs = { "Daryl Riknussun" },
		},
		{
			type = "NOTE",
			title = "Start the Artisan Cooking quest",
			note = "Zamja in Orgrimmar, the third house on the right near the Valley of Strength, in the Drag, starts it. Needs level 40 and skill 225. You can skip this and go straight to Dirge Quikcleave.",
			faction = "Horde",
			optional = true,
			npcs = { "Zamja" },
		},
		{
			type = "NOTE",
			title = "Gather for Dirge Quikcleave",
			note = "Giant Eggs drop from level 40+ rocs in Tanaris (plenty near Gadgetzan) or owlbeasts in The Hinterlands. Zesty Clam Meat comes out of Big-mouth Clams, dropped by Muckshells and Threshers in Dustwallow Marsh, Naga Explorers in Stranglethorn Vale and Hatecrests in Feralas. Alterac Swiss is 40 silver per stack of 5 from Ben Trias in Stormwind City (Alliance) or Innkeeper Sikewa in Desolace, Shadowprey Village (Horde).",
			reagents = { { item = "Giant Egg", qty = 12 }, { item = "Zesty Clam Meat", qty = 10 }, { item = "Alterac Swiss", qty = 20 } },
		},
		{
			type = "NOTE",
			title = "Hand in to Dirge Quikcleave",
			note = "Tanaris, Gadgetzan. Tanaris, Gadgetzan. The big bonfire around the corner behind the inn does for cooking.",
			rank = { profession = "Cooking", cap = 300 },
			npcs = { "Dirge Quikcleave" },
		},
		{
			type = "USE",
			title = "Craft 1x Mithril Head Trout",
			note = "Takes you from 225 to 230.",
			skill = { profession = "Cooking", from = 225, to = 230 },
			craft = { item = "Mithril Head Trout", count = 1 },
			reagents = { { item = "Raw Mithril Head Trout", qty = 1 } },
			source = "Recipe: Mithril Head Trout",
			alternatives = { "Rockscale Cod", "Giant Clam Scorcho", "Jungle Stew", "Roast Raptor", "Hot Wolf Ribs", "Carrion Surprise" },
		},
		{
			type = "USE",
			title = "Craft 35x Spotted Yellowtail",
			note = "Takes you from 230 to 280.",
			skill = { profession = "Cooking", from = 230, to = 280 },
			craft = { item = "Spotted Yellowtail", count = 35 },
			reagents = { { item = "Raw Spotted Yellowtail", qty = 1 } },
			source = "Recipe: Spotted Yellowtail",
			alternatives = { "Filet of Redgill", "Mithril Head Trout", "Cooked Glossy Mightfish", "Giant Clam Scorcho", "Jungle Stew", "Roast Raptor" },
		},
		{
			type = "USE",
			title = "Craft 10x Poached Sunscale Salmon",
			note = "Takes you from 280 to 300.",
			skill = { profession = "Cooking", from = 280, to = 300 },
			craft = { item = "Poached Sunscale Salmon", count = 10 },
			reagents = { { item = "Raw Sunscale Salmon", qty = 1 } },
			source = "Recipe: Poached Sunscale Salmon",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Cooking is maxed at 300.",
		},
	},
})
