-- Enchanting (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Enchanting route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Enchanting.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Enchanting (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Enchanting (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 379 crafts in total). For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Enchanting needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Enchanting (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Magister Sylvus Silkspinner (Thalassian Highlands), Betty Quin (Stormwind City), Thonys Pillarstone (Ironforge), Lalina Summermoon (Darnassus).",
			faction = "Alliance",
			rank = { profession = "Enchanting", cap = 75 },
			npcs = { "Magister Sylvus Silkspinner", "Betty Quin", "Thonys Pillarstone", "Lalina Summermoon" },
		},
		{
			type = "TRAIN",
			title = "Learn Enchanting (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Mot Dawnstrider (Thunder Bluff), Malcomb Wynn (Undercity), Jhag (Orgrimmar), Vance Undergloom (Tirisfal Glades).",
			faction = "Horde",
			rank = { profession = "Enchanting", cap = 75 },
			npcs = { "Mot Dawnstrider", "Malcomb Wynn", "Jhag", "Vance Undergloom" },
		},
		{
			type = "USE",
			title = "Craft 1x Runed Copper Rod",
			note = "Takes you from 1 to 2.",
			skill = { profession = "Enchanting", from = 1, to = 2 },
			craft = { item = "Runed Copper Rod", count = 1 },
			reagents = { { item = "Copper Rod", qty = 1 }, { item = "Strange Dust", qty = 1 }, { item = "Lesser Magic Essence", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 52x Enchant Bracer - Minor Health",
			note = "Takes you from 2 to 50.",
			skill = { profession = "Enchanting", from = 2, to = 50 },
			craft = { item = "Enchant Bracer - Minor Health", count = 52 },
			reagents = { { item = "Strange Dust", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Enchanting needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Enchanting (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Magister Sylvus Silkspinner (Thalassian Highlands), Gimble Thistlefuzz (Ironforge), Lucan Cordell (Stormwind City), Taladan (Darnassus).",
			faction = "Alliance",
			rank = { profession = "Enchanting", cap = 150 },
			npcs = { "Magister Sylvus Silkspinner", "Gimble Thistlefuzz", "Lucan Cordell", "Taladan" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Enchanting (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Godan (Orgrimmar), Lavinia Crowe (Undercity), Teg Dawnstrider (Thunder Bluff), Mot Dawnstrider (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Enchanting", cap = 150 },
			npcs = { "Godan", "Lavinia Crowe", "Teg Dawnstrider", "Mot Dawnstrider" },
		},
		{
			type = "USE",
			title = "Craft 44x Enchant Bracer - Minor Health",
			note = "Takes you from 50 to 90.",
			skill = { profession = "Enchanting", from = 50, to = 90 },
			craft = { item = "Enchant Bracer - Minor Health", count = 44 },
			reagents = { { item = "Strange Dust", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 18x Enchant Chest - Minor Mana",
			note = "Takes you from 90 to 100.",
			skill = { profession = "Enchanting", from = 90, to = 100 },
			craft = { item = "Enchant Chest - Minor Mana", count = 18 },
			reagents = { { item = "Lesser Magic Essence", qty = 1 } },
			source = "Formula: Enchant Chest - Minor Mana",
		},
		{
			type = "USE",
			title = "Craft 1x Runed Silver Rod",
			note = "Takes you from 100 to 101.",
			skill = { profession = "Enchanting", from = 100, to = 101 },
			craft = { item = "Runed Silver Rod", count = 1 },
			reagents = { { item = "Silver Rod", qty = 1 }, { item = "Strange Dust", qty = 6 }, { item = "Greater Magic Essence", qty = 3 }, { item = "Shadowgem", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Enchant Chest - Minor Mana",
			note = "Takes you from 101 to 103.",
			skill = { profession = "Enchanting", from = 101, to = 103 },
			craft = { item = "Enchant Chest - Minor Mana", count = 4 },
			reagents = { { item = "Lesser Magic Essence", qty = 1 } },
			source = "Formula: Enchant Chest - Minor Mana",
		},
		{
			type = "USE",
			title = "Craft 13x Enchant Bracer - Minor Spirit",
			note = "Takes you from 103 to 114.",
			skill = { profession = "Enchanting", from = 103, to = 114 },
			craft = { item = "Enchant Bracer - Minor Spirit", count = 13 },
			reagents = { { item = "Lesser Magic Essence", qty = 2 } },
			source = "Formula: Enchant Bracer - Minor Spirit",
		},
		{
			type = "USE",
			title = "Craft 10x Greater Magic Wand",
			note = "Takes you from 114 to 122.",
			skill = { profession = "Enchanting", from = 114, to = 122 },
			craft = { item = "Greater Magic Wand", count = 10 },
			reagents = { { item = "Simple Wood", qty = 1 }, { item = "Greater Magic Essence", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 3x Enchant 2H Weapon - Minor Impact",
			note = "Takes you from 122 to 125.",
			skill = { profession = "Enchanting", from = 122, to = 125 },
			craft = { item = "Enchant 2H Weapon - Minor Impact", count = 3 },
			reagents = { { item = "Strange Dust", qty = 4 }, { item = "Small Glimmering Shard", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Enchanting needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Enchanting (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Annora (Uldaman), Kitta Firewind (Elwynn Forest), Magister Sylvus Silkspinner (Thalassian Highlands), Gimble Thistlefuzz (Ironforge).",
			faction = "Alliance",
			rank = { profession = "Enchanting", cap = 225 },
			npcs = { "Annora", "Kitta Firewind", "Magister Sylvus Silkspinner", "Gimble Thistlefuzz" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Enchanting (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Annora (Uldaman), Hgarth (Stonetalon Mountains), Godan (Orgrimmar), Lavinia Crowe (Undercity).",
			faction = "Horde",
			rank = { profession = "Enchanting", cap = 225 },
			npcs = { "Annora", "Hgarth", "Godan", "Lavinia Crowe" },
		},
		{
			type = "USE",
			title = "Craft 4x Enchant 2H Weapon - Minor Impact",
			note = "Takes you from 125 to 129.",
			skill = { profession = "Enchanting", from = 125, to = 129 },
			craft = { item = "Enchant 2H Weapon - Minor Impact", count = 4 },
			reagents = { { item = "Strange Dust", qty = 4 }, { item = "Small Glimmering Shard", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Enchant Cloak - Minor Agility",
			note = "Takes you from 129 to 130.",
			skill = { profession = "Enchanting", from = 129, to = 130 },
			craft = { item = "Enchant Cloak - Minor Agility", count = 1 },
			reagents = { { item = "Lesser Astral Essence", qty = 1 } },
			source = "Formula: Enchant Cloak - Minor Agility",
		},
		{
			type = "USE",
			title = "Craft 21x Enchant Bracer - Lesser Stamina",
			note = "Takes you from 130 to 150.",
			skill = { profession = "Enchanting", from = 130, to = 150 },
			craft = { item = "Enchant Bracer - Lesser Stamina", count = 21 },
			reagents = { { item = "Soul Dust", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Runed Golden Rod",
			note = "Takes you from 150 to 151.",
			skill = { profession = "Enchanting", from = 150, to = 151 },
			craft = { item = "Runed Golden Rod", count = 1 },
			reagents = { { item = "Golden Rod", qty = 1 }, { item = "Iridescent Pearl", qty = 1 }, { item = "Greater Astral Essence", qty = 2 }, { item = "Soul Dust", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 13x Enchant Bracer - Lesser Stamina",
			note = "Takes you from 151 to 163.",
			skill = { profession = "Enchanting", from = 151, to = 163 },
			craft = { item = "Enchant Bracer - Lesser Stamina", count = 13 },
			reagents = { { item = "Soul Dust", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 18x Enchant Bracer - Lesser Strength",
			note = "Takes you from 163 to 178.",
			skill = { profession = "Enchanting", from = 163, to = 178 },
			craft = { item = "Enchant Bracer - Lesser Strength", count = 18 },
			reagents = { { item = "Soul Dust", qty = 2 } },
			source = "Formula: Enchant Bracer - Lesser Strength",
		},
		{
			type = "USE",
			title = "Craft 2x Enchant Bracer - Spirit",
			note = "Takes you from 178 to 180.",
			skill = { profession = "Enchanting", from = 178, to = 180 },
			craft = { item = "Enchant Bracer - Spirit", count = 2 },
			reagents = { { item = "Lesser Mystic Essence", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 30x Enchant Bracer - Strength",
			note = "Takes you from 180 to 200.",
			skill = { profession = "Enchanting", from = 180, to = 200 },
			craft = { item = "Enchant Bracer - Strength", count = 30 },
			reagents = { { item = "Vision Dust", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Enchanting needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Enchanting (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Annora (Uldaman), Kitta Firewind (Elwynn Forest).",
			faction = "Alliance",
			rank = { profession = "Enchanting", cap = 300 },
			npcs = { "Annora", "Kitta Firewind" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Enchanting (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Annora (Uldaman), Hgarth (Stonetalon Mountains).",
			faction = "Horde",
			rank = { profession = "Enchanting", cap = 300 },
			npcs = { "Annora", "Hgarth" },
		},
		{
			type = "USE",
			title = "Craft 1x Runed Truesilver Rod",
			note = "Takes you from 200 to 201.",
			skill = { profession = "Enchanting", from = 200, to = 201 },
			craft = { item = "Runed Truesilver Rod", count = 1 },
			reagents = { { item = "Truesilver Rod", qty = 1 }, { item = "Black Pearl", qty = 1 }, { item = "Greater Mystic Essence", qty = 2 }, { item = "Vision Dust", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 44x Enchant Bracer - Strength",
			note = "Takes you from 201 to 230.",
			skill = { profession = "Enchanting", from = 201, to = 230 },
			craft = { item = "Enchant Bracer - Strength", count = 44 },
			reagents = { { item = "Vision Dust", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 34x Enchant Cloak - Greater Defense",
			note = "Takes you from 230 to 250.",
			skill = { profession = "Enchanting", from = 230, to = 250 },
			craft = { item = "Enchant Cloak - Greater Defense", count = 34 },
			reagents = { { item = "Vision Dust", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Enchanted Thorium Bar",
			note = "Takes you from 250 to 254.",
			skill = { profession = "Enchanting", from = 250, to = 254 },
			craft = { item = "Enchanted Thorium Bar", count = 5 },
			reagents = { { item = "Dream Dust", qty = 3 }, { item = "Thorium Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 12x Lesser Mana Oil",
			note = "Takes you from 254 to 265.",
			skill = { profession = "Enchanting", from = 254, to = 265 },
			craft = { item = "Lesser Mana Oil", count = 12 },
			reagents = { { item = "Dream Dust", qty = 3 }, { item = "Purple Lotus", qty = 2 }, { item = "Crystal Vial", qty = 1 } },
			source = "Formula: Lesser Mana Oil",
		},
		{
			type = "USE",
			title = "Craft 34x Enchant Bracer - Greater Stamina",
			note = "Takes you from 265 to 288.",
			skill = { profession = "Enchanting", from = 265, to = 288 },
			craft = { item = "Enchant Bracer - Greater Stamina", count = 34 },
			reagents = { { item = "Dream Dust", qty = 5 } },
			source = "Formula: Enchant Bracer - Greater Stamina",
		},
		{
			type = "USE",
			title = "Craft 13x Enchant Chest - Major Health",
			note = "Takes you from 288 to 300.",
			skill = { profession = "Enchanting", from = 288, to = 300 },
			craft = { item = "Enchant Chest - Major Health", count = 13 },
			reagents = { { item = "Illusion Dust", qty = 6 }, { item = "Small Brilliant Shard", qty = 1 } },
			source = "Formula: Enchant Chest - Major Health",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Enchanting is maxed at 300.",
		},
	},
})
