-- Engineering (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's fixed Engineering route (GPLv3, Kitymeowmeow), via
--            Tools/data/craftroute_routes.json; reagents and recipe sources
--            from Crafting/Engineering.lua; trainers from
--            Tools/data/profession_training.json
-- Generator: Tools/convert_professions.py
--
-- Regenerate with:  python3 Tools/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Engineering (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Engineering (1-300)",
			note = "A 1-300 route from CraftRoute's Engineering data. Craft counts are estimates (about 572 crafts in total). For one planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Engineering needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Engineering (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Jemma Quikswitch (Ironforge), Trixie Quikswitch (Dun Morogh), Springspindle Fizzlegear (Dun Morogh), Bronk Guzzlegear (Dun Morogh), Lilliam Sparkspindle (Stormwind City), Sprite Jumpsprocket (Stormwind City), Deek Fizzlebizz (Loch Modan), Jenna Lemkenilli (Darkshore), Tinkerwiz (The Barrens), Twizwick Sprocketgrind (The Barrens).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 75 },
			npcs = { "Jemma Quikswitch", "Trixie Quikswitch", "Springspindle Fizzlegear", "Bronk Guzzlegear", "Lilliam Sparkspindle", "Sprite Jumpsprocket", "Deek Fizzlebizz", "Jenna Lemkenilli", "Tinkerwiz", "Twizwick Sprocketgrind" },
		},
		{
			type = "TRAIN",
			title = "Learn Engineering (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Roxxik (Orgrimmar), Nogg (Orgrimmar), Thund (Orgrimmar), Mukdrak (Durotar), Franklin Lloyd (Undercity), Graham Van Talen (Undercity), Tinkerwiz (The Barrens), Twizwick Sprocketgrind (The Barrens).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 75 },
			npcs = { "Roxxik", "Nogg", "Thund", "Mukdrak", "Franklin Lloyd", "Graham Van Talen", "Tinkerwiz", "Twizwick Sprocketgrind" },
		},
		{
			type = "USE",
			title = "Craft 60x Rough Blasting Powder",
			note = "Takes you from 1 to 30.",
			skill = { profession = "Engineering", from = 1, to = 30 },
			craft = { item = "Rough Blasting Powder", count = 60 },
			reagents = { { item = "Rough Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 30x Handful of Copper Bolts",
			note = "Takes you from 30 to 50.",
			skill = { profession = "Engineering", from = 30, to = 50 },
			craft = { item = "Handful of Copper Bolts", count = 30 },
			reagents = { { item = "Copper Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Engineering needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Engineering (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Trixie Quikswitch (Dun Morogh), Springspindle Fizzlegear (Dun Morogh), Lilliam Sparkspindle (Stormwind City), Buzzek Bracketswing (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 150 },
			npcs = { "Trixie Quikswitch", "Springspindle Fizzlegear", "Lilliam Sparkspindle", "Buzzek Bracketswing" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Engineering (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Roxxik (Orgrimmar), Nogg (Orgrimmar), Franklin Lloyd (Undercity), Buzzek Bracketswing (Tanaris).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 150 },
			npcs = { "Roxxik", "Nogg", "Franklin Lloyd", "Buzzek Bracketswing" },
		},
		{
			type = "USE",
			title = "Craft 1x Arclight Spanner",
			note = "Takes you from 50 to 51.",
			skill = { profession = "Engineering", from = 50, to = 51 },
			craft = { item = "Arclight Spanner", count = 1 },
			reagents = { { item = "Copper Bar", qty = 6 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 30x Rough Copper Bomb",
			note = "Takes you from 51 to 75.",
			skill = { profession = "Engineering", from = 51, to = 75 },
			craft = { item = "Rough Copper Bomb", count = 30 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Handful of Copper Bolts", qty = 1 }, { item = "Rough Blasting Powder", qty = 2 }, { item = "Linen Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 60x Coarse Blasting Powder",
			note = "Takes you from 75 to 90.",
			skill = { profession = "Engineering", from = 75, to = 90 },
			craft = { item = "Coarse Blasting Powder", count = 60 },
			reagents = { { item = "Coarse Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Coarse Dynamite",
			note = "Takes you from 90 to 100.",
			skill = { profession = "Engineering", from = 90, to = 100 },
			craft = { item = "Coarse Dynamite", count = 20 },
			reagents = { { item = "Coarse Blasting Powder", qty = 3 }, { item = "Linen Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Silver Contact",
			note = "Takes you from 100 to 105.",
			skill = { profession = "Engineering", from = 100, to = 105 },
			craft = { item = "Silver Contact", count = 5 },
			reagents = { { item = "Silver Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 25x Bronze Tube",
			note = "Takes you from 105 to 125.",
			skill = { profession = "Engineering", from = 105, to = 125 },
			craft = { item = "Bronze Tube", count = 25 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Weak Flux", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Engineering needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Engineering (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Springspindle Fizzlegear (Dun Morogh), Buzzek Bracketswing (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 225 },
			npcs = { "Springspindle Fizzlegear", "Buzzek Bracketswing" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Engineering (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Roxxik (Orgrimmar), Buzzek Bracketswing (Tanaris).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 225 },
			npcs = { "Roxxik", "Buzzek Bracketswing" },
		},
		{
			type = "USE",
			title = "Craft 10x Standard Scope",
			note = "Takes you from 125 to 135.",
			skill = { profession = "Engineering", from = 125, to = 135 },
			craft = { item = "Standard Scope", count = 10 },
			reagents = { { item = "Bronze Tube", qty = 1 }, { item = "Moss Agate", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 59x Heavy Blasting Powder",
			note = "Takes you from 135 to 145.",
			skill = { profession = "Engineering", from = 135, to = 145 },
			craft = { item = "Heavy Blasting Powder", count = 59 },
			reagents = { { item = "Heavy Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Whirring Bronze Gizmo",
			note = "Takes you from 145 to 150.",
			skill = { profession = "Engineering", from = 145, to = 150 },
			craft = { item = "Whirring Bronze Gizmo", count = 9 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 15x Bronze Framework",
			note = "Takes you from 150 to 160.",
			skill = { profession = "Engineering", from = 150, to = 160 },
			craft = { item = "Bronze Framework", count = 15 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Medium Leather", qty = 1 }, { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 15x Explosive Sheep",
			note = "Takes you from 160 to 175.",
			skill = { profession = "Engineering", from = 160, to = 175 },
			craft = { item = "Explosive Sheep", count = 15 },
			reagents = { { item = "Bronze Framework", qty = 1 }, { item = "Whirring Bronze Gizmo", qty = 1 }, { item = "Heavy Blasting Powder", qty = 2 }, { item = "Wool Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 60x Solid Blasting Powder",
			note = "Takes you from 175 to 194.",
			skill = { profession = "Engineering", from = 175, to = 194 },
			craft = { item = "Solid Blasting Powder", count = 60 },
			reagents = { { item = "Solid Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Gyromatic Micro-Adjustor",
			note = "Takes you from 194 to 195.",
			skill = { profession = "Engineering", from = 194, to = 195 },
			craft = { item = "Gyromatic Micro-Adjustor", count = 1 },
			reagents = { { item = "Steel Bar", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Mithril Tube",
			note = "Takes you from 195 to 200.",
			skill = { profession = "Engineering", from = 195, to = 200 },
			craft = { item = "Mithril Tube", count = 7 },
			reagents = { { item = "Mithril Bar", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Engineering needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Engineering (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Buzzek Bracketswing (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 300 },
			npcs = { "Buzzek Bracketswing" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Engineering (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Buzzek Bracketswing (Tanaris).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 300 },
			npcs = { "Buzzek Bracketswing" },
		},
		{
			type = "USE",
			title = "Craft 20x Unstable Trigger",
			note = "Takes you from 200 to 215.",
			skill = { profession = "Engineering", from = 200, to = 215 },
			craft = { item = "Unstable Trigger", count = 20 },
			reagents = { { item = "Mithril Bar", qty = 1 }, { item = "Mageweave Cloth", qty = 1 }, { item = "Solid Blasting Powder", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 40x Mithril Casing",
			note = "Takes you from 215 to 238.",
			skill = { profession = "Engineering", from = 215, to = 238 },
			craft = { item = "Mithril Casing", count = 40 },
			reagents = { { item = "Mithril Bar", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Hi-Explosive Bomb",
			note = "Takes you from 238 to 250.",
			skill = { profession = "Engineering", from = 238, to = 250 },
			craft = { item = "Hi-Explosive Bomb", count = 20 },
			reagents = { { item = "Mithril Casing", qty = 2 }, { item = "Unstable Trigger", qty = 1 }, { item = "Solid Blasting Powder", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 30x Dense Blasting Powder",
			note = "Takes you from 250 to 260.",
			skill = { profession = "Engineering", from = 250, to = 260 },
			craft = { item = "Dense Blasting Powder", count = 30 },
			reagents = { { item = "Dense Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 35x Thorium Widget",
			note = "Takes you from 260 to 285.",
			skill = { profession = "Engineering", from = 260, to = 285 },
			craft = { item = "Thorium Widget", count = 35 },
			reagents = { { item = "Thorium Bar", qty = 3 }, { item = "Runecloth", qty = 1 } },
			source = "Schematic: Thorium Widget",
		},
		{
			type = "USE",
			title = "Craft 20x Thorium Tube",
			note = "Takes you from 285 to 300.",
			skill = { profession = "Engineering", from = 285, to = 300 },
			craft = { item = "Thorium Tube", count = 20 },
			reagents = { { item = "Thorium Bar", qty = 6 } },
			source = "Schematic: Thorium Tube",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Engineering is maxed at 300.",
		},
	},
})
