-- Engineering (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Engineering route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Engineering.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Engineering (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Engineering (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 478 crafts in total). For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Engineering needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Engineering (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Jemma Quikswitch (Ironforge), Trixie Quikswitch (Dun Morogh), Springspindle Fizzlegear (Dun Morogh), Bronk Guzzlegear (Dun Morogh), Lilliam Sparkspindle (Stormwind City), Sprite Jumpsprocket (Stormwind City), Deek Fizzlebizz (Loch Modan), Jenna Lemkenilli (Darkshore), Tinkerwiz (The Barrens), Twizwick Sprocketgrind (The Barrens).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 75 },
			npcs = { "Jemma Quikswitch", "Trixie Quikswitch", "Springspindle Fizzlegear", "Bronk Guzzlegear", "Lilliam Sparkspindle", "Sprite Jumpsprocket", "Deek Fizzlebizz", "Jenna Lemkenilli", "Tinkerwiz", "Twizwick Sprocketgrind" },
		},
		{
			type = "TRAIN",
			title = "Learn Engineering (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Roxxik (Orgrimmar), Nogg (Orgrimmar), Thund (Orgrimmar), Mukdrak (Durotar), Franklin Lloyd (Undercity), Graham Van Talen (Undercity), Tinkerwiz (The Barrens), Twizwick Sprocketgrind (The Barrens).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 75 },
			npcs = { "Roxxik", "Nogg", "Thund", "Mukdrak", "Franklin Lloyd", "Graham Van Talen", "Tinkerwiz", "Twizwick Sprocketgrind" },
		},
		{
			type = "USE",
			title = "Craft 62x Rough Blasting Powder",
			note = "Takes you from 1 to 38. Keep them for Rough Copper Bomb.",
			skill = { profession = "Engineering", from = 1, to = 38 },
			craft = { item = "Rough Blasting Powder", count = 62 },
			reagents = { { item = "Rough Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 19x Handful of Copper Bolts",
			note = "Takes you from 38 to 50. Keep them for Rough Copper Bomb, Copper Modulator and Crude Scope.",
			skill = { profession = "Engineering", from = 38, to = 50 },
			craft = { item = "Handful of Copper Bolts", count = 19 },
			reagents = { { item = "Copper Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Engineering needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Engineering (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Trixie Quikswitch (Dun Morogh), Springspindle Fizzlegear (Dun Morogh), Lilliam Sparkspindle (Stormwind City), Buzzek Bracketswing (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 150 },
			npcs = { "Trixie Quikswitch", "Springspindle Fizzlegear", "Lilliam Sparkspindle", "Buzzek Bracketswing" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Engineering (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Roxxik (Orgrimmar), Nogg (Orgrimmar), Franklin Lloyd (Undercity), Buzzek Bracketswing (Tanaris).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 150 },
			npcs = { "Roxxik", "Nogg", "Franklin Lloyd", "Buzzek Bracketswing" },
		},
		{
			type = "USE",
			title = "Craft 1x Arclight Spanner",
			note = "Takes you from 50 to 51.",
			skill = { profession = "Engineering", from = 50, to = 51 },
			craft = { item = "Arclight Spanner", count = 1 },
			reagents = { { item = "Copper Bar", qty = 6 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 8x Handful of Copper Bolts",
			note = "Takes you from 51 to 56. Keep them for Rough Copper Bomb, Copper Modulator and Crude Scope.",
			skill = { profession = "Engineering", from = 51, to = 56 },
			craft = { item = "Handful of Copper Bolts", count = 8 },
			reagents = { { item = "Copper Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Rough Copper Bomb",
			note = "Takes you from 56 to 65.",
			skill = { profession = "Engineering", from = 56, to = 65 },
			craft = { item = "Rough Copper Bomb", count = 10 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Handful of Copper Bolts", qty = 1 }, { item = "Rough Blasting Powder", qty = 2 }, { item = "Linen Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Copper Modulator",
			note = "Takes you from 65 to 72. Keep them for Small Seaforium Charge.",
			skill = { profession = "Engineering", from = 65, to = 72 },
			craft = { item = "Copper Modulator", count = 7 },
			reagents = { { item = "Handful of Copper Bolts", qty = 2 }, { item = "Copper Bar", qty = 1 }, { item = "Linen Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 3x Crude Scope",
			note = "Takes you from 72 to 75.",
			skill = { profession = "Engineering", from = 72, to = 75 },
			craft = { item = "Crude Scope", count = 3 },
			reagents = { { item = "Copper Tube", qty = 1 }, { item = "Malachite", qty = 1 }, { item = "Handful of Copper Bolts", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 11x Coarse Dynamite",
			note = "Takes you from 75 to 86.",
			skill = { profession = "Engineering", from = 75, to = 86 },
			craft = { item = "Coarse Dynamite", count = 11 },
			reagents = { { item = "Coarse Blasting Powder", qty = 3 }, { item = "Linen Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Crafted Heavy Shot",
			note = "Takes you from 86 to 89.",
			skill = { profession = "Engineering", from = 86, to = 89 },
			craft = { item = "Crafted Heavy Shot", count = 4 },
			reagents = { { item = "Coarse Blasting Powder", qty = 1 }, { item = "Copper Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Coarse Dynamite",
			note = "Takes you from 89 to 90.",
			skill = { profession = "Engineering", from = 89, to = 90 },
			craft = { item = "Coarse Dynamite", count = 1 },
			reagents = { { item = "Coarse Blasting Powder", qty = 3 }, { item = "Linen Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 41x Silver Contact",
			note = "Takes you from 90 to 125. Keep them for Big Iron Bomb.",
			skill = { profession = "Engineering", from = 90, to = 125 },
			craft = { item = "Silver Contact", count = 41 },
			reagents = { { item = "Silver Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Engineering needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Engineering (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Springspindle Fizzlegear (Dun Morogh), Buzzek Bracketswing (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 225 },
			npcs = { "Springspindle Fizzlegear", "Buzzek Bracketswing" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Engineering (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Roxxik (Orgrimmar), Buzzek Bracketswing (Tanaris).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 225 },
			npcs = { "Roxxik", "Buzzek Bracketswing" },
		},
		{
			type = "USE",
			title = "Craft 5x Whirring Bronze Gizmo",
			note = "Takes you from 125 to 129. Keep them for Explosive Sheep.",
			skill = { profession = "Engineering", from = 125, to = 129 },
			craft = { item = "Whirring Bronze Gizmo", count = 5 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 8x Heavy Blasting Powder",
			note = "Takes you from 129 to 134. Keep them for Explosive Sheep and Big Iron Bomb.",
			skill = { profession = "Engineering", from = 129, to = 134 },
			craft = { item = "Heavy Blasting Powder", count = 8 },
			reagents = { { item = "Heavy Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 3x Small Seaforium Charge",
			note = "Takes you from 134 to 136.",
			skill = { profession = "Engineering", from = 134, to = 136 },
			craft = { item = "Small Seaforium Charge", count = 3 },
			reagents = { { item = "Coarse Blasting Powder", qty = 2 }, { item = "Copper Modulator", qty = 1 }, { item = "Light Leather", qty = 1 }, { item = "Refreshing Spring Water", qty = 1 } },
			source = "Schematic: Small Seaforium Charge",
		},
		{
			type = "USE",
			title = "Craft 14x Flying Tiger Goggles",
			note = "Takes you from 136 to 145.",
			skill = { profession = "Engineering", from = 136, to = 145 },
			craft = { item = "Flying Tiger Goggles", count = 14 },
			reagents = { { item = "Light Leather", qty = 6 }, { item = "Tigerseye", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Bronze Framework",
			note = "Takes you from 145 to 150. Keep them for Explosive Sheep.",
			skill = { profession = "Engineering", from = 145, to = 150 },
			craft = { item = "Bronze Framework", count = 6 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Medium Leather", qty = 1 }, { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Explosive Sheep",
			note = "Takes you from 150 to 155.",
			skill = { profession = "Engineering", from = 150, to = 155 },
			craft = { item = "Explosive Sheep", count = 5 },
			reagents = { { item = "Bronze Framework", qty = 1 }, { item = "Whirring Bronze Gizmo", qty = 1 }, { item = "Heavy Blasting Powder", qty = 2 }, { item = "Wool Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Bronze Framework",
			note = "Takes you from 155 to 160.",
			skill = { profession = "Engineering", from = 155, to = 160 },
			craft = { item = "Bronze Framework", count = 7 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Medium Leather", qty = 1 }, { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Iron Strut",
			note = "Takes you from 160 to 170.",
			skill = { profession = "Engineering", from = 160, to = 170 },
			craft = { item = "Iron Strut", count = 14 },
			reagents = { { item = "Iron Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Gyrochronatom",
			note = "Takes you from 170 to 175.",
			skill = { profession = "Engineering", from = 170, to = 175 },
			craft = { item = "Gyrochronatom", count = 6 },
			reagents = { { item = "Iron Bar", qty = 1 }, { item = "Gold Power Core", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Gyromatic Micro-Adjustor",
			note = "Takes you from 175 to 176.",
			skill = { profession = "Engineering", from = 175, to = 176 },
			craft = { item = "Gyromatic Micro-Adjustor", count = 1 },
			reagents = { { item = "Steel Bar", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Solid Blasting Powder",
			note = "Takes you from 176 to 183. Keep them for Solid Dynamite, Large Seaforium Charge, Hi-Impact Mithril Slugs and what comes after.",
			skill = { profession = "Engineering", from = 176, to = 183 },
			craft = { item = "Solid Blasting Powder", count = 9 },
			reagents = { { item = "Solid Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Solid Dynamite",
			note = "Takes you from 183 to 187.",
			skill = { profession = "Engineering", from = 183, to = 187 },
			craft = { item = "Solid Dynamite", count = 10 },
			reagents = { { item = "Solid Blasting Powder", qty = 1 }, { item = "Silk Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 55x Solid Blasting Powder",
			note = "Takes you from 187 to 195. Keep them for Large Seaforium Charge, Hi-Impact Mithril Slugs and Mithril Gyro-Shot.",
			skill = { profession = "Engineering", from = 187, to = 195 },
			craft = { item = "Solid Blasting Powder", count = 55 },
			reagents = { { item = "Solid Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Big Iron Bomb",
			note = "Takes you from 195 to 198.",
			skill = { profession = "Engineering", from = 195, to = 198 },
			craft = { item = "Big Iron Bomb", count = 4 },
			reagents = { { item = "Iron Bar", qty = 3 }, { item = "Heavy Blasting Powder", qty = 3 }, { item = "Silver Contact", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 3x Mithril Tube",
			note = "Takes you from 198 to 200.",
			skill = { profession = "Engineering", from = 198, to = 200 },
			craft = { item = "Mithril Tube", count = 3 },
			reagents = { { item = "Mithril Bar", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Engineering needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Engineering (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Buzzek Bracketswing (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Engineering", cap = 300 },
			npcs = { "Buzzek Bracketswing" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Engineering (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Buzzek Bracketswing (Tanaris).",
			faction = "Horde",
			rank = { profession = "Engineering", cap = 300 },
			npcs = { "Buzzek Bracketswing" },
		},
		{
			type = "USE",
			title = "Craft 12x Large Seaforium Charge",
			note = "Takes you from 200 to 210.",
			skill = { profession = "Engineering", from = 200, to = 210 },
			craft = { item = "Large Seaforium Charge", count = 12 },
			reagents = { { item = "Solid Blasting Powder", qty = 2 }, { item = "Heavy Leather", qty = 2 }, { item = "Refreshing Spring Water", qty = 1 } },
			source = "Schematic: Large Seaforium Charge",
		},
		{
			type = "USE",
			title = "Craft 80x Hi-Impact Mithril Slugs",
			note = "Takes you from 210 to 245.",
			skill = { profession = "Engineering", from = 210, to = 245 },
			craft = { item = "Hi-Impact Mithril Slugs", count = 80 },
			reagents = { { item = "Mithril Bar", qty = 1 }, { item = "Solid Blasting Powder", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Mithril Gyro-Shot",
			note = "Takes you from 245 to 250.",
			skill = { profession = "Engineering", from = 245, to = 250 },
			craft = { item = "Mithril Gyro-Shot", count = 6 },
			reagents = { { item = "Mithril Bar", qty = 2 }, { item = "Solid Blasting Powder", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 11x Dense Blasting Powder",
			note = "Takes you from 250 to 257. Keep them for Thorium Shells.",
			skill = { profession = "Engineering", from = 250, to = 257 },
			craft = { item = "Dense Blasting Powder", count = 11 },
			reagents = { { item = "Dense Stone", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Mithril Gyro-Shot",
			note = "Takes you from 257 to 265.",
			skill = { profession = "Engineering", from = 257, to = 265 },
			craft = { item = "Mithril Gyro-Shot", count = 14 },
			reagents = { { item = "Mithril Bar", qty = 2 }, { item = "Solid Blasting Powder", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 27x Thorium Widget",
			note = "Takes you from 265 to 289.",
			skill = { profession = "Engineering", from = 265, to = 289 },
			craft = { item = "Thorium Widget", count = 27 },
			reagents = { { item = "Thorium Bar", qty = 3 }, { item = "Runecloth", qty = 1 } },
			source = "Schematic: Thorium Widget",
		},
		{
			type = "USE",
			title = "Craft 11x Thorium Shells",
			note = "Takes you from 289 to 300.",
			skill = { profession = "Engineering", from = 289, to = 300 },
			craft = { item = "Thorium Shells", count = 11 },
			reagents = { { item = "Thorium Bar", qty = 2 }, { item = "Dense Blasting Powder", qty = 1 } },
			source = "Schematic: Thorium Shells",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Engineering is maxed at 300.",
		},
	},
})
