-- First Aid (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    the route and each bandage's skill colours from
--            Tools/data/profession_training.json; reagents, recipe sources
--            and trainers from Tools/data/Professions_Reference.docx
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("First Aid (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "First Aid (1-300)",
			note = "A 1-300 route. Craft counts are the average it takes, rounded up, from each bandage's skill colours (about 399 crafts in total).",
		},
		{
			type = "TRAIN",
			title = "Learn First Aid (Apprentice)",
			note = "Costs 5 copper. Trainers: Thamner Pol (Dun Morogh), Aelira Dawnhand (Thalassian Highlands), Michelle Belle (Elwynn Forest), Byancie (Teldrassil).",
			faction = "Alliance",
			rank = { profession = "First Aid", cap = 75 },
			npcs = { "Thamner Pol", "Aelira Dawnhand", "Michelle Belle", "Byancie" },
		},
		{
			type = "TRAIN",
			title = "Learn First Aid (Apprentice)",
			note = "Costs 5 copper. Trainers: Leyna Dayton (Silverpine Forest), Nurse Neela (Tirisfal Glades), Vira Younghoof (Mulgore), Kana Togglebend (Blackstone Island).",
			faction = "Horde",
			rank = { profession = "First Aid", cap = 75 },
			npcs = { "Leyna Dayton", "Nurse Neela", "Vira Younghoof", "Kana Togglebend" },
		},
		{
			type = "USE",
			title = "Craft 41x Linen Bandage",
			note = "Takes you from 1 to 40.",
			skill = { profession = "First Aid", from = 1, to = 40 },
			craft = { item = "Linen Bandage", count = 41 },
			reagents = { { item = "Linen Cloth", qty = 1 } },
			source = "Auto-learned",
		},
		{
			type = "USE",
			title = "Craft 10x Heavy Linen Bandage",
			note = "Takes you from 40 to 50.",
			skill = { profession = "First Aid", from = 40, to = 50 },
			craft = { item = "Heavy Linen Bandage", count = 10 },
			reagents = { { item = "Linen Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Journeyman First Aid (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Thamner Pol (Dun Morogh), Aelira Dawnhand (Thalassian Highlands), Michelle Belle (Elwynn Forest), Byancie (Teldrassil).",
			faction = "Alliance",
			rank = { profession = "First Aid", cap = 150 },
			npcs = { "Thamner Pol", "Aelira Dawnhand", "Michelle Belle", "Byancie" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman First Aid (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Leyna Dayton (Silverpine Forest), Nurse Neela (Tirisfal Glades), Vira Younghoof (Mulgore), Kana Togglebend (Blackstone Island).",
			faction = "Horde",
			rank = { profession = "First Aid", cap = 150 },
			npcs = { "Leyna Dayton", "Nurse Neela", "Vira Younghoof", "Kana Togglebend" },
		},
		{
			type = "USE",
			title = "Craft 46x Heavy Linen Bandage",
			note = "Takes you from 50 to 80.",
			skill = { profession = "First Aid", from = 50, to = 80 },
			craft = { item = "Heavy Linen Bandage", count = 46 },
			reagents = { { item = "Linen Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 49x Wool Bandage",
			note = "Takes you from 80 to 115.",
			skill = { profession = "First Aid", from = 80, to = 115 },
			craft = { item = "Wool Bandage", count = 49 },
			reagents = { { item = "Wool Cloth", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 11x Heavy Wool Bandage",
			note = "Takes you from 115 to 125.",
			skill = { profession = "First Aid", from = 115, to = 125 },
			craft = { item = "Heavy Wool Bandage", count = 11 },
			reagents = { { item = "Wool Cloth", qty = 2 } },
			source = "Trainer",
			alternatives = { "Wool Bandage", "Anti-Venom" },
		},
		{
			type = "BUY",
			title = "Buy Expert First Aid - Under Wraps",
			note = "Deneb Walker (Arathi Highlands, Stromgarde Keep) sells it for 1 gold. Read it to raise your First Aid cap to 225; it needs skill 125.",
			faction = "Alliance",
			rank = { profession = "First Aid", cap = 225 },
			npcs = { "Deneb Walker" },
		},
		{
			type = "BUY",
			title = "Buy Expert First Aid - Under Wraps",
			note = "Balai Lok'Wein (Dustwallow Marsh, Brackenwall Village) sells it for 1 gold. Read it to raise your First Aid cap to 225; it needs skill 125.",
			faction = "Horde",
			rank = { profession = "First Aid", cap = 225 },
			npcs = { "Balai Lok'Wein" },
		},
		{
			type = "USE",
			title = "Craft 38x Heavy Wool Bandage",
			note = "Takes you from 125 to 150.",
			skill = { profession = "First Aid", from = 125, to = 150 },
			craft = { item = "Heavy Wool Bandage", count = 38 },
			reagents = { { item = "Wool Cloth", qty = 2 } },
			source = "Trainer",
			alternatives = { "Wool Bandage", "Anti-Venom" },
		},
		{
			type = "USE",
			title = "Craft 42x Silk Bandage",
			note = "Takes you from 150 to 180.",
			skill = { profession = "First Aid", from = 150, to = 180 },
			craft = { item = "Silk Bandage", count = 42 },
			reagents = { { item = "Silk Cloth", qty = 1 } },
			source = "Trainer",
			alternatives = { "Heavy Wool Bandage", "Strong Anti-Venom" },
		},
		{
			type = "USE",
			title = "Craft 42x Heavy Silk Bandage",
			note = "Takes you from 180 to 210.",
			skill = { profession = "First Aid", from = 180, to = 210 },
			craft = { item = "Heavy Silk Bandage", count = 42 },
			reagents = { { item = "Silk Cloth", qty = 2 } },
			source = "Recipe: Manual: Heavy Silk Bandage",
			alternatives = { "Heavy Wool Bandage", "Silk Bandage", "Strong Anti-Venom" },
		},
		{
			type = "USE",
			title = "Craft 18x Mageweave Bandage",
			note = "Takes you from 210 to 225.",
			skill = { profession = "First Aid", from = 210, to = 225 },
			craft = { item = "Mageweave Bandage", count = 18 },
			reagents = { { item = "Mageweave Cloth", qty = 1 } },
			source = "Recipe: Manual: Mageweave Bandage",
		},
		{
			type = "GRIND",
			title = "Reach level 40",
			note = "The Artisan First Aid quest needs character level 40. This step clears itself when you get there.",
			level = 40,
		},
		{
			type = "NOTE",
			title = "Start the Artisan First Aid quest",
			note = "Nissa Firestone in Ironforge, near the Military Ward, at the forge, starts it. Needs level 40 and skill 225.",
			faction = "Alliance",
			npcs = { "Nissa Firestone" },
		},
		{
			type = "NOTE",
			title = "Start the Artisan First Aid quest",
			note = "Arnok in Orgrimmar, the Valley of Spirits, starts it. Needs level 40 and skill 225.",
			faction = "Horde",
			npcs = { "Arnok" },
		},
		{
			type = "NOTE",
			title = "Hand in to Doctor Gustaf VanHowzen",
			note = "Dustwallow Marsh, Theramore. Triage: 15 patients in the right order before 6 die. Stand where you can see all six cots, put the special triage bandages on your action bar, and treat Critically injured first, then Badly injured, then Injured.",
			faction = "Alliance",
			rank = { profession = "First Aid", cap = 300 },
			npcs = { "Doctor Gustaf VanHowzen" },
		},
		{
			type = "NOTE",
			title = "Hand in to Doctor Gregory Victor",
			note = "Arathi Highlands, Hammerfall. Triage: 15 patients in the right order before 6 die. Stand where you can see all six cots, put the special triage bandages on your action bar, and treat Critically injured first, then Badly injured, then Injured.",
			faction = "Horde",
			rank = { profession = "First Aid", cap = 300 },
			npcs = { "Doctor Gregory Victor" },
		},
		{
			type = "USE",
			title = "Craft 24x Mageweave Bandage",
			note = "Takes you from 225 to 240.",
			skill = { profession = "First Aid", from = 225, to = 240 },
			craft = { item = "Mageweave Bandage", count = 24 },
			reagents = { { item = "Mageweave Cloth", qty = 1 } },
			source = "Recipe: Manual: Mageweave Bandage",
		},
		{
			type = "USE",
			title = "Craft 25x Heavy Mageweave Bandage",
			note = "Takes you from 240 to 260.",
			skill = { profession = "First Aid", from = 240, to = 260 },
			craft = { item = "Heavy Mageweave Bandage", count = 25 },
			reagents = { { item = "Mageweave Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 42x Runecloth Bandage",
			note = "Takes you from 260 to 290.",
			skill = { profession = "First Aid", from = 260, to = 290 },
			craft = { item = "Runecloth Bandage", count = 42 },
			reagents = { { item = "Runecloth", qty = 1 } },
			source = "Trainer",
			alternatives = { "Mageweave Bandage", "Heavy Mageweave Bandage", "Powerful Smelling Salts" },
		},
		{
			type = "USE",
			title = "Craft 11x Heavy Runecloth Bandage",
			note = "Takes you from 290 to 300.",
			skill = { profession = "First Aid", from = 290, to = 300 },
			craft = { item = "Heavy Runecloth Bandage", count = 11 },
			reagents = { { item = "Runecloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "First Aid is maxed at 300.",
		},
	},
})
