-- Herbalism (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/gathering.json -- pfQuest's gathering nodes (with
--            pfQuest-turtle) and CMaNGOS classic-db's creatures, fishing
--            skill, trainers, book and quest, extracted by
--            Tools/build/build_gathering.py; zone sides and levels from this
--            addon's own zone guides
-- Generator: Tools/build/convert_professions.py, via Tools/build/gathering_guides.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Herbalism (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Herbalism (1-300)",
			note = "Where to gather at each skill band: the zones with most of the herbs that can raise your skill there, from pfQuest's node counts. Zones show the levels this addon's guides spend there; pick one your level suits.",
		},
		{
			type = "TRAIN",
			title = "Learn Herbalism (Apprentice)",
			note = "Costs 10 copper. Trainers: Reyna Stonebranch (Ironforge), Shylamiir (Stormwind City), Tannysa (Stormwind City), Alma Jainrose (Redridge Mountains), Brant Jasperbloom (Dustwallow Marsh), Cylania Rootstalker (Ashenvale), Firodren Mooncaller (Teldrassil), Flora Silverwind (Stranglethorn Vale), Herbalist Pomeroy (Elwynn Forest), Kali Healtouch (Loch Modan), Malorne Bladeleaf (Teldrassil), Malvor (Moonglade), Telurinon Moonshadow (Wetlands).",
			faction = "Alliance",
			rank = { profession = "Herbalism", cap = 75 },
			npcs = { "Reyna Stonebranch", "Shylamiir", "Tannysa", "Alma Jainrose", "Brant Jasperbloom", "Cylania Rootstalker", "Firodren Mooncaller", "Flora Silverwind", "Herbalist Pomeroy", "Kali Healtouch", "Malorne Bladeleaf", "Malvor", "Telurinon Moonshadow" },
		},
		{
			type = "TRAIN",
			title = "Learn Herbalism (Apprentice)",
			note = "Costs 10 copper. Trainers: Jandi (Orgrimmar), Martha Alliestar (Undercity), Angrun (Stranglethorn Vale), Aranae Venomblood (Alterac Mountains), Faruza (Tirisfal Glades), Flora Silverwind (Stranglethorn Vale), Komin Winterhoof (Mulgore), Malvor (Moonglade), Mishiki (Durotar), Ruw (Feralas).",
			faction = "Horde",
			rank = { profession = "Herbalism", cap = 75 },
			npcs = { "Jandi", "Martha Alliestar", "Angrun", "Aranae Venomblood", "Faruza", "Flora Silverwind", "Komin Winterhoof", "Malvor", "Mishiki", "Ruw" },
		},
		{
			type = "GRIND",
			title = "Gather to 50: Silverleaf, Peacebloom and Earthroot",
			note = "Takes you from 1 to 50. Best: Elwynn Forest (1-12): Silverleaf, Peacebloom, Earthroot; Dun Morogh (1-12): Silverleaf, Peacebloom, Earthroot; Teldrassil (1-12): Silverleaf, Peacebloom, Earthroot.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 1, to = 50 },
		},
		{
			type = "GRIND",
			title = "Gather to 50: Silverleaf, Earthroot and Peacebloom",
			note = "Takes you from 1 to 50. Best: The Barrens (12-25): Silverleaf, Earthroot, Peacebloom; Durotar (1-12): Silverleaf, Peacebloom, Earthroot; Tirisfal Glades (1-12): Silverleaf, Peacebloom, Earthroot.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 1, to = 50 },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Herbalism (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Reyna Stonebranch (Ironforge), Shylamiir (Stormwind City), Tannysa (Stormwind City), Alma Jainrose (Redridge Mountains), Brant Jasperbloom (Dustwallow Marsh), Cylania Rootstalker (Ashenvale), Firodren Mooncaller (Teldrassil), Flora Silverwind (Stranglethorn Vale), Herbalist Pomeroy (Elwynn Forest), Kali Healtouch (Loch Modan), Malorne Bladeleaf (Teldrassil), Malvor (Moonglade), Telurinon Moonshadow (Wetlands).",
			faction = "Alliance",
			rank = { profession = "Herbalism", cap = 150 },
			npcs = { "Reyna Stonebranch", "Shylamiir", "Tannysa", "Alma Jainrose", "Brant Jasperbloom", "Cylania Rootstalker", "Firodren Mooncaller", "Flora Silverwind", "Herbalist Pomeroy", "Kali Healtouch", "Malorne Bladeleaf", "Malvor", "Telurinon Moonshadow" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Herbalism (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Jandi (Orgrimmar), Martha Alliestar (Undercity), Angrun (Stranglethorn Vale), Aranae Venomblood (Alterac Mountains), Faruza (Tirisfal Glades), Flora Silverwind (Stranglethorn Vale), Komin Winterhoof (Mulgore), Malvor (Moonglade), Mishiki (Durotar), Ruw (Feralas).",
			faction = "Horde",
			rank = { profession = "Herbalism", cap = 150 },
			npcs = { "Jandi", "Martha Alliestar", "Angrun", "Aranae Venomblood", "Faruza", "Flora Silverwind", "Komin Winterhoof", "Malvor", "Mishiki", "Ruw" },
		},
		{
			type = "GRIND",
			title = "Gather to 70: Mageroyal, Earthroot and Silverleaf",
			note = "Takes you from 50 to 70. Best: Darkshore (12-24): Mageroyal, Earthroot, Silverleaf; Westfall (12-17): Mageroyal, Earthroot, Silverleaf; Ashenvale (21-30): Mageroyal.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 50, to = 70 },
		},
		{
			type = "GRIND",
			title = "Gather to 70: Mageroyal, Earthroot and Silverleaf",
			note = "Takes you from 50 to 70. Best: The Barrens (12-25): Mageroyal, Earthroot, Silverleaf; Durotar (1-12): Earthroot, Silverleaf, Mageroyal; Ashenvale (26-27): Mageroyal.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 50, to = 70 },
		},
		{
			type = "GRIND",
			title = "Gather to 85: Briarthorn, Mageroyal and Silverleaf",
			note = "Takes you from 70 to 85. Best: Darkshore (12-24): Briarthorn, Mageroyal, Silverleaf; Duskwood (28-29): Briarthorn, Mageroyal; Ashenvale (21-30): Briarthorn, Mageroyal.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 70, to = 85 },
		},
		{
			type = "GRIND",
			title = "Gather to 85: Mageroyal, Briarthorn and Silverleaf",
			note = "Takes you from 70 to 85. Best: The Barrens (12-25): Mageroyal, Briarthorn, Silverleaf; Ashenvale (26-27): Briarthorn, Mageroyal; Grim Reaches (33-38): Briarthorn, Mageroyal, Silverleaf.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 70, to = 85 },
		},
		{
			type = "GRIND",
			title = "Gather to 100: Stranglekelp, Briarthorn and Mageroyal",
			note = "Takes you from 85 to 100. Best: Darkshore (12-24): Stranglekelp, Briarthorn, Mageroyal; Ashenvale (21-30): Stranglekelp, Briarthorn, Mageroyal; Westfall (12-17): Briarthorn, Mageroyal, Stranglekelp.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 85, to = 100 },
		},
		{
			type = "GRIND",
			title = "Gather to 100: Mageroyal, Briarthorn and Stranglekelp",
			note = "Takes you from 85 to 100. Best: The Barrens (12-25): Mageroyal, Briarthorn, Stranglekelp; Ashenvale (26-27): Stranglekelp, Briarthorn, Mageroyal; Silverpine Forest (12-20): Briarthorn, Mageroyal, Stranglekelp.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 85, to = 100 },
		},
		{
			type = "GRIND",
			title = "Gather to 115: Stranglekelp, Bruiseweed and Briarthorn",
			note = "Takes you from 100 to 115. Best: Ashenvale (21-30): Stranglekelp, Bruiseweed, Briarthorn; Darkshore (12-24): Stranglekelp, Bruiseweed, Briarthorn; Stonetalon Mountains (22-23): Bruiseweed, Briarthorn, Stranglekelp.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 100, to = 115 },
		},
		{
			type = "GRIND",
			title = "Gather to 115: Bruiseweed, Stranglekelp and Mageroyal",
			note = "Takes you from 100 to 115. Best: The Barrens (12-25): Bruiseweed, Stranglekelp, Mageroyal; Ashenvale (26-27): Stranglekelp, Bruiseweed, Briarthorn; Stonetalon Mountains (20-27): Bruiseweed, Briarthorn, Stranglekelp.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 100, to = 115 },
		},
		{
			type = "GRIND",
			title = "Gather to 125: Bruiseweed, Wild Steelbloom and Briarthorn",
			note = "Takes you from 115 to 125. Best: Stonetalon Mountains (22-23): Bruiseweed, Wild Steelbloom, Briarthorn; Ashenvale (21-30): Bruiseweed, Stranglekelp, Briarthorn; Wetlands (24-31): Bruiseweed, Wild Steelbloom, Stranglekelp.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 115, to = 125 },
		},
		{
			type = "GRIND",
			title = "Gather to 125: Bruiseweed, Mageroyal and Briarthorn",
			note = "Takes you from 115 to 125. Best: The Barrens (12-25): Bruiseweed, Mageroyal, Briarthorn; Stonetalon Mountains (20-27): Bruiseweed, Wild Steelbloom, Briarthorn; Ashenvale (26-27): Bruiseweed, Stranglekelp, Briarthorn.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 115, to = 125 },
		},
		{
			type = "TRAIN",
			title = "Train Expert Herbalism (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Reyna Stonebranch (Ironforge), Shylamiir (Stormwind City), Tannysa (Stormwind City), Alma Jainrose (Redridge Mountains), Brant Jasperbloom (Dustwallow Marsh), Cylania Rootstalker (Ashenvale), Firodren Mooncaller (Teldrassil), Flora Silverwind (Stranglethorn Vale), Herbalist Pomeroy (Elwynn Forest), Kali Healtouch (Loch Modan), Malorne Bladeleaf (Teldrassil), Malvor (Moonglade), Telurinon Moonshadow (Wetlands).",
			faction = "Alliance",
			rank = { profession = "Herbalism", cap = 225 },
			npcs = { "Reyna Stonebranch", "Shylamiir", "Tannysa", "Alma Jainrose", "Brant Jasperbloom", "Cylania Rootstalker", "Firodren Mooncaller", "Flora Silverwind", "Herbalist Pomeroy", "Kali Healtouch", "Malorne Bladeleaf", "Malvor", "Telurinon Moonshadow" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Herbalism (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Jandi (Orgrimmar), Martha Alliestar (Undercity), Angrun (Stranglethorn Vale), Aranae Venomblood (Alterac Mountains), Faruza (Tirisfal Glades), Flora Silverwind (Stranglethorn Vale), Komin Winterhoof (Mulgore), Malvor (Moonglade), Mishiki (Durotar), Ruw (Feralas).",
			faction = "Horde",
			rank = { profession = "Herbalism", cap = 225 },
			npcs = { "Jandi", "Martha Alliestar", "Angrun", "Aranae Venomblood", "Faruza", "Flora Silverwind", "Komin Winterhoof", "Malvor", "Mishiki", "Ruw" },
		},
		{
			type = "GRIND",
			title = "Gather to 150: Wild Steelbloom, Bruiseweed and Kingsblood",
			note = "Takes you from 125 to 150. Best: Stonetalon Mountains (22-23): Wild Steelbloom, Bruiseweed, Kingsblood; Ashenvale (21-30): Stranglekelp, Bruiseweed, Kingsblood; Wetlands (24-31): Bruiseweed, Wild Steelbloom, Kingsblood.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 125, to = 150 },
		},
		{
			type = "GRIND",
			title = "Gather to 150: Bruiseweed, Mageroyal and Stranglekelp",
			note = "Takes you from 125 to 150. Best: The Barrens (12-25): Bruiseweed, Mageroyal, Stranglekelp; Stonetalon Mountains (20-27): Wild Steelbloom, Bruiseweed, Kingsblood; Ashenvale (26-27): Stranglekelp, Bruiseweed, Kingsblood.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 125, to = 150 },
		},
		{
			type = "GRIND",
			title = "Gather to 170: Wild Steelbloom, Liferoot and Kingsblood",
			note = "Takes you from 150 to 170. Best: Arathi Highlands (37-38): Wild Steelbloom, Liferoot, Kingsblood; Wetlands (24-31): Liferoot, Wild Steelbloom, Kingsblood; Stranglethorn Vale (32-47): Liferoot, Kingsblood, Wild Steelbloom.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 150, to = 170 },
		},
		{
			type = "GRIND",
			title = "Gather to 170: Wild Steelbloom, Liferoot and Kingsblood",
			note = "Takes you from 150 to 170. Best: Arathi Highlands (30-38): Wild Steelbloom, Liferoot, Kingsblood; Stranglethorn Vale (30-47): Liferoot, Kingsblood, Wild Steelbloom; The Barrens (12-25): Bruiseweed, Wild Steelbloom, Kingsblood.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 150, to = 170 },
		},
		{
			type = "GRIND",
			title = "Gather to 185: Goldthorn, Fadeleaf and Liferoot",
			note = "Takes you from 170 to 185. Best: Stranglethorn Vale (32-47): Goldthorn, Fadeleaf, Liferoot; Arathi Highlands (37-38): Goldthorn, Fadeleaf, Liferoot; Alterac Mountains (36-37): Goldthorn, Fadeleaf, Liferoot.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 170, to = 185 },
		},
		{
			type = "GRIND",
			title = "Gather to 185: Goldthorn, Fadeleaf and Liferoot",
			note = "Takes you from 170 to 185. Best: Stranglethorn Vale (30-47): Goldthorn, Fadeleaf, Liferoot; Arathi Highlands (30-38): Goldthorn, Fadeleaf, Liferoot; Alterac Mountains (36-37): Goldthorn, Fadeleaf, Liferoot.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 170, to = 185 },
		},
		{
			type = "GRIND",
			title = "Gather to 200: Khadgar's Whisker, Goldthorn and Liferoot",
			note = "Takes you from 185 to 200. Best: Stranglethorn Vale (32-47): Khadgar's Whisker, Goldthorn, Liferoot; Arathi Highlands (37-38): Goldthorn, Khadgar's Whisker, Fadeleaf; Swamp of Sorrows (41-42): Goldthorn, Khadgar's Whisker, Fadeleaf.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 185, to = 200 },
		},
		{
			type = "GRIND",
			title = "Gather to 200: Khadgar's Whisker, Goldthorn and Liferoot",
			note = "Takes you from 185 to 200. Best: Stranglethorn Vale (30-47): Khadgar's Whisker, Goldthorn, Liferoot; Arathi Highlands (30-38): Goldthorn, Khadgar's Whisker, Fadeleaf; Swamp of Sorrows (41-49): Goldthorn, Khadgar's Whisker, Fadeleaf.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 185, to = 200 },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Herbalism (Cap 300)",
			note = "Needs skill 200; costs 5 gold. Trainers: Reyna Stonebranch (Ironforge), Shylamiir (Stormwind City), Tannysa (Stormwind City), Alma Jainrose (Redridge Mountains), Brant Jasperbloom (Dustwallow Marsh), Cylania Rootstalker (Ashenvale), Firodren Mooncaller (Teldrassil), Flora Silverwind (Stranglethorn Vale), Herbalist Pomeroy (Elwynn Forest), Kali Healtouch (Loch Modan), Malorne Bladeleaf (Teldrassil), Malvor (Moonglade), Telurinon Moonshadow (Wetlands).",
			faction = "Alliance",
			rank = { profession = "Herbalism", cap = 300 },
			npcs = { "Reyna Stonebranch", "Shylamiir", "Tannysa", "Alma Jainrose", "Brant Jasperbloom", "Cylania Rootstalker", "Firodren Mooncaller", "Flora Silverwind", "Herbalist Pomeroy", "Kali Healtouch", "Malorne Bladeleaf", "Malvor", "Telurinon Moonshadow" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Herbalism (Cap 300)",
			note = "Needs skill 200; costs 5 gold. Trainers: Jandi (Orgrimmar), Martha Alliestar (Undercity), Angrun (Stranglethorn Vale), Aranae Venomblood (Alterac Mountains), Faruza (Tirisfal Glades), Flora Silverwind (Stranglethorn Vale), Komin Winterhoof (Mulgore), Malvor (Moonglade), Mishiki (Durotar), Ruw (Feralas).",
			faction = "Horde",
			rank = { profession = "Herbalism", cap = 300 },
			npcs = { "Jandi", "Martha Alliestar", "Angrun", "Aranae Venomblood", "Faruza", "Flora Silverwind", "Komin Winterhoof", "Malvor", "Mishiki", "Ruw" },
		},
		{
			type = "GRIND",
			title = "Gather to 230: Khadgar's Whisker, Goldthorn and Purple Lotus",
			note = "Takes you from 200 to 230. Best: Stranglethorn Vale (32-47): Khadgar's Whisker, Goldthorn, Purple Lotus; Arathi Highlands (37-38): Goldthorn, Khadgar's Whisker, Wild Steelbloom; Azshara (46-53): Purple Lotus, Khadgar's Whisker.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 200, to = 230 },
		},
		{
			type = "GRIND",
			title = "Gather to 230: Khadgar's Whisker, Goldthorn and Purple Lotus",
			note = "Takes you from 200 to 230. Best: Stranglethorn Vale (30-47): Khadgar's Whisker, Goldthorn, Purple Lotus; Arathi Highlands (30-38): Goldthorn, Khadgar's Whisker, Wild Steelbloom; Azshara (46-50): Purple Lotus, Khadgar's Whisker.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 200, to = 230 },
		},
		{
			type = "GRIND",
			title = "Gather to 250: Sungrass, Purple Lotus and Khadgar's Whisker",
			note = "Takes you from 230 to 250. Best: Azshara (46-53): Sungrass, Purple Lotus, Khadgar's Whisker; Swamp of Sorrows (41-42): Blindweed, Goldthorn, Khadgar's Whisker; The Hinterlands (46-50): Sungrass, Purple Lotus, Goldthorn.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 230, to = 250 },
		},
		{
			type = "GRIND",
			title = "Gather to 250: Sungrass, Purple Lotus and Khadgar's Whisker",
			note = "Takes you from 230 to 250. Best: Azshara (46-50): Sungrass, Purple Lotus, Khadgar's Whisker; Swamp of Sorrows (41-49): Blindweed, Goldthorn, Khadgar's Whisker; The Hinterlands (47-51): Sungrass, Purple Lotus, Goldthorn.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 230, to = 250 },
		},
		{
			type = "GRIND",
			title = "Gather to 270: Blindweed, Goldthorn and Khadgar's Whisker",
			note = "Takes you from 250 to 270. Best: Swamp of Sorrows (41-42): Blindweed, Goldthorn, Khadgar's Whisker; Azshara (46-53): Purple Lotus, Sungrass, Khadgar's Whisker; The Hinterlands (46-50): Sungrass, Ghost Mushroom, Purple Lotus.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 250, to = 270 },
		},
		{
			type = "GRIND",
			title = "Gather to 270: Blindweed, Goldthorn and Khadgar's Whisker",
			note = "Takes you from 250 to 270. Best: Swamp of Sorrows (41-49): Blindweed, Goldthorn, Khadgar's Whisker; Azshara (46-50): Purple Lotus, Sungrass, Khadgar's Whisker; The Hinterlands (47-51): Sungrass, Ghost Mushroom, Purple Lotus.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 250, to = 270 },
		},
		{
			type = "GRIND",
			title = "Gather to 285: Dreamfoil, Golden Sansam and Sungrass",
			note = "Takes you from 270 to 285. Best: Azshara (46-53): Dreamfoil, Golden Sansam, Sungrass; Un'Goro Crater (51-52): Dreamfoil, Golden Sansam, Sungrass; Felwood (53-56): Gromsblood, Dreamfoil, Golden Sansam.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 270, to = 285 },
		},
		{
			type = "GRIND",
			title = "Gather to 285: Dreamfoil, Golden Sansam and Sungrass",
			note = "Takes you from 270 to 285. Best: Azshara (46-50): Dreamfoil, Golden Sansam, Sungrass; Un'Goro Crater (51-53): Dreamfoil, Golden Sansam, Sungrass; Felwood (54-56): Gromsblood, Dreamfoil, Golden Sansam.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 270, to = 285 },
		},
		{
			type = "GRIND",
			title = "Gather to 300: Plaguebloom, Dreamfoil and Golden Sansam",
			note = "Takes you from 285 to 300. Best: Eastern Plaguelands (57-58): Plaguebloom, Dreamfoil, Golden Sansam; Winterspring (54-60): Icecap, Mountain Silversage, Dreamfoil; Azshara (46-53): Dreamfoil, Mountain Silversage, Golden Sansam.",
			faction = "Alliance",
			skill = { profession = "Herbalism", from = 285, to = 300 },
		},
		{
			type = "GRIND",
			title = "Gather to 300: Plaguebloom, Dreamfoil and Golden Sansam",
			note = "Takes you from 285 to 300. Best: Eastern Plaguelands (56-57): Plaguebloom, Dreamfoil, Golden Sansam; Winterspring (54-60): Icecap, Mountain Silversage, Dreamfoil; Azshara (46-50): Dreamfoil, Mountain Silversage, Golden Sansam.",
			faction = "Horde",
			skill = { profession = "Herbalism", from = 285, to = 300 },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Herbalism is maxed at 300.",
		},
	},
})
