-- Jewelcrafting (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Jewelcrafting route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Jewelcrafting.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Jewelcrafting (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Jewelcrafting (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 465 crafts in total). Nobody was selling Copper Ore, Amber Topaz, Crystal Quartz and Pure Moonstone then, so they were costed at 3 times what a merchant pays. For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Jewelcrafting needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Jewelcrafting (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Brandon Fencer (Stormwind City), Frabus Barleymantle (Ironforge), Kalvan Fencer (Stormwind City), Ranellius Pureheart (Alah'Thalas).",
			faction = "Alliance",
			rank = { profession = "Jewelcrafting", cap = 75 },
			npcs = { "Brandon Fencer", "Frabus Barleymantle", "Kalvan Fencer", "Ranellius Pureheart" },
		},
		{
			type = "TRAIN",
			title = "Learn Jewelcrafting (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Asoran (Orgrimmar), Edgar Tullson (Undercity), Gelpan Rizspark (Durotar), Mayvelle Tonberg (Undercity).",
			faction = "Horde",
			rank = { profession = "Jewelcrafting", cap = 75 },
			npcs = { "Asoran", "Edgar Tullson", "Gelpan Rizspark", "Mayvelle Tonberg" },
		},
		{
			type = "USE",
			title = "Craft 49x Rough Gritted Paper",
			note = "Takes you from 1 to 30. Keep them for Rough Gemstone Cluster, Tigercrest Ring and Amber Orb.",
			skill = { profession = "Jewelcrafting", from = 1, to = 30 },
			craft = { item = "Rough Gritted Paper", count = 49 },
			reagents = { { item = "Linen Cloth", qty = 1 }, { item = "Rough Stone", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Rough Copper Ring",
			note = "Takes you from 30 to 34. Keep them for Bright Copper Ring, Tigercrest Ring and Softglow Ring.",
			skill = { profession = "Jewelcrafting", from = 30, to = 34 },
			craft = { item = "Rough Copper Ring", count = 7 },
			reagents = { { item = "Copper Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Bright Copper Ring",
			note = "Takes you from 34 to 35.",
			skill = { profession = "Jewelcrafting", from = 34, to = 35 },
			craft = { item = "Bright Copper Ring", count = 1 },
			reagents = { { item = "Rough Copper Ring", qty = 1 }, { item = "Polishing Oil", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 24x Rough Gemstone Cluster",
			note = "Takes you from 35 to 50.",
			skill = { profession = "Jewelcrafting", from = 35, to = 50 },
			craft = { item = "Rough Gemstone Cluster", count = 24 },
			reagents = { { item = "Rough Gritted Paper", qty = 1 }, { item = "Copper Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Jewelcrafting needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Jewelcrafting (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Kalvan Fencer (Stormwind City), Ethennar Somberfall (Alah'Thalas), Torvag Thunderhand (Ironforge), Mayva Togview (Ironforge).",
			faction = "Alliance",
			rank = { profession = "Jewelcrafting", cap = 150 },
			npcs = { "Kalvan Fencer", "Ethennar Somberfall", "Torvag Thunderhand", "Mayva Togview" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Jewelcrafting (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Mayvelle Tonberg (Undercity), Tacknazz Copperfire (Durotar), Kalnag (Orgrimmar), Gulmire Fartower (Undercity).",
			faction = "Horde",
			rank = { profession = "Jewelcrafting", cap = 150 },
			npcs = { "Mayvelle Tonberg", "Tacknazz Copperfire", "Kalnag", "Gulmire Fartower" },
		},
		{
			type = "USE",
			title = "Craft 6x Rough Gemstone Cluster",
			note = "Takes you from 50 to 54.",
			skill = { profession = "Jewelcrafting", from = 50, to = 54 },
			craft = { item = "Rough Gemstone Cluster", count = 6 },
			reagents = { { item = "Rough Gritted Paper", qty = 1 }, { item = "Copper Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Tigercrest Ring",
			note = "Takes you from 54 to 73.",
			skill = { profession = "Jewelcrafting", from = 54, to = 73 },
			craft = { item = "Tigercrest Ring", count = 20 },
			reagents = { { item = "Rough Copper Ring", qty = 1 }, { item = "Rough Gritted Paper", qty = 1 }, { item = "Polishing Oil", qty = 1 }, { item = "Tigerseye", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 18x Softglow Ring",
			note = "Takes you from 73 to 90.",
			skill = { profession = "Jewelcrafting", from = 73, to = 90 },
			craft = { item = "Softglow Ring", count = 18 },
			reagents = { { item = "Rough Copper Ring", qty = 1 }, { item = "Malachite", qty = 1 }, { item = "Weak Flux", qty = 1 }, { item = "Tigerseye", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 26x Rough Bronze Ring",
			note = "Takes you from 90 to 110. Keep them for Shadowgem Band and Ocean's Wrath.",
			skill = { profession = "Jewelcrafting", from = 90, to = 110 },
			craft = { item = "Rough Bronze Ring", count = 26 },
			reagents = { { item = "Bronze Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Amber Orb",
			note = "Takes you from 110 to 114.",
			skill = { profession = "Jewelcrafting", from = 110, to = 114 },
			craft = { item = "Amber Orb", count = 5 },
			reagents = { { item = "Bronze Bar", qty = 2 }, { item = "Amber Topaz", qty = 3 }, { item = "Rough Gritted Paper", qty = 4 }, { item = "Polishing Oil", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Shadowgem Band",
			note = "Takes you from 114 to 115.",
			skill = { profession = "Jewelcrafting", from = 114, to = 115 },
			craft = { item = "Shadowgem Band", count = 1 },
			reagents = { { item = "Rough Bronze Ring", qty = 1 }, { item = "Shadowgem", qty = 2 }, { item = "Shimmering Oil", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 11x Ocean's Wrath",
			note = "Takes you from 115 to 125.",
			skill = { profession = "Jewelcrafting", from = 115, to = 125 },
			craft = { item = "Ocean's Wrath", count = 11 },
			reagents = { { item = "Rough Bronze Ring", qty = 1 }, { item = "Small Lustrous Pearl", qty = 1 }, { item = "Weak Flux", qty = 1 } },
			source = "Plans: Ocean's Wrath",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Jewelcrafting needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Jewelcrafting (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Fanzy Sparkspring (Tanaris), Mayva Togview (Ironforge), Kalvan Fencer (Stormwind City), Ethennar Somberfall (Alah'Thalas).",
			faction = "Alliance",
			rank = { profession = "Jewelcrafting", cap = 225 },
			npcs = { "Fanzy Sparkspring", "Mayva Togview", "Kalvan Fencer", "Ethennar Somberfall" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Jewelcrafting (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Fanzy Sparkspring (Tanaris), Gulmire Fartower (Undercity), Mayvelle Tonberg (Undercity), Tacknazz Copperfire (Durotar).",
			faction = "Horde",
			rank = { profession = "Jewelcrafting", cap = 225 },
			npcs = { "Fanzy Sparkspring", "Gulmire Fartower", "Mayvelle Tonberg", "Tacknazz Copperfire" },
		},
		{
			type = "USE",
			title = "Craft 37x Rough Silver Ring",
			note = "Takes you from 125 to 150.",
			skill = { profession = "Jewelcrafting", from = 125, to = 150 },
			craft = { item = "Rough Silver Ring", count = 37 },
			reagents = { { item = "Silver Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 2x Heavy Gritted Paper",
			note = "Takes you from 150 to 151. Keep them for Ironbloom Ring.",
			skill = { profession = "Jewelcrafting", from = 150, to = 151 },
			craft = { item = "Heavy Gritted Paper", count = 2 },
			reagents = { { item = "Silk Cloth", qty = 3 }, { item = "Heavy Stone", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 44x Rough Iron Ring",
			note = "Takes you from 151 to 175. Keep them for Ironbloom Ring.",
			skill = { profession = "Jewelcrafting", from = 151, to = 175 },
			craft = { item = "Rough Iron Ring", count = 44 },
			reagents = { { item = "Iron Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 14x Rough Mithril Ring",
			note = "Takes you from 175 to 180. Keep them for Greater Binding Signet.",
			skill = { profession = "Jewelcrafting", from = 175, to = 180 },
			craft = { item = "Rough Mithril Ring", count = 14 },
			reagents = { { item = "Mithril Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Goldenshade Quartz Crown",
			note = "Takes you from 180 to 199.",
			skill = { profession = "Jewelcrafting", from = 180, to = 199 },
			craft = { item = "Goldenshade Quartz Crown", count = 20 },
			reagents = { { item = "Iron Bar", qty = 8 }, { item = "Gold Bar", qty = 2 }, { item = "Crystal Quartz", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Ironbloom Ring",
			note = "Takes you from 199 to 200.",
			skill = { profession = "Jewelcrafting", from = 199, to = 200 },
			craft = { item = "Ironbloom Ring", count = 1 },
			reagents = { { item = "Rough Iron Ring", qty = 1 }, { item = "Iron Bar", qty = 2 }, { item = "Heavy Stone", qty = 6 }, { item = "Wild Steelbloom", qty = 1 }, { item = "Heavy Gritted Paper", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Jewelcrafting needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Jewelcrafting (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: The Artificer (Desolace), Thegren (Badlands), Fanzy Sparkspring (Tanaris).",
			faction = "Alliance",
			rank = { profession = "Jewelcrafting", cap = 300 },
			npcs = { "The Artificer", "Thegren", "Fanzy Sparkspring" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Jewelcrafting (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: The Artificer (Desolace), Thegren (Badlands), Fanzy Sparkspring (Tanaris).",
			faction = "Horde",
			rank = { profession = "Jewelcrafting", cap = 300 },
			npcs = { "The Artificer", "Thegren", "Fanzy Sparkspring" },
		},
		{
			type = "USE",
			title = "Craft 20x Solid Gritted Paper",
			note = "Takes you from 200 to 209.",
			skill = { profession = "Jewelcrafting", from = 200, to = 209 },
			craft = { item = "Solid Gritted Paper", count = 20 },
			reagents = { { item = "Mageweave Cloth", qty = 3 }, { item = "Solid Stone", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 16x Heart of the Sea",
			note = "Takes you from 209 to 224.",
			skill = { profession = "Jewelcrafting", from = 209, to = 224 },
			craft = { item = "Heart of the Sea", count = 16 },
			reagents = { { item = "Mithril Bar", qty = 4 }, { item = "Elemental Water", qty = 4 }, { item = "Aquamarine", qty = 1 }, { item = "Shimmering Oil", qty = 1 } },
			source = "Quest reward",
		},
		{
			type = "USE",
			title = "Craft 12x Greater Binding Signet",
			note = "Takes you from 224 to 235.",
			skill = { profession = "Jewelcrafting", from = 224, to = 235 },
			craft = { item = "Greater Binding Signet", count = 12 },
			reagents = { { item = "Rough Mithril Ring", qty = 1 }, { item = "Pure Moonstone", qty = 1 }, { item = "Aquamarine", qty = 1 }, { item = "Greater Mana Potion", qty = 2 }, { item = "Gemstone Oil", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 40x Rough Thorium Ring",
			note = "Takes you from 235 to 255. Keep them for Skyfire Jewel and Blue Starfire.",
			skill = { profession = "Jewelcrafting", from = 235, to = 255 },
			craft = { item = "Rough Thorium Ring", count = 40 },
			reagents = { { item = "Thorium Bar", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Dense Gritted Paper",
			note = "Takes you from 255 to 264.",
			skill = { profession = "Jewelcrafting", from = 255, to = 264 },
			craft = { item = "Dense Gritted Paper", count = 10 },
			reagents = { { item = "Runecloth", qty = 3 }, { item = "Dense Stone", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Skyfire Jewel",
			note = "Takes you from 264 to 265.",
			skill = { profession = "Jewelcrafting", from = 264, to = 265 },
			craft = { item = "Skyfire Jewel", count = 1 },
			reagents = { { item = "Rough Thorium Ring", qty = 1 }, { item = "Pure Moonstone", qty = 3 }, { item = "Elemental Air", qty = 3 } },
			source = "Plans: Skyfire Jewel",
		},
		{
			type = "USE",
			title = "Craft 80x Blue Starfire",
			note = "Takes you from 265 to 300.",
			skill = { profession = "Jewelcrafting", from = 265, to = 300 },
			craft = { item = "Blue Starfire", count = 80 },
			reagents = { { item = "Rough Thorium Ring", qty = 1 }, { item = "Pure Moonstone", qty = 1 }, { item = "Pure Moonstone", qty = 1 }, { item = "Gemstone Oil", qty = 1 } },
			source = "Plans: Blue Starfire",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Jewelcrafting is maxed at 300.",
		},
	},
})
