-- Leatherworking (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Leatherworking route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Leatherworking.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Leatherworking (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Leatherworking (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 396 crafts in total). For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Leatherworking needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Leatherworking (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Shandlar Thethis (Alah'Thalas), Adele Fielder (Elwynn Forest), Darianna (Darnassus), Gretta Finespindle (Ironforge).",
			faction = "Alliance",
			rank = { profession = "Leatherworking", cap = 75 },
			npcs = { "Shandlar Thethis", "Adele Fielder", "Darianna", "Gretta Finespindle" },
		},
		{
			type = "TRAIN",
			title = "Learn Leatherworking (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Zantiki (The Barrens), Chaw Stronghide (Mulgore), Dan Golthas (Undercity), Mak (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Leatherworking", cap = 75 },
			npcs = { "Zantiki", "Chaw Stronghide", "Dan Golthas", "Mak" },
		},
		{
			type = "USE",
			title = "Craft 70x Light Armor Kit",
			note = "Takes you from 1 to 50.",
			skill = { profession = "Leatherworking", from = 1, to = 50 },
			craft = { item = "Light Armor Kit", count = 70 },
			reagents = { { item = "Light Leather", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Leatherworking needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Leatherworking (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Shandlar Thethis (Alah'Thalas), Faldron (Darnassus), Fimble Finespindle (Ironforge), Simon Tanner (Stormwind City).",
			faction = "Alliance",
			rank = { profession = "Leatherworking", cap = 150 },
			npcs = { "Shandlar Thethis", "Faldron", "Fimble Finespindle", "Simon Tanner" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Leatherworking (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Arthur Moore (Undercity), Brawn (Stranglethorn Vale), Karolek (Orgrimmar), Tarn (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Leatherworking", cap = 150 },
			npcs = { "Arthur Moore", "Brawn", "Karolek", "Tarn" },
		},
		{
			type = "USE",
			title = "Craft 6x Light Armor Kit",
			note = "Takes you from 50 to 54.",
			skill = { profession = "Leatherworking", from = 50, to = 54 },
			craft = { item = "Light Armor Kit", count = 6 },
			reagents = { { item = "Light Leather", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Small Leather Ammo Pouch",
			note = "Takes you from 54 to 55.",
			skill = { profession = "Leatherworking", from = 54, to = 55 },
			craft = { item = "Small Leather Ammo Pouch", count = 1 },
			reagents = { { item = "Light Leather", qty = 3 }, { item = "Coarse Thread", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 51x Embossed Leather Gloves",
			note = "Takes you from 55 to 100.",
			skill = { profession = "Leatherworking", from = 55, to = 100 },
			craft = { item = "Embossed Leather Gloves", count = 51 },
			reagents = { { item = "Light Leather", qty = 3 }, { item = "Coarse Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Medium Leather",
			note = "Takes you from 100 to 105. Keep them for Dark Leather Pants and Heavy Leather.",
			skill = { profession = "Leatherworking", from = 100, to = 105 },
			craft = { item = "Medium Leather", count = 7 },
			reagents = { { item = "Light Leather", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 13x Fine Leather Belt",
			note = "Takes you from 105 to 117.",
			skill = { profession = "Leatherworking", from = 105, to = 117 },
			craft = { item = "Fine Leather Belt", count = 13 },
			reagents = { { item = "Light Leather", qty = 6 }, { item = "Coarse Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 16x Fine Leather Boots",
			note = "Takes you from 117 to 125.",
			skill = { profession = "Leatherworking", from = 117, to = 125 },
			craft = { item = "Fine Leather Boots", count = 16 },
			reagents = { { item = "Light Leather", qty = 7 }, { item = "Coarse Thread", qty = 2 } },
			source = "Pattern: Fine Leather Boots",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Leatherworking needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Leatherworking (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Telonis (Darnassus), Peter Galen (Azshara), Master Craftsman T'kalpa (Moonwhisper Coast), Sarah Tanner (Searing Gorge).",
			faction = "Alliance",
			rank = { profession = "Leatherworking", cap = 225 },
			npcs = { "Telonis", "Peter Galen", "Master Craftsman T'kalpa", "Sarah Tanner" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Leatherworking (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Thorkaf Dragoneye (Badlands), Master Craftsman T'kalpa (Moonwhisper Coast), Brumn Winterhoof (Arathi Highlands), Una (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Leatherworking", cap = 225 },
			npcs = { "Thorkaf Dragoneye", "Master Craftsman T'kalpa", "Brumn Winterhoof", "Una" },
		},
		{
			type = "USE",
			title = "Craft 39x Fine Leather Boots",
			note = "Takes you from 125 to 145.",
			skill = { profession = "Leatherworking", from = 125, to = 145 },
			craft = { item = "Fine Leather Boots", count = 39 },
			reagents = { { item = "Light Leather", qty = 7 }, { item = "Coarse Thread", qty = 2 } },
			source = "Pattern: Fine Leather Boots",
		},
		{
			type = "USE",
			title = "Craft 7x Dark Leather Pants",
			note = "Takes you from 145 to 150.",
			skill = { profession = "Leatherworking", from = 145, to = 150 },
			craft = { item = "Dark Leather Pants", count = 7 },
			reagents = { { item = "Medium Leather", qty = 12 }, { item = "Gray Dye", qty = 1 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Heavy Leather",
			note = "Takes you from 150 to 154. Keep them for Raptor Hide Belt and Guardian Gloves.",
			skill = { profession = "Leatherworking", from = 150, to = 154 },
			craft = { item = "Heavy Leather", count = 5 },
			reagents = { { item = "Medium Leather", qty = 5 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 32x Cured Heavy Hide",
			note = "Takes you from 154 to 169. Keep them for Guardian Gloves.",
			skill = { profession = "Leatherworking", from = 154, to = 169 },
			craft = { item = "Cured Heavy Hide", count = 32 },
			reagents = { { item = "Heavy Hide", qty = 1 }, { item = "Salt", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 22x Raptor Hide Belt",
			note = "Takes you from 169 to 190.",
			skill = { profession = "Leatherworking", from = 169, to = 190 },
			craft = { item = "Raptor Hide Belt", count = 22 },
			reagents = { { item = "Raptor Hide", qty = 4 }, { item = "Heavy Leather", qty = 4 }, { item = "Fine Thread", qty = 2 } },
			source = "Pattern: Raptor Hide Belt",
		},
		{
			type = "USE",
			title = "Craft 11x Guardian Gloves",
			note = "Takes you from 190 to 200.",
			skill = { profession = "Leatherworking", from = 190, to = 200 },
			craft = { item = "Guardian Gloves", count = 11 },
			reagents = { { item = "Heavy Leather", qty = 4 }, { item = "Cured Heavy Hide", qty = 1 }, { item = "Silken Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Leatherworking needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Leatherworking (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Drakk Stonehand (The Hinterlands), Caryssia Moonhunter (Feralas), Peter Galen (Azshara), Telonis (Darnassus).",
			faction = "Alliance",
			rank = { profession = "Leatherworking", cap = 300 },
			npcs = { "Drakk Stonehand", "Caryssia Moonhunter", "Peter Galen", "Telonis" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Leatherworking (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Hahrana Ironhide (Feralas), Raz'Dag (Arathi Highlands), Se'Jib (Stranglethorn Vale), Una (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Leatherworking", cap = 300 },
			npcs = { "Hahrana Ironhide", "Raz'Dag", "Se'Jib", "Una" },
		},
		{
			type = "USE",
			title = "Craft 21x Guardian Gloves",
			note = "Takes you from 200 to 219.",
			skill = { profession = "Leatherworking", from = 200, to = 219 },
			craft = { item = "Guardian Gloves", count = 21 },
			reagents = { { item = "Heavy Leather", qty = 4 }, { item = "Cured Heavy Hide", qty = 1 }, { item = "Silken Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 7x Thick Armor Kit",
			note = "Takes you from 219 to 225.",
			skill = { profession = "Leatherworking", from = 219, to = 225 },
			craft = { item = "Thick Armor Kit", count = 7 },
			reagents = { { item = "Thick Leather", qty = 5 }, { item = "Silken Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 18x Nightscape Headband",
			note = "Takes you from 225 to 237.",
			skill = { profession = "Leatherworking", from = 225, to = 237 },
			craft = { item = "Nightscape Headband", count = 18 },
			reagents = { { item = "Thick Leather", qty = 5 }, { item = "Silken Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Wild Leather Shoulders",
			note = "Takes you from 237 to 245.",
			skill = { profession = "Leatherworking", from = 237, to = 245 },
			craft = { item = "Wild Leather Shoulders", count = 9 },
			reagents = { { item = "Thick Leather", qty = 10 }, { item = "Wildvine", qty = 1 }, { item = "Cured Thick Hide", qty = 1 } },
		},
		{
			type = "USE",
			title = "Craft 6x Wild Leather Helmet",
			note = "Takes you from 245 to 250.",
			skill = { profession = "Leatherworking", from = 245, to = 250 },
			craft = { item = "Wild Leather Helmet", count = 6 },
			reagents = { { item = "Thick Leather", qty = 10 }, { item = "Wildvine", qty = 2 }, { item = "Cured Thick Hide", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Nightscape Pants",
			note = "Takes you from 250 to 257.",
			skill = { profession = "Leatherworking", from = 250, to = 257 },
			craft = { item = "Nightscape Pants", count = 9 },
			reagents = { { item = "Thick Leather", qty = 14 }, { item = "Silken Thread", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 3x Wild Leather Boots",
			note = "Takes you from 257 to 260.",
			skill = { profession = "Leatherworking", from = 257, to = 260 },
			craft = { item = "Wild Leather Boots", count = 3 },
			reagents = { { item = "Thick Leather", qty = 14 }, { item = "Wildvine", qty = 4 }, { item = "Cured Thick Hide", qty = 2 } },
		},
		{
			type = "USE",
			title = "Craft 24x Wicked Leather Gauntlets",
			note = "Takes you from 260 to 283.",
			skill = { profession = "Leatherworking", from = 260, to = 283 },
			craft = { item = "Wicked Leather Gauntlets", count = 24 },
			reagents = { { item = "Rugged Leather", qty = 8 }, { item = "Black Dye", qty = 1 }, { item = "Rune Thread", qty = 1 } },
			source = "Pattern: Wicked Leather Gauntlets",
		},
		{
			type = "USE",
			title = "Craft 7x Wicked Leather Bracers",
			note = "Takes you from 283 to 289.",
			skill = { profession = "Leatherworking", from = 283, to = 289 },
			craft = { item = "Wicked Leather Bracers", count = 7 },
			reagents = { { item = "Rugged Leather", qty = 8 }, { item = "Black Dye", qty = 1 }, { item = "Rune Thread", qty = 1 } },
			source = "Pattern: Wicked Leather Bracers",
		},
		{
			type = "USE",
			title = "Craft 4x Heavy Scorpid Belt",
			note = "Takes you from 289 to 293.",
			skill = { profession = "Leatherworking", from = 289, to = 293 },
			craft = { item = "Heavy Scorpid Belt", count = 4 },
			reagents = { { item = "Rugged Leather", qty = 6 }, { item = "Heavy Scorpid Scale", qty = 8 }, { item = "Rune Thread", qty = 1 } },
			source = "Pattern: Heavy Scorpid Belt",
		},
		{
			type = "USE",
			title = "Craft 8x Runic Leather Bracers",
			note = "Takes you from 293 to 300.",
			skill = { profession = "Leatherworking", from = 293, to = 300 },
			craft = { item = "Runic Leather Bracers", count = 8 },
			reagents = { { item = "Rugged Leather", qty = 6 }, { item = "Black Pearl", qty = 1 }, { item = "Runecloth", qty = 6 }, { item = "Rune Thread", qty = 1 } },
			source = "Pattern: Runic Leather Bracers",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Leatherworking is maxed at 300.",
		},
	},
})
