-- Mining (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/Professions_Reference.docx
-- Where to mine: Tools/data/gathering.json -- pfQuest's ore nodes and
--            CMaNGOS classic-db's vein loot, via Tools/build/gathering_guides.py
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Mining (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Mining (1-300)",
			note = "A low-cost 1-300 route. Craft counts are estimates (about 108 crafts in total).",
		},
		{
			type = "NOTE",
			title = "Before you start",
			note = "Totals assume you follow the main route below without alternatives.",
		},
		{
			type = "TRAIN",
			title = "Learn Mining (Apprentice)",
			note = "Costs 5 copper. Trainers: Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brindel Morningsun (Alah'Thalas), Brock Stoneseeker (Loch Modan).",
			faction = "Alliance",
			rank = { profession = "Mining", cap = 75 },
			npcs = { "Dank Drizzlecut", "Yarr Hammerstone", "Brindel Morningsun", "Brock Stoneseeker" },
		},
		{
			type = "TRAIN",
			title = "Learn Mining (Apprentice)",
			note = "Costs 5 copper. Trainers: Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Mining", cap = 75 },
			npcs = { "Tantaz Coppermud", "Krunn", "Johan Focht", "Brek Stonehoof" },
		},
		{
			type = "USE",
			title = "Craft 24x Copper Bar",
			note = "Takes you from 1 to 70. Copper Ore: mine Copper Veins, most in Elwynn Forest (1-12), Darkshore (12-24) and Westfall (12-17). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 1, to = 70 },
			craft = { item = "Copper Bar", count = 24 },
			reagents = { { item = "Copper Ore", qty = 1 } },
			source = "Auto-learned",
		},
		{
			type = "USE",
			title = "Craft 24x Copper Bar",
			note = "Takes you from 1 to 70. Copper Ore: mine Copper Veins, most in The Barrens (12-25), Durotar (1-12) and Silverpine Forest (12-20). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 1, to = 70 },
			craft = { item = "Copper Bar", count = 24 },
			reagents = { { item = "Copper Ore", qty = 1 } },
			source = "Auto-learned",
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Mining (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brock Stoneseeker (Loch Modan), Matt Johnson (Duskwood).",
			faction = "Alliance",
			rank = { profession = "Mining", cap = 150 },
			npcs = { "Dank Drizzlecut", "Yarr Hammerstone", "Brock Stoneseeker", "Matt Johnson" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Mining (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Mining", cap = 150 },
			npcs = { "Tantaz Coppermud", "Krunn", "Johan Focht", "Brek Stonehoof" },
		},
		{
			type = "USE",
			title = "Craft 26x Bronze Bar",
			note = "Takes you from 70 to 90. Copper Ore: mine Copper Veins, most in Elwynn Forest (1-12), Darkshore (12-24) and Westfall (12-17); Tin Ore: mine Tin Veins, most in Wetlands (24-31), Stonetalon Mountains (22-23) and Westfall (12-17). Or buy them.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 70, to = 90 },
			craft = { item = "Bronze Bar", count = 26 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Tin Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 26x Bronze Bar",
			note = "Takes you from 70 to 90. Copper Ore: mine Copper Veins, most in The Barrens (12-25), Durotar (1-12) and Silverpine Forest (12-20); Tin Ore: mine Tin Veins, most in The Barrens (12-25), Stonetalon Mountains (20-27) and Ashenvale (26-27). Or buy them.",
			faction = "Horde",
			skill = { profession = "Mining", from = 70, to = 90 },
			craft = { item = "Bronze Bar", count = 26 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Tin Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Silver Bar",
			note = "Takes you from 90 to 113. Silver Ore: mine Silver Veins, most in Ashenvale (21-30), Wetlands (24-31) and Northwind (28-34). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 90, to = 113 },
			craft = { item = "Silver Bar", count = 10 },
			reagents = { { item = "Silver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Silver Bar",
			note = "Takes you from 90 to 113. Silver Ore: mine Silver Veins, most in Ashenvale (26-27), Hillsbrad Foothills (29-30) and The Barrens (12-25). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 90, to = 113 },
			craft = { item = "Silver Bar", count = 10 },
			reagents = { { item = "Silver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Bronze Bar",
			note = "Takes you from 113 to 115. Copper Ore: mine Copper Veins, most in Elwynn Forest (1-12), Darkshore (12-24) and Westfall (12-17); Tin Ore: mine Tin Veins, most in Wetlands (24-31), Stonetalon Mountains (22-23) and Westfall (12-17). Or buy them.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 113, to = 115 },
			craft = { item = "Bronze Bar", count = 4 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Tin Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Bronze Bar",
			note = "Takes you from 113 to 115. Copper Ore: mine Copper Veins, most in The Barrens (12-25), Durotar (1-12) and Silverpine Forest (12-20); Tin Ore: mine Tin Veins, most in The Barrens (12-25), Stonetalon Mountains (20-27) and Ashenvale (26-27). Or buy them.",
			faction = "Horde",
			skill = { profession = "Mining", from = 113, to = 115 },
			craft = { item = "Bronze Bar", count = 4 },
			reagents = { { item = "Copper Bar", qty = 1 }, { item = "Tin Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Silver Bar",
			note = "Takes you from 115 to 125. Silver Ore: mine Silver Veins, most in Ashenvale (21-30), Wetlands (24-31) and Northwind (28-34). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 115, to = 125 },
			craft = { item = "Silver Bar", count = 20 },
			reagents = { { item = "Silver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Silver Bar",
			note = "Takes you from 115 to 125. Silver Ore: mine Silver Veins, most in Ashenvale (26-27), Hillsbrad Foothills (29-30) and The Barrens (12-25). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 115, to = 125 },
			craft = { item = "Silver Bar", count = 20 },
			reagents = { { item = "Silver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Iron Bar",
			note = "Takes you from 125 to 140. Iron Ore: mine Iron Deposits, most in Arathi Highlands (37-38), Grim Reaches (33-38) and Thousand Needles (33-34). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 125, to = 140 },
			craft = { item = "Iron Bar", count = 5 },
			reagents = { { item = "Iron Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Iron Bar",
			note = "Takes you from 125 to 140. Iron Ore: mine Iron Deposits, most in Arathi Highlands (30-38), Grim Reaches (33-38) and Thousand Needles (25-38). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 125, to = 140 },
			craft = { item = "Iron Bar", count = 5 },
			reagents = { { item = "Iron Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Expert Mining (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brock Stoneseeker (Loch Modan), Matt Johnson (Duskwood).",
			faction = "Alliance",
			rank = { profession = "Mining", cap = 225 },
			npcs = { "Dank Drizzlecut", "Yarr Hammerstone", "Brock Stoneseeker", "Matt Johnson" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Mining (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Mining", cap = 225 },
			npcs = { "Tantaz Coppermud", "Krunn", "Johan Focht", "Brek Stonehoof" },
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Iron Veins / Gold Veins)",
			note = "Takes you from 140 to 155. No learnable smelting recipe covers this range in the database. Best: Arathi Highlands (37-38): Iron Deposit, Tin Vein; Grim Reaches (33-38): Iron Deposit, Tin Vein; Thousand Needles (33-34): Iron Deposit, Tin Vein.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 140, to = 155 },
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Iron Veins / Gold Veins)",
			note = "Takes you from 140 to 155. No learnable smelting recipe covers this range in the database. Best: Arathi Highlands (30-38): Iron Deposit, Tin Vein; Grim Reaches (33-38): Iron Deposit, Tin Vein; Thousand Needles (25-38): Iron Deposit, Tin Vein.",
			faction = "Horde",
			skill = { profession = "Mining", from = 140, to = 155 },
		},
		{
			type = "USE",
			title = "Craft 15x Gold Bar",
			note = "Takes you from 155 to 185. Gold Ore: mine Gold Veins, most in Tanaris (43-50), Stranglethorn Vale (32-47) and Thousand Needles (33-34). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 155, to = 185 },
			craft = { item = "Gold Bar", count = 15 },
			reagents = { { item = "Gold Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 15x Gold Bar",
			note = "Takes you from 155 to 185. Gold Ore: mine Gold Veins, most in Tanaris (44-50), Stranglethorn Vale (30-47) and Thousand Needles (25-38). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 155, to = 185 },
			craft = { item = "Gold Bar", count = 15 },
			reagents = { { item = "Gold Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Artisan Mining (Cap 300)",
			note = "Needs skill 200; costs 5 gold. Trainers: Dank Drizzlecut (Dun Morogh), Yarr Hammerstone (Dun Morogh), Brock Stoneseeker (Loch Modan), Matt Johnson (Duskwood).",
			faction = "Alliance",
			rank = { profession = "Mining", cap = 300 },
			npcs = { "Dank Drizzlecut", "Yarr Hammerstone", "Brock Stoneseeker", "Matt Johnson" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Mining (Cap 300)",
			note = "Needs skill 200; costs 5 gold. Trainers: Tantaz Coppermud (Blackstone Island), Krunn (Durotar), Johan Focht (Silverpine Forest), Brek Stonehoof (Thunder Bluff).",
			faction = "Horde",
			rank = { profession = "Mining", cap = 300 },
			npcs = { "Tantaz Coppermud", "Krunn", "Johan Focht", "Brek Stonehoof" },
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Mithril Veins)",
			note = "Takes you from 185 to 230. No learnable smelting recipe covers this range in the database. Best: Tanaris (43-50): Gold Vein, Mithril Deposit; Arathi Highlands (37-38): Mithril Deposit, Iron Deposit; Thousand Needles (33-34): Gold Vein, Iron Deposit.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 185, to = 230 },
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Mithril Veins)",
			note = "Takes you from 185 to 230. No learnable smelting recipe covers this range in the database. Best: Tanaris (44-50): Gold Vein, Mithril Deposit; Arathi Highlands (30-38): Mithril Deposit, Iron Deposit; Thousand Needles (25-38): Gold Vein, Iron Deposit.",
			faction = "Horde",
			skill = { profession = "Mining", from = 185, to = 230 },
		},
		{
			type = "USE",
			title = "Craft 2x Truesilver Bar",
			note = "Takes you from 230 to 231. Truesilver Ore: mine Truesilver Deposits, most in Burning Steppes (55-56), Felwood (53-56) and Searing Gorge (47-48). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 230, to = 231 },
			craft = { item = "Truesilver Bar", count = 2 },
			reagents = { { item = "Truesilver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 2x Truesilver Bar",
			note = "Takes you from 230 to 231. Truesilver Ore: mine Truesilver Deposits, most in Burning Steppes (53-54), Felwood (54-56) and Searing Gorge (47-48). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 230, to = 231 },
			craft = { item = "Truesilver Bar", count = 2 },
			reagents = { { item = "Truesilver Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Truesilver Veins / Small Thorium Veins)",
			note = "Takes you from 231 to 250. No learnable smelting recipe covers this range in the database. Best: Burning Steppes (55-56): Truesilver Deposit, Dark Iron Deposit; Searing Gorge (47-48): Dark Iron Deposit, Truesilver Deposit; Felwood (53-56): Truesilver Deposit, Mithril Deposit.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 231, to = 250 },
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Truesilver Veins / Small Thorium Veins)",
			note = "Takes you from 231 to 250. No learnable smelting recipe covers this range in the database. Best: Burning Steppes (53-54): Truesilver Deposit, Dark Iron Deposit; Searing Gorge (47-48): Dark Iron Deposit, Truesilver Deposit; Felwood (54-56): Truesilver Deposit, Mithril Deposit.",
			faction = "Horde",
			skill = { profession = "Mining", from = 231, to = 250 },
		},
		{
			type = "USE",
			title = "Craft 2x Thorium Bar",
			note = "Takes you from 250 to 251. Thorium Ore: mine Small Thorium Veins, most in Burning Steppes (55-56), Winterspring (54-60) and Un'Goro Crater (51-52). Or buy it.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 250, to = 251 },
			craft = { item = "Thorium Bar", count = 2 },
			reagents = { { item = "Thorium Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 2x Thorium Bar",
			note = "Takes you from 250 to 251. Thorium Ore: mine Small Thorium Veins, most in Burning Steppes (53-54), Winterspring (54-60) and Un'Goro Crater (51-53). Or buy it.",
			faction = "Horde",
			skill = { profession = "Mining", from = 250, to = 251 },
			craft = { item = "Thorium Bar", count = 2 },
			reagents = { { item = "Thorium Ore", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Rich Thorium Veins)",
			note = "Takes you from 251 to 300. No learnable smelting recipe covers this range in the database. Best: Burning Steppes (55-56): Small Thorium Vein, Truesilver Deposit; Felwood (53-56): Truesilver Deposit, Small Thorium Vein; Un'Goro Crater (51-52): Small Thorium Vein, Truesilver Deposit.",
			faction = "Alliance",
			skill = { profession = "Mining", from = 251, to = 300 },
		},
		{
			type = "GRIND",
			title = "Open-world node mining (Rich Thorium Veins)",
			note = "Takes you from 251 to 300. No learnable smelting recipe covers this range in the database. Best: Burning Steppes (53-54): Small Thorium Vein, Truesilver Deposit; Felwood (54-56): Truesilver Deposit, Small Thorium Vein; Un'Goro Crater (51-53): Small Thorium Vein, Truesilver Deposit.",
			faction = "Horde",
			skill = { profession = "Mining", from = 251, to = 300 },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Mining is maxed at 300.",
		},
	},
})
