-- Skinning (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    Tools/data/gathering.json -- pfQuest's gathering nodes (with
--            pfQuest-turtle) and CMaNGOS classic-db's creatures, fishing
--            skill, trainers, book and quest, extracted by
--            Tools/build/build_gathering.py; zone sides and levels from this
--            addon's own zone guides
-- Generator: Tools/build/convert_professions.py, via Tools/build/gathering_guides.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Skinning (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Skinning (1-300)",
			note = "Where to skin at each skill band: the beasts that can raise your skill there, and the zones with most of them (normal creatures only). Zones show the levels this addon's guides spend there.",
		},
		{
			type = "TRAIN",
			title = "Learn Skinning (Apprentice)",
			note = "Costs 10 copper. Trainers: Balthus Stoneflayer (Ironforge), Maris Granger (Stormwind City), Eladriel (Teldrassil), Helene Peltskinner (Elwynn Forest), Jayla (Ashenvale), Radnaal Maneweaver (Teldrassil), Wilma Ranthal (Redridge Mountains).",
			faction = "Alliance",
			rank = { profession = "Skinning", cap = 75 },
			npcs = { "Balthus Stoneflayer", "Maris Granger", "Eladriel", "Helene Peltskinner", "Jayla", "Radnaal Maneweaver", "Wilma Ranthal" },
		},
		{
			type = "TRAIN",
			title = "Learn Skinning (Apprentice)",
			note = "Costs 10 copper. Trainers: Killian Hagey (Undercity), Thuwd (Orgrimmar), Dranh (The Barrens), Kulleg Stonehorn (Feralas), Malux (Desolace), Mooranta (Mulgore), Rand Rhobart (Tirisfal Glades), Yonn Deepcut (Mulgore).",
			faction = "Horde",
			rank = { profession = "Skinning", cap = 75 },
			npcs = { "Killian Hagey", "Thuwd", "Dranh", "Kulleg Stonehorn", "Malux", "Mooranta", "Rand Rhobart", "Yonn Deepcut" },
		},
		{
			type = "GRIND",
			title = "Skin to 25: levels 1-10 beasts",
			note = "Takes you from 1 to 25. Skin beasts of levels 1-10. Best: Dun Morogh (1-12), Elwynn Forest (1-12), Teldrassil (1-12).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 1, to = 25 },
		},
		{
			type = "GRIND",
			title = "Skin to 25: levels 1-10 beasts",
			note = "Takes you from 1 to 25. Skin beasts of levels 1-10. Best: Mulgore (1-12), Durotar (1-12), Tirisfal Glades (1-12).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 1, to = 25 },
		},
		{
			type = "GRIND",
			title = "Skin to 50: levels 1-12 beasts",
			note = "Takes you from 25 to 50. Skin beasts of levels 1-12. Best: Dun Morogh (1-12), Elwynn Forest (1-12), Darkshore (12-24).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 25, to = 50 },
		},
		{
			type = "GRIND",
			title = "Skin to 50: levels 1-12 beasts",
			note = "Takes you from 25 to 50. Skin beasts of levels 1-12. Best: Mulgore (1-12), Durotar (1-12), The Barrens (12-25).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 25, to = 50 },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Skinning (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Balthus Stoneflayer (Ironforge), Maris Granger (Stormwind City), Eladriel (Teldrassil), Helene Peltskinner (Elwynn Forest), Jayla (Ashenvale), Radnaal Maneweaver (Teldrassil), Wilma Ranthal (Redridge Mountains).",
			faction = "Alliance",
			rank = { profession = "Skinning", cap = 150 },
			npcs = { "Balthus Stoneflayer", "Maris Granger", "Eladriel", "Helene Peltskinner", "Jayla", "Radnaal Maneweaver", "Wilma Ranthal" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Skinning (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Killian Hagey (Undercity), Thuwd (Orgrimmar), Dranh (The Barrens), Kulleg Stonehorn (Feralas), Malux (Desolace), Mooranta (Mulgore), Rand Rhobart (Tirisfal Glades), Yonn Deepcut (Mulgore).",
			faction = "Horde",
			rank = { profession = "Skinning", cap = 150 },
			npcs = { "Killian Hagey", "Thuwd", "Dranh", "Kulleg Stonehorn", "Malux", "Mooranta", "Rand Rhobart", "Yonn Deepcut" },
		},
		{
			type = "GRIND",
			title = "Skin to 75: levels 13-15 beasts",
			note = "Takes you from 50 to 75. Skin beasts of levels 13-15. Best: Darkshore (12-24), Loch Modan (17-18), Westfall (12-17).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 50, to = 75 },
		},
		{
			type = "GRIND",
			title = "Skin to 75: levels 13-15 beasts",
			note = "Takes you from 50 to 75. Skin beasts of levels 13-15. Best: The Barrens (12-25), Silverpine Forest (12-20), Durotar (1-12).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 50, to = 75 },
		},
		{
			type = "GRIND",
			title = "Skin to 100: levels 16-17 beasts",
			note = "Takes you from 75 to 100. Skin beasts of levels 16-17. Best: Darkshore (12-24), Redridge Mountains (18-28), Loch Modan (17-18).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 75, to = 100 },
		},
		{
			type = "GRIND",
			title = "Skin to 100: levels 16-17 beasts",
			note = "Takes you from 75 to 100. Skin beasts of levels 16-17. Best: The Barrens (12-25), Stonetalon Mountains (20-27), Silverpine Forest (12-20).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 75, to = 100 },
		},
		{
			type = "GRIND",
			title = "Skin to 125: levels 18-20 beasts",
			note = "Takes you from 100 to 125. Skin beasts of levels 18-20. Best: Ashenvale (21-30), Darkshore (12-24), Stonetalon Mountains (22-23).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 100, to = 125 },
		},
		{
			type = "GRIND",
			title = "Skin to 125: levels 18-20 beasts",
			note = "Takes you from 100 to 125. Skin beasts of levels 18-20. Best: The Barrens (12-25), Stonetalon Mountains (20-27).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 100, to = 125 },
		},
		{
			type = "TRAIN",
			title = "Train Expert Skinning (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Balthus Stoneflayer (Ironforge), Maris Granger (Stormwind City), Eladriel (Teldrassil), Helene Peltskinner (Elwynn Forest), Jayla (Ashenvale), Radnaal Maneweaver (Teldrassil), Wilma Ranthal (Redridge Mountains).",
			faction = "Alliance",
			rank = { profession = "Skinning", cap = 225 },
			npcs = { "Balthus Stoneflayer", "Maris Granger", "Eladriel", "Helene Peltskinner", "Jayla", "Radnaal Maneweaver", "Wilma Ranthal" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Skinning (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Killian Hagey (Undercity), Thuwd (Orgrimmar), Dranh (The Barrens), Kulleg Stonehorn (Feralas), Malux (Desolace), Mooranta (Mulgore), Rand Rhobart (Tirisfal Glades), Yonn Deepcut (Mulgore).",
			faction = "Horde",
			rank = { profession = "Skinning", cap = 225 },
			npcs = { "Killian Hagey", "Thuwd", "Dranh", "Kulleg Stonehorn", "Malux", "Mooranta", "Rand Rhobart", "Yonn Deepcut" },
		},
		{
			type = "GRIND",
			title = "Skin to 150: levels 21-25 beasts",
			note = "Takes you from 125 to 150. Skin beasts of levels 21-25. Best: Wetlands (24-31), Ashenvale (21-30), Stonetalon Mountains (22-23).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 125, to = 150 },
		},
		{
			type = "GRIND",
			title = "Skin to 150: levels 21-25 beasts",
			note = "Takes you from 125 to 150. Skin beasts of levels 21-25. Best: Ashenvale (26-27), Hillsbrad Foothills (29-30), Stonetalon Mountains (20-27).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 125, to = 150 },
		},
		{
			type = "GRIND",
			title = "Skin to 175: levels 26-30 beasts",
			note = "Takes you from 150 to 175. Skin beasts of levels 26-30. Best: Thousand Needles (33-34), Duskwood (28-29), Ashenvale (21-30).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 150, to = 175 },
		},
		{
			type = "GRIND",
			title = "Skin to 175: levels 26-30 beasts",
			note = "Takes you from 150 to 175. Skin beasts of levels 26-30. Best: Thousand Needles (25-38), Ashenvale (26-27), Arathi Highlands (30-38).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 150, to = 175 },
		},
		{
			type = "GRIND",
			title = "Skin to 200: levels 31-35 beasts",
			note = "Takes you from 175 to 200. Skin beasts of levels 31-35. Best: Desolace (34-43), Stranglethorn Vale (32-47), Dustwallow Marsh (38-39).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 175, to = 200 },
		},
		{
			type = "GRIND",
			title = "Skin to 200: levels 31-35 beasts",
			note = "Takes you from 175 to 200. Skin beasts of levels 31-35. Best: Desolace (32-44), Stranglethorn Vale (30-47), Dustwallow Marsh (38-49).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 175, to = 200 },
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Skinning needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Skinning (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Balthus Stoneflayer (Ironforge), Maris Granger (Stormwind City), Eladriel (Teldrassil), Helene Peltskinner (Elwynn Forest), Jayla (Ashenvale), Radnaal Maneweaver (Teldrassil), Wilma Ranthal (Redridge Mountains).",
			faction = "Alliance",
			rank = { profession = "Skinning", cap = 300 },
			npcs = { "Balthus Stoneflayer", "Maris Granger", "Eladriel", "Helene Peltskinner", "Jayla", "Radnaal Maneweaver", "Wilma Ranthal" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Skinning (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Killian Hagey (Undercity), Thuwd (Orgrimmar), Dranh (The Barrens), Kulleg Stonehorn (Feralas), Malux (Desolace), Mooranta (Mulgore), Rand Rhobart (Tirisfal Glades), Yonn Deepcut (Mulgore).",
			faction = "Horde",
			rank = { profession = "Skinning", cap = 300 },
			npcs = { "Killian Hagey", "Thuwd", "Dranh", "Kulleg Stonehorn", "Malux", "Mooranta", "Rand Rhobart", "Yonn Deepcut" },
		},
		{
			type = "GRIND",
			title = "Skin to 225: levels 36-40 beasts",
			note = "Takes you from 200 to 225. Skin beasts of levels 36-40. Best: Dustwallow Marsh (38-39), Stranglethorn Vale (32-47), Badlands (40-41).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 200, to = 225 },
		},
		{
			type = "GRIND",
			title = "Skin to 225: levels 36-40 beasts",
			note = "Takes you from 200 to 225. Skin beasts of levels 36-40. Best: Dustwallow Marsh (38-49), Stranglethorn Vale (30-47), Badlands (40-41).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 200, to = 225 },
		},
		{
			type = "GRIND",
			title = "Skin to 250: levels 41-45 beasts",
			note = "Takes you from 225 to 250. Skin beasts of levels 41-45. Best: Tanaris (43-50), Dustwallow Marsh (38-39), Feralas (44-49).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 225, to = 250 },
		},
		{
			type = "GRIND",
			title = "Skin to 250: levels 41-45 beasts",
			note = "Takes you from 225 to 250. Skin beasts of levels 41-45. Best: Tanaris (44-50), Dustwallow Marsh (38-49), Feralas (45-50).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 225, to = 250 },
		},
		{
			type = "GRIND",
			title = "Skin to 275: levels 46-50 beasts",
			note = "Takes you from 250 to 275. Skin beasts of levels 46-50. Best: Tanaris (43-50), Un'Goro Crater (51-52), Felwood (53-56).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 250, to = 275 },
		},
		{
			type = "GRIND",
			title = "Skin to 275: levels 46-50 beasts",
			note = "Takes you from 250 to 275. Skin beasts of levels 46-50. Best: Tanaris (44-50), Un'Goro Crater (51-53), Felwood (54-56).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 250, to = 275 },
		},
		{
			type = "GRIND",
			title = "Skin to 300: levels 51-55 beasts",
			note = "Takes you from 275 to 300. Skin beasts of levels 51-55. Best: Azshara (46-53), Un'Goro Crater (51-52), Winterspring (54-60).",
			faction = "Alliance",
			skill = { profession = "Skinning", from = 275, to = 300 },
		},
		{
			type = "GRIND",
			title = "Skin to 300: levels 51-55 beasts",
			note = "Takes you from 275 to 300. Skin beasts of levels 51-55. Best: Azshara (46-50), Un'Goro Crater (51-53), Winterspring (54-60).",
			faction = "Horde",
			skill = { profession = "Skinning", from = 275, to = 300 },
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Skinning is maxed at 300.",
		},
	},
})
