-- Survival (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Survival route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Survival.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Survival (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Survival (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 558 crafts in total). Nobody was selling Simple Leaves, Clam Meat, Bright Wood, Long Tail Feather, Tangy Clam Meat, Shade Wood, Zesty Clam Meat, Delicate Feather and Star Wood then, so they were costed at 3 times what a merchant pays. For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "TRAIN",
			title = "Learn Survival (Apprentice)",
			note = "Costs 5 copper. Trainers: Eissinn Cragbelly (Ironforge), Krennan Wildberry (Stormwind City), Rufus Hardwick (Stranglethorn Vale), Nallaeth (Darnassus).",
			faction = "Alliance",
			rank = { profession = "Survival", cap = 75 },
			npcs = { "Eissinn Cragbelly", "Krennan Wildberry", "Rufus Hardwick", "Nallaeth" },
		},
		{
			type = "TRAIN",
			title = "Learn Survival (Apprentice)",
			note = "Costs 5 copper. Trainers: Brakan (Orgrimmar), Rufus Hardwick (Stranglethorn Vale), Swampwalker Krug (Swamp of Sorrows), Cynthessa Grimblood (Undercity).",
			faction = "Horde",
			rank = { profession = "Survival", cap = 75 },
			npcs = { "Brakan", "Rufus Hardwick", "Swampwalker Krug", "Cynthessa Grimblood" },
		},
		{
			type = "USE",
			title = "Craft 23x Dim Torch",
			note = "Takes you from 1 to 15.",
			skill = { profession = "Survival", from = 1, to = 15 },
			craft = { item = "Dim Torch", count = 23 },
			reagents = { { item = "Unlit Poor Torch", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 47x Survivalist's Skinning Knife",
			note = "Takes you from 15 to 50.",
			skill = { profession = "Survival", from = 15, to = 50 },
			craft = { item = "Survivalist's Skinning Knife", count = 47 },
			reagents = { { item = "Rough Stone", qty = 2 }, { item = "Coarse Thread", qty = 1 }, { item = "Light Leather", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Survival (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Eissinn Cragbelly (Ironforge), Krennan Wildberry (Stormwind City), Nallaeth (Darnassus), Dyrohrinn Boulderhorn (Dun Morogh).",
			faction = "Alliance",
			rank = { profession = "Survival", cap = 150 },
			npcs = { "Eissinn Cragbelly", "Krennan Wildberry", "Nallaeth", "Dyrohrinn Boulderhorn" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Survival (Cap 150)",
			note = "Needs skill 50; costs 5 silver. Trainers: Brakan (Orgrimmar), Cynthessa Grimblood (Undercity), Feebeld (Blackstone Island), Karolina Cloven (Tirisfal Glades).",
			faction = "Horde",
			rank = { profession = "Survival", cap = 150 },
			npcs = { "Brakan", "Cynthessa Grimblood", "Feebeld", "Karolina Cloven" },
		},
		{
			type = "USE",
			title = "Craft 56x Weak Healing Salve",
			note = "Takes you from 50 to 87.",
			skill = { profession = "Survival", from = 50, to = 87 },
			craft = { item = "Weak Healing Salve", count = 56 },
			reagents = { { item = "Refreshing Spring Water", qty = 1 }, { item = "Remedy Herbs", qty = 2 }, { item = "Simple Leaves", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 25x Gardening Gloves",
			note = "Takes you from 87 to 100.",
			skill = { profession = "Survival", from = 87, to = 100 },
			craft = { item = "Gardening Gloves", count = 25 },
			reagents = { { item = "Light Leather", qty = 4 }, { item = "Coarse Thread", qty = 2 }, { item = "Peacebloom", qty = 6 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 28x Simple Fishing Lure",
			note = "Takes you from 100 to 125. Keep them for Blackmouth Fishing Trap.",
			skill = { profession = "Survival", from = 100, to = 125 },
			craft = { item = "Simple Fishing Lure", count = 28 },
			reagents = { { item = "Clam Meat", qty = 1 }, { item = "Remedy Herbs", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Expert Survival (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Rufus Hardwick (Stranglethorn Vale), Nerean Stagtree (Desolace), Eissinn Cragbelly (Ironforge), Krennan Wildberry (Stormwind City).",
			faction = "Alliance",
			rank = { profession = "Survival", cap = 225 },
			npcs = { "Rufus Hardwick", "Nerean Stagtree", "Eissinn Cragbelly", "Krennan Wildberry" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Survival (Cap 225)",
			note = "Needs skill 125; costs 50 silver. Trainers: Rufus Hardwick (Stranglethorn Vale), Swampwalker Krug (Swamp of Sorrows), Brakan (Orgrimmar), Cynthessa Grimblood (Undercity).",
			faction = "Horde",
			rank = { profession = "Survival", cap = 225 },
			npcs = { "Rufus Hardwick", "Swampwalker Krug", "Brakan", "Cynthessa Grimblood" },
		},
		{
			type = "USE",
			title = "Craft 6x Simple Fishing Lure",
			note = "Takes you from 125 to 130. Keep them for Blackmouth Fishing Trap.",
			skill = { profession = "Survival", from = 125, to = 130 },
			craft = { item = "Simple Fishing Lure", count = 6 },
			reagents = { { item = "Clam Meat", qty = 1 }, { item = "Remedy Herbs", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 26x Sturdy Net",
			note = "Takes you from 130 to 139. Keep them for Blackmouth Fishing Trap and Stonescale Fishing Trap.",
			skill = { profession = "Survival", from = 130, to = 139 },
			craft = { item = "Sturdy Net", count = 26 },
			reagents = { { item = "Sturdy Rope", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Simple Fishing Lure",
			note = "Takes you from 139 to 140. Keep them for Blackmouth Fishing Trap.",
			skill = { profession = "Survival", from = 139, to = 140 },
			craft = { item = "Simple Fishing Lure", count = 20 },
			reagents = { { item = "Clam Meat", qty = 1 }, { item = "Remedy Herbs", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Bundle of Bright Wood Sticks",
			note = "Takes you from 140 to 142. Keep them for Blackmouth Fishing Trap and Bright Wood Arrows.",
			skill = { profession = "Survival", from = 140, to = 142 },
			craft = { item = "Bundle of Bright Wood Sticks", count = 5 },
			reagents = { { item = "Bright Wood", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Blackmouth Fishing Trap",
			note = "Takes you from 142 to 146.",
			skill = { profession = "Survival", from = 142, to = 146 },
			craft = { item = "Blackmouth Fishing Trap", count = 4 },
			reagents = { { item = "Bundle of Bright Wood Sticks", qty = 2 }, { item = "Simple Fishing Lure", qty = 1 }, { item = "Sturdy Net", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Bright Wood Arrows",
			note = "Takes you from 146 to 150.",
			skill = { profession = "Survival", from = 146, to = 150 },
			craft = { item = "Bright Wood Arrows", count = 4 },
			reagents = { { item = "Bundle of Bright Wood Sticks", qty = 1 }, { item = "Long Tail Feather", qty = 1 }, { item = "Iron Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 26x Spicy Fishing Lure",
			note = "Takes you from 150 to 175.",
			skill = { profession = "Survival", from = 150, to = 175 },
			craft = { item = "Spicy Fishing Lure", count = 26 },
			reagents = { { item = "Tangy Clam Meat", qty = 1 }, { item = "Hot Spices", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Bundle of Shade Wood Sticks",
			note = "Takes you from 175 to 184. Keep them for Vine Cutter and Shade Wood Arrows.",
			skill = { profession = "Survival", from = 175, to = 184 },
			craft = { item = "Bundle of Shade Wood Sticks", count = 9 },
			reagents = { { item = "Shade Wood", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 49x Spicy Fishing Lure",
			note = "Takes you from 184 to 190.",
			skill = { profession = "Survival", from = 184, to = 190 },
			craft = { item = "Spicy Fishing Lure", count = 49 },
			reagents = { { item = "Tangy Clam Meat", qty = 1 }, { item = "Hot Spices", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 10x Iron Lantern",
			note = "Takes you from 190 to 194.",
			skill = { profession = "Survival", from = 190, to = 194 },
			craft = { item = "Iron Lantern", count = 10 },
			reagents = { { item = "Iron Bar", qty = 2 }, { item = "Flask of Oil", qty = 4 }, { item = "Wool Cloth", qty = 5 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Sharpened Herb Sickle",
			note = "Takes you from 194 to 200.",
			skill = { profession = "Survival", from = 194, to = 200 },
			craft = { item = "Sharpened Herb Sickle", count = 6 },
			reagents = { { item = "Iron Bar", qty = 2 }, { item = "Gold Bar", qty = 1 }, { item = "Shade Wood", qty = 1 }, { item = "Heavy Leather", qty = 2 }, { item = "Handful of Copper Bolts", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "TRAIN",
			title = "Train Artisan Survival (Cap 300)",
			note = "Needs skill 200; costs 5 gold. Trainers: Rufus Hardwick (Stranglethorn Vale), Nerean Stagtree (Desolace).",
			faction = "Alliance",
			rank = { profession = "Survival", cap = 300 },
			npcs = { "Rufus Hardwick", "Nerean Stagtree" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Survival (Cap 300)",
			note = "Needs skill 200; costs 5 gold. Trainers: Rufus Hardwick (Stranglethorn Vale), Swampwalker Krug (Swamp of Sorrows).",
			faction = "Horde",
			rank = { profession = "Survival", cap = 300 },
			npcs = { "Rufus Hardwick", "Swampwalker Krug" },
		},
		{
			type = "USE",
			title = "Craft 15x Savory Fishing Lure",
			note = "Takes you from 200 to 215.",
			skill = { profession = "Survival", from = 200, to = 215 },
			craft = { item = "Savory Fishing Lure", count = 15 },
			reagents = { { item = "Zesty Clam Meat", qty = 1 }, { item = "Soothing Spices", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 2x Vine Cutter",
			note = "Takes you from 215 to 217.",
			skill = { profession = "Survival", from = 215, to = 217 },
			craft = { item = "Vine Cutter", count = 2 },
			reagents = { { item = "Mithril Bar", qty = 10 }, { item = "Solid Grinding Stone", qty = 2 }, { item = "Thick Leather", qty = 4 }, { item = "Bundle of Shade Wood Sticks", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 75x Savory Fishing Lure",
			note = "Takes you from 217 to 240.",
			skill = { profession = "Survival", from = 217, to = 240 },
			craft = { item = "Savory Fishing Lure", count = 75 },
			reagents = { { item = "Zesty Clam Meat", qty = 1 }, { item = "Soothing Spices", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 9x Shade Wood Arrows",
			note = "Takes you from 240 to 242.",
			skill = { profession = "Survival", from = 240, to = 242 },
			craft = { item = "Shade Wood Arrows", count = 9 },
			reagents = { { item = "Bundle of Shade Wood Sticks", qty = 1 }, { item = "Delicate Feather", qty = 1 }, { item = "Mithril Bar", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 8x Thick Rations Bag",
			note = "Takes you from 242 to 250.",
			skill = { profession = "Survival", from = 242, to = 250 },
			craft = { item = "Thick Rations Bag", count = 8 },
			reagents = { { item = "Thick Leather", qty = 12 }, { item = "Cured Thick Hide", qty = 2 }, { item = "Heavy Silken Thread", qty = 4 }, { item = "Mageweave Cloth", qty = 10 }, { item = "Deeprock Salt", qty = 5 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 20x Premium Fishing Lure",
			note = "Takes you from 250 to 270. Keep them for Stonescale Fishing Trap.",
			skill = { profession = "Survival", from = 250, to = 270 },
			craft = { item = "Premium Fishing Lure", count = 20 },
			reagents = { { item = "Zesty Clam Meat", qty = 2 }, { item = "Molasses Firewater", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 22x Bundle of Star Wood Sticks",
			note = "Takes you from 270 to 283. Keep them for Stonescale Fishing Trap.",
			skill = { profession = "Survival", from = 270, to = 283 },
			craft = { item = "Bundle of Star Wood Sticks", count = 22 },
			reagents = { { item = "Star Wood", qty = 5 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 52x Premium Fishing Lure",
			note = "Takes you from 283 to 290. Keep them for Stonescale Fishing Trap.",
			skill = { profession = "Survival", from = 283, to = 290 },
			craft = { item = "Premium Fishing Lure", count = 52 },
			reagents = { { item = "Zesty Clam Meat", qty = 2 }, { item = "Molasses Firewater", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 11x Stonescale Fishing Trap",
			note = "Takes you from 290 to 300.",
			skill = { profession = "Survival", from = 290, to = 300 },
			craft = { item = "Stonescale Fishing Trap", count = 11 },
			reagents = { { item = "Bundle of Star Wood Sticks", qty = 2 }, { item = "Premium Fishing Lure", qty = 1 }, { item = "Sturdy Net", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Survival is maxed at 300.",
		},
	},
})
