-- Tailoring (1-300)
--
-- GENERATED FILE -- do not edit by hand.
-- Source:    CraftRoute's Tailoring route (GPLv3, Kitymeowmeow), planned by its
--            own planner and saved in Tools/data/craftroute_routes.json by
--            Tools/build/import_routes.py; reagents and recipe sources from
--            Crafting/Tailoring.lua; trainers from
--            Tools/data/Professions_Reference.docx and
--            Tools/data/profession_training.json
-- Generator: Tools/build/convert_professions.py
--
-- Regenerate with:  python3 Tools/build/convert_professions.py


AegisPathfinder:RegisterQuestShellPlusGuide("Tailoring (1-300)", {
	faction = "Both",
	category = "Profession",
	steps = {
		{
			type = "NOTE",
			title = "Tailoring (1-300)",
			note = "CraftRoute's cheapest 1-300 route, planned from auction prices of 30 July 2026. Craft counts are the average it takes, rounded up (about 773 crafts in total). For a route planned from today's prices, open Cheapest route on the shopping list.",
		},
		{
			type = "GRIND",
			title = "Reach level 5",
			note = "Apprentice Tailoring needs character level 5. This step clears itself when you get there.",
			level = 5,
		},
		{
			type = "TRAIN",
			title = "Learn Tailoring (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Velessa Brightstar (Alah'Thalas), Eldrin (Elwynn Forest), Uthrar Threx (Ironforge), Lawrence Schneider (Stormwind City).",
			faction = "Alliance",
			rank = { profession = "Tailoring", cap = 75 },
			npcs = { "Velessa Brightstar", "Eldrin", "Uthrar Threx", "Lawrence Schneider" },
		},
		{
			type = "TRAIN",
			title = "Learn Tailoring (Apprentice)",
			note = "Needs level 5; costs 5 copper. Trainers: Bowen Brisboise (Tirisfal Glades), Snang (Orgrimmar), Victor Ward (Undercity), Kil'hala (The Barrens).",
			faction = "Horde",
			rank = { profession = "Tailoring", cap = 75 },
			npcs = { "Bowen Brisboise", "Snang", "Victor Ward", "Kil'hala" },
		},
		{
			type = "USE",
			title = "Craft 212x Bolt of Linen Cloth",
			note = "Takes you from 1 to 50. Keep them for Linen Belt, Reinforced Linen Cape and Simple Kilt.",
			skill = { profession = "Tailoring", from = 1, to = 50 },
			craft = { item = "Bolt of Linen Cloth", count = 212 },
			reagents = { { item = "Linen Cloth", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 10",
			note = "Journeyman Tailoring needs character level 10. This step clears itself when you get there.",
			level = 10,
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Tailoring (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Velessa Brightstar (Alah'Thalas), Sellandus (Stormwind City), Grarnik Goodstitch (Stranglethorn Vale), Jormund Stonebrow (Ironforge).",
			faction = "Alliance",
			rank = { profession = "Tailoring", cap = 150 },
			npcs = { "Velessa Brightstar", "Sellandus", "Grarnik Goodstitch", "Jormund Stonebrow" },
		},
		{
			type = "TRAIN",
			title = "Train Journeyman Tailoring (Cap 150)",
			note = "Needs skill 50 and level 10; costs 5 silver. Trainers: Mahani (The Barrens), Rhiannon Davis (Undercity), Grarnik Goodstitch (Stranglethorn Vale), Magar (Orgrimmar).",
			faction = "Horde",
			rank = { profession = "Tailoring", cap = 150 },
			npcs = { "Mahani", "Rhiannon Davis", "Grarnik Goodstitch", "Magar" },
		},
		{
			type = "USE",
			title = "Craft 28x Linen Belt",
			note = "Takes you from 50 to 71.",
			skill = { profession = "Tailoring", from = 50, to = 71 },
			craft = { item = "Linen Belt", count = 28 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 1 }, { item = "Coarse Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Reinforced Linen Cape",
			note = "Takes you from 71 to 75.",
			skill = { profession = "Tailoring", from = 71, to = 75 },
			craft = { item = "Reinforced Linen Cape", count = 4 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 2 }, { item = "Coarse Thread", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 36x Bolt of Woolen Cloth",
			note = "Takes you from 75 to 101. Keep them for Gloves of Meditation.",
			skill = { profession = "Tailoring", from = 75, to = 101 },
			craft = { item = "Bolt of Woolen Cloth", count = 36 },
			reagents = { { item = "Wool Cloth", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 26x Reinforced Linen Cape",
			note = "Takes you from 101 to 111.",
			skill = { profession = "Tailoring", from = 101, to = 111 },
			craft = { item = "Reinforced Linen Cape", count = 26 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 2 }, { item = "Coarse Thread", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 31x Simple Kilt",
			note = "Takes you from 111 to 125.",
			skill = { profession = "Tailoring", from = 111, to = 125 },
			craft = { item = "Simple Kilt", count = 31 },
			reagents = { { item = "Bolt of Linen Cloth", qty = 4 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 20",
			note = "Expert Tailoring needs character level 20. This step clears itself when you get there.",
			level = 20,
		},
		{
			type = "TRAIN",
			title = "Train Expert Tailoring (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Georgio Bolero (Stormwind City), Timothy Worthington (Dustwallow Marsh), Meilosh (Timbermaw Tunnels), Jalane Ayrole (Stormwind City).",
			faction = "Alliance",
			rank = { profession = "Tailoring", cap = 225 },
			npcs = { "Georgio Bolero", "Timothy Worthington", "Meilosh", "Jalane Ayrole" },
		},
		{
			type = "TRAIN",
			title = "Train Expert Tailoring (Cap 225)",
			note = "Needs skill 125 and level 20; costs 50 silver. Trainers: Josef Gregorian (Undercity), Meilosh (Timbermaw Tunnels), Daryl Stack (Hillsbrad Foothills), Josephine Lister (Undercity).",
			faction = "Horde",
			rank = { profession = "Tailoring", cap = 225 },
			npcs = { "Josef Gregorian", "Meilosh", "Daryl Stack", "Josephine Lister" },
		},
		{
			type = "USE",
			title = "Craft 142x Bolt of Silk Cloth",
			note = "Takes you from 125 to 145. Keep them for Bright Yellow Shirt, Dark Silk Shirt, Silk Headband and what comes after.",
			skill = { profession = "Tailoring", from = 125, to = 145 },
			craft = { item = "Bolt of Silk Cloth", count = 142 },
			reagents = { { item = "Silk Cloth", qty = 4 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 5x Bright Yellow Shirt",
			note = "Takes you from 145 to 149.",
			skill = { profession = "Tailoring", from = 145, to = 149 },
			craft = { item = "Bright Yellow Shirt", count = 5 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 1 }, { item = "Yellow Dye", qty = 1 }, { item = "Fine Thread", qty = 1 } },
			source = "Pattern: Bright Yellow Shirt",
		},
		{
			type = "USE",
			title = "Craft 9x Gloves of Meditation",
			note = "Takes you from 149 to 157.",
			skill = { profession = "Tailoring", from = 149, to = 157 },
			craft = { item = "Gloves of Meditation", count = 9 },
			reagents = { { item = "Bolt of Woolen Cloth", qty = 4 }, { item = "Fine Thread", qty = 3 }, { item = "Elixir of Wisdom", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 12x Dark Silk Shirt",
			note = "Takes you from 157 to 168.",
			skill = { profession = "Tailoring", from = 157, to = 168 },
			craft = { item = "Dark Silk Shirt", count = 12 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 2 }, { item = "Gray Dye", qty = 2 }, { item = "Fine Thread", qty = 1 } },
			source = "Pattern: Dark Silk Shirt",
		},
		{
			type = "USE",
			title = "Craft 3x Silk Headband",
			note = "Takes you from 168 to 171.",
			skill = { profession = "Tailoring", from = 168, to = 171 },
			craft = { item = "Silk Headband", count = 3 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 3 }, { item = "Fine Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 4x Formal White Shirt",
			note = "Takes you from 171 to 175.",
			skill = { profession = "Tailoring", from = 171, to = 175 },
			craft = { item = "Formal White Shirt", count = 4 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 3 }, { item = "Bleach", qty = 2 }, { item = "Fine Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 122x Bolt of Mageweave",
			note = "Takes you from 175 to 185. Keep them for Black Mageweave Vest, White Bandit Mask, Simple Black Dress and what comes after.",
			skill = { profession = "Tailoring", from = 175, to = 185 },
			craft = { item = "Bolt of Mageweave", count = 122 },
			reagents = { { item = "Mageweave Cloth", qty = 5 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 16x Crimson Silk Vest",
			note = "Takes you from 185 to 200.",
			skill = { profession = "Tailoring", from = 185, to = 200 },
			craft = { item = "Crimson Silk Vest", count = 16 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 4 }, { item = "Red Dye", qty = 2 }, { item = "Fine Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "GRIND",
			title = "Reach level 35",
			note = "Artisan Tailoring needs character level 35. This step clears itself when you get there.",
			level = 35,
		},
		{
			type = "TRAIN",
			title = "Train Artisan Tailoring (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Georgio Bolero (Stormwind City), Timothy Worthington (Dustwallow Marsh), Meilosh (Timbermaw Tunnels).",
			faction = "Alliance",
			rank = { profession = "Tailoring", cap = 300 },
			npcs = { "Georgio Bolero", "Timothy Worthington", "Meilosh" },
		},
		{
			type = "TRAIN",
			title = "Train Artisan Tailoring (Cap 300)",
			note = "Needs skill 200 and level 35; costs 5 gold. Trainers: Josef Gregorian (Undercity), Meilosh (Timbermaw Tunnels).",
			faction = "Horde",
			rank = { profession = "Tailoring", cap = 300 },
			npcs = { "Josef Gregorian", "Meilosh" },
		},
		{
			type = "USE",
			title = "Craft 7x Crimson Silk Vest",
			note = "Takes you from 200 to 207.",
			skill = { profession = "Tailoring", from = 200, to = 207 },
			craft = { item = "Crimson Silk Vest", count = 7 },
			reagents = { { item = "Bolt of Silk Cloth", qty = 4 }, { item = "Red Dye", qty = 2 }, { item = "Fine Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 8x Black Mageweave Vest",
			note = "Takes you from 207 to 215.",
			skill = { profession = "Tailoring", from = 207, to = 215 },
			craft = { item = "Black Mageweave Vest", count = 8 },
			reagents = { { item = "Bolt of Mageweave", qty = 2 }, { item = "Silken Thread", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 12x White Bandit Mask",
			note = "Takes you from 215 to 225.",
			skill = { profession = "Tailoring", from = 215, to = 225 },
			craft = { item = "White Bandit Mask", count = 12 },
			reagents = { { item = "Bolt of Mageweave", qty = 1 }, { item = "Bleach", qty = 1 }, { item = "Heavy Silken Thread", qty = 1 } },
			source = "Pattern: White Bandit Mask",
		},
		{
			type = "USE",
			title = "Craft 15x Black Mageweave Vest",
			note = "Takes you from 225 to 235.",
			skill = { profession = "Tailoring", from = 225, to = 235 },
			craft = { item = "Black Mageweave Vest", count = 15 },
			reagents = { { item = "Bolt of Mageweave", qty = 2 }, { item = "Silken Thread", qty = 3 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 8x Simple Black Dress",
			note = "Takes you from 235 to 242.",
			skill = { profession = "Tailoring", from = 235, to = 242 },
			craft = { item = "Simple Black Dress", count = 8 },
			reagents = { { item = "Bolt of Mageweave", qty = 3 }, { item = "Black Dye", qty = 1 }, { item = "Heavy Silken Thread", qty = 1 }, { item = "Bleach", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 8x Black Mageweave Headband",
			note = "Takes you from 242 to 249.",
			skill = { profession = "Tailoring", from = 242, to = 249 },
			craft = { item = "Black Mageweave Headband", count = 8 },
			reagents = { { item = "Bolt of Mageweave", qty = 3 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 1x Red Mageweave Shoulders",
			note = "Takes you from 249 to 250.",
			skill = { profession = "Tailoring", from = 249, to = 250 },
			craft = { item = "Red Mageweave Shoulders", count = 1 },
			reagents = { { item = "Bolt of Mageweave", qty = 4 }, { item = "Red Dye", qty = 1 }, { item = "Heavy Silken Thread", qty = 1 } },
			source = "Pattern: Red Mageweave Shoulders",
		},
		{
			type = "USE",
			title = "Craft 19x Bolt of Runecloth",
			note = "Takes you from 250 to 260. Keep them for Runecloth Belt, Pillager's Shoes and Brightcloth Cloak.",
			skill = { profession = "Tailoring", from = 250, to = 260 },
			craft = { item = "Bolt of Runecloth", count = 19 },
			reagents = { { item = "Runecloth", qty = 5 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 3x Red Mageweave Headband",
			note = "Takes you from 260 to 262.",
			skill = { profession = "Tailoring", from = 260, to = 262 },
			craft = { item = "Red Mageweave Headband", count = 3 },
			reagents = { { item = "Bolt of Mageweave", qty = 4 }, { item = "Red Dye", qty = 2 }, { item = "Heavy Silken Thread", qty = 2 } },
			source = "Pattern: Red Mageweave Headband",
		},
		{
			type = "USE",
			title = "Craft 13x Runecloth Belt",
			note = "Takes you from 262 to 274.",
			skill = { profession = "Tailoring", from = 262, to = 274 },
			craft = { item = "Runecloth Belt", count = 13 },
			reagents = { { item = "Bolt of Runecloth", qty = 3 }, { item = "Rune Thread", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 6x Pillager's Shoes",
			note = "Takes you from 274 to 279.",
			skill = { profession = "Tailoring", from = 274, to = 279 },
			craft = { item = "Pillager's Shoes", count = 6 },
			reagents = { { item = "Bolt of Runecloth", qty = 2 }, { item = "Rugged Leather", qty = 2 }, { item = "Rune Thread", qty = 1 }, { item = "Fire Oil", qty = 1 } },
			source = "Trainer",
		},
		{
			type = "USE",
			title = "Craft 23x Brightcloth Cloak",
			note = "Takes you from 279 to 300.",
			skill = { profession = "Tailoring", from = 279, to = 300 },
			craft = { item = "Brightcloth Cloak", count = 23 },
			reagents = { { item = "Bolt of Runecloth", qty = 4 }, { item = "Gold Bar", qty = 2 }, { item = "Rune Thread", qty = 1 } },
			source = "Pattern: Brightcloth Cloak",
		},
		{
			type = "NOTE",
			title = "Guide Complete",
			note = "Tailoring is maxed at 300.",
		},
	},
})
